### ISSUE TITLE
Can't create a notebook on Mac

### ISSUE THREAD

**Issue by csu** [twosigma/beakerx#1066]
I'm running Beaker on Mac OS X 10.10.1. 

I get the following when I try to make a new notebook:
![screen shot 2015-01-17 at 4 55 30 pm](https://cloud.githubusercontent.com/assets/164822/5790610/081a61e2-9e6f-11e4-85e2-f2452f56bbea.jpg)

I get the following error when I try to make a new default notebook:

```
Error in library(Rserve) : there is no package called 'Rserve'
Execution halted
[qtp927327686-22] WARN org.eclipse.jetty.servlet.ServletHandler - 
javax.servlet.ServletException: org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:420)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1465)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.rest.RShellRest.startRserve(RShellRest.java:175)
    at com.twosigma.beaker.r.rest.RShellRest.newEvaluator(RShellRest.java:323)
    at com.twosigma.beaker.r.rest.RShellRest.getShell(RShellRest.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
    ... 30 more
[qtp927327686-22] WARN org.eclipse.jetty.servlet.ServletHandler - /rest/rsh/getShell
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.rest.RShellRest.startRserve(RShellRest.java:175)
    at com.twosigma.beaker.r.rest.RShellRest.newEvaluator(RShellRest.java:323)
    at com.twosigma.beaker.r.rest.RShellRest.getShell(RShellRest.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1465)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by scottdraves** [comment]
Thanks for the report Christopher.

About the 2nd issue, the default notebook has R in it, and it looks like you have installed R but not the R packages that Beaker needs to communicate with it.  On http://beakernotebook.com/getting-started you'll see a list. You also need XQuartz.  Btw you can change the default notebook to be whatever you want, see the FAQ.

About the 1st issue, first try exiting Beaker (bring the app to the front by clicking its icon in the dock and hitting command-q, and running it again.  Then right away click "New empty notebook".  If the problem persists, please report back with the contents of the JS console.  You can also use the Mac's Console app to look in the log, search for Beaker and see if there are any errors there.

**Comment by csu** [comment]
Thanks! Installing the R packages and XQuartz got both working. I can only see HTML, JS, and LaTeX though. I have Anaconda, R, and Node.js all installed, but it won't let me select them.

**Comment by scottdraves** [comment]
Cool.  Yea it is not as intuitive as it should be, sorry.

With the Notebook menu, open the Language Manager.  You should see buttons for each possible language.  Each button has a status indicator: gray means inactive, green means active, and yellow means it is in progress starting up.  Click on the language you want to add (presumably it is gray).  It should turn yellow, and after a while depending on how fast your computer is, it should go green.  Then close the language manager, and then you can pop up the language menu on any cell and change it to the new language you just added.

If a language is green, you can click it again to remove it from the notebook.

**Comment by csu** [comment]
Got it. Thanks. I can enable Java, R, and Node, but IPython won't work. Any ideas? I have anaconda installed in `~/anaconda`.

**Comment by scottdraves** [comment]
What happens when you try IPython?  Look for errors with the Console program and report them here.  Make sure that wherever your ipython binary is that it's in your PATH and that is set up in your .bash_profile.

**Comment by csu** [comment]
I have IPython in my PATH. Console in Chrome says:

```
 installing keydownHandler
:8801/9161b57/beaker/plugins/eval/ipythonPlugins/ipython/ipython.js:367 Using ipython 1.x compatibility mode: true
http://127.0.0.1:8801/9161b57/beaker/rest/plugin-services/IPython?command=i…otebook+is+running+at:+http:%2F%2F127.0.0.1:&startedIndicatorStream=stderr Failed to load resource: the server responded with a status of 500 (Server Error)
:8801/9161b57/beaker/plugins/eval/ipythonPlugins/ipython/ipython.js:352 failed to locate plugin service IPython Arguments[4]0: "<html>↵<head>↵<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>↵<title>Error 500 Server Error</title>↵</head>↵<body>↵<h2>HTTP ERROR: 500</h2>↵<p>Problem accessing /rest/plugin-services/IPython. Reason:↵<pre>    Server Error</pre></p>↵<hr /><i><small>Powered by Jetty://</small></i>↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵                                                ↵</body>↵</html>↵"1: 5002: function (name) {3: Objectcallee: (...)get callee: function ThrowTypeError() { [native code] }set callee: function ThrowTypeError() { [native code] }caller: (...)get caller: function ThrowTypeError() { [native code] }set caller: function ThrowTypeError() { [native code] }length: 4Symbol(Symbol.iterator): function ArrayValues() { [native code] }__proto__: Object
angular.js:9383 TypeError: Cannot read property 'spec' of undefined
    at http://127.0.0.1:8801/9161b57/beaker/app/mainapp/mainapp.js:131:41
    at wrappedCallback (http://127.0.0.1:8801/9161b57/beaker/vendor/bower_components/angular/angular.js:10905:81)
    at wrappedCallback (http://127.0.0.1:8801/9161b57/beaker/vendor/bower_components/angular/angular.js:10905:81)
    at http://127.0.0.1:8801/9161b57/beaker/vendor/bower_components/angular/angular.js:10991:26
    at Scope.$eval (http://127.0.0.1:8801/9161b57/beaker/vendor/bower_components/angular/angular.js:11906:28)
    at Scope.$digest (http://127.0.0.1:8801/9161b57/beaker/vendor/bower_components/angular/angular.js:11734:31)
    at Scope.$apply (http://127.0.0.1:8801/9161b57/beaker/vendor/bower_components/angular/angular.js:12012:24)
    at done (http://127.0.0.1:8801/9161b57/beaker/vendor/bower_components/angular/angular.js:7818:45)
    at completeRequest (http://127.0.0.1:8801/9161b57/beaker/vendor/bower_components/angular/angular.js:7991:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://127.0.0.1:8801/9161b57/beaker/vendor/bower_components/angular/angular.js:7947:11)
```

In Mac Console:

```
1/17/15 8:55:07.922 PM Beaker[24694]: Beaker App start JVM and launch browser
1/17/15 8:55:08.547 PM sandboxd[267]: ([23993]) storeuid(23993) deny mach-lookup com.apple.dock.server
1/17/15 8:55:08.767 PM Beaker[24694]: starting nginx instance (/Applications/Beaker.app/Contents/Resources/dist/nginx)
1/17/15 8:55:08.789 PM Beaker[24694]: nginx-stderr>nginx: [alert] could not open error log file: open() "/usr/local/var/log/nginx/error.log" failed (2: No such file or directory)
1/17/15 8:55:08.805 PM Beaker[24694]: [main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
1/17/15 8:55:09.381 PM Beaker[24694]: [main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802
1/17/15 8:55:09.384 PM Beaker[24694]: 
Connecting to http://127.0.0.1:8801/
1/17/15 8:55:09.000 PM kernel[0]: Google Chrome He (map: 0xffffff8024a87000) triggered DYLD shared region unnest for map: 0xffffff8024a87000, region 0x7fff8f800000->0x7fff8fa00000. While not abnormal for debuggers, this increases system memory footprint until the target exits.
1/17/15 8:55:15.351 PM Beaker[24694]: ipython-version-stderr>Error: No environment to deactivate
1/17/15 8:55:16.110 PM python[24723]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.1 instead of 10.10.1. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
1/17/15 8:55:16.110 PM python[24723]: 0   CarbonCore                          0x00007fff93e59dc3 ___Gestalt_SystemVersion_block_invoke + 113
1/17/15 8:55:16.110 PM python[24723]: 1   libdispatch.dylib                   0x00007fff8ab11c13 _dispatch_client_callout + 8
1/17/15 8:55:16.110 PM python[24723]: 2   libdispatch.dylib                   0x00007fff8ab11b26 dispatch_once_f + 117
1/17/15 8:55:16.110 PM python[24723]: 3   CarbonCore                          0x00007fff93e024da _Gestalt_SystemVersion + 987
1/17/15 8:55:16.110 PM python[24723]: 4   CarbonCore                          0x00007fff93e020c7 Gestalt + 144
1/17/15 8:55:16.111 PM python[24723]: 5   libQtCore.4.7.4.dylib               0x00000001060b1d5e _Z41__static_initialization_and_destruction_0ii + 46
1/17/15 8:55:16.111 PM python[24723]: 6   ???                                 0x00007fff68f58ceb 0x0 + 140734954310891
1/17/15 8:55:17.785 PM Beaker[24694]: ipython-hash-stderr>Error: No environment to deactivate
1/17/15 8:55:17.808 PM Beaker[24694]: ipython-hash-stderr>Traceback (most recent call last):
ipython-hash-stderr>  File "<stdin>", line 1, in <module>
1/17/15 8:55:17.808 PM Beaker[24694]: ipython-hash-stderr>ImportError: No module named IPython.lib
1/17/15 8:55:17.810 PM Beaker[24694]: [qtp1881901842-25] WARN org.eclipse.jetty.servlet.ServletHandler - /rest/plugin-services/IPython
1/17/15 8:55:17.810 PM Beaker[24694]: java.lang.RuntimeException: unable to get IPython hash
1/17/15 8:55:17.810 PM Beaker[24694]:   at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.hashIPythonPassword(PluginServiceLocatorRest.java:569)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.generateIPythonConfig(PluginServiceLocatorRest.java:582)
1/17/15 8:55:17.811 PM Beaker[24694]: 
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.locatePluginService(PluginServiceLocatorRest.java:349)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
1/17/15 8:55:17.811 PM Beaker[24694]: 
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
1/17/15 8:55:17.811 PM Beaker[24694]: 
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
1/17/15 8:55:17.811 PM Beaker[24694]: 
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1465)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
1/17/15 8:55:17.812 PM Beaker[24694]: 
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
1/17/15 8:55:17.812 PM Beaker[24694]:   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by scottdraves** [comment]
thank you for the detailed report.

```
1/17/15 8:55:15.351 PM Beaker[24694]: ipython-version-stderr>Error: No environment to deactivate
```

aha, are you running 1.2pre?  if so then maybe i can explain and maybe even offer a workaround.  What happens if you select Python3 instead of IPython?

**Comment by scottdraves** [comment]
I added the explanation of how to use the language manager to the FAQ: https://github.com/twosigma/beaker-notebook-www/commit/35617f458337ca042745778e9053250db23393fd
