### ISSUE TITLE
IPython does not initialise when installed with Homebrew

### ISSUE THREAD

**Issue by JonyEpsilon** [twosigma/beakerx#1162]
On a 2012 Macbook Air, Yosemite, Beaker v1.2-pre2, python and IPython installed with homebrew I find that "Initializing IPython" never completes. Looks like it might be getting mixed up between python installations.

Some info:

```
~ jony$ which python
/usr/local/bin/python
~ jony$ which ipython
/usr/local/bin/ipython
~ jony$ python --version
Python 2.7.9
~ jony$ ipython --version
2.3.1
```

Browser:

```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (IPython, line 0)
```

System log:

```
07/02/2015 18:23:17.579 Beaker[21102]: Beaker App start JVM and launch browser
07/02/2015 18:23:19.186 Beaker[21102]: starting nginx instance (/Applications/Beaker-v1.2pre2.app/Contents/Resources/dist/nginx)
07/02/2015 18:23:19.284 Beaker[21102]: [main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
07/02/2015 18:23:19.299 Beaker[21102]: nginx-stderr>nginx: [alert] could not open error log file: open() "/usr/local/var/log/nginx/error.log" failed (2: No such file or directory)
07/02/2015 18:23:20.440 Beaker[21102]: [main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802
07/02/2015 18:23:20.453 Beaker[21102]: 
Connecting to http://127.0.0.1:8801/
07/02/2015 18:23:22.283 Beaker[21102]: nginx-stderr>2015/02/07 18:23:22 [error] 21125#0: *9 open() "/Users/jony/.beaker/v1/nginx4336986424844470238/html/apple-touch-icon-precomposed.png" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /apple-touch-icon-precomposed.png HTTP/1.1", host: "127.0.0.1:8801"
07/02/2015 18:23:22.285 Beaker[21102]: nginx-stderr>2015/02/07 18:23:22 [error] 21125#0: *9 open() "/Users/jony/.beaker/v1/nginx4336986424844470238/html/apple-touch-icon.png" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /apple-touch-icon.png HTTP/1.1", host: "127.0.0.1:8801"
07/02/2015 18:23:29.942 Beaker[21102]: ipython-version-stderr>sh: deactivate: No such file or directory
07/02/2015 18:23:29.942 Beaker[21102]: ipython-version-stderr>Traceback (most recent call last):
07/02/2015 18:23:29.942 Beaker[21102]: ipython-version-stderr>  File "/Applications/Beaker-v1.2pre2.app/Contents/Resources/dist/config/plugins/eval/ipythonPlugins/ipython/ipythonPlugin", line 35, in <module>
07/02/2015 18:23:29.945 Beaker[21102]: ipython-version-stderr>    os.execlp("ipython", "ipython", "--version")
07/02/2015 18:23:29.946 Beaker[21102]: ipython-version-stderr>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 327, in execlp
ipython-version-stderr>    execvp(file, args)
07/02/2015 18:23:29.946 Beaker[21102]: ipython-version-stderr>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 344, in execvp
ipython-version-stderr>    _execvpe(file, args)
07/02/2015 18:23:29.946 Beaker[21102]: ipython-version-stderr>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 380, in _execvpe
ipython-version-stderr>    func(fullname, *argrest)
ipython-version-stderr>OSError: [Errno 2] No such file or directory
07/02/2015 18:23:30.095 Beaker[21102]: ipython-hash-stderr>sh: deactivate: No such file or directory
07/02/2015 18:23:30.096 Beaker[21102]: ipython-hash-stderr>Traceback (most recent call last):
07/02/2015 18:23:30.096 Beaker[21102]: ipython-hash-stderr>  File "/Applications/Beaker-v1.2pre2.app/Contents/Resources/dist/config/plugins/eval/ipythonPlugins/ipython/ipythonPlugin", line 37, in <module>
ipython-hash-stderr>    os.execlp("python", "python")
07/02/2015 18:23:30.096 Beaker[21102]: ipython-hash-stderr>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 327, in execlp
ipython-hash-stderr>    execvp(file, args)
07/02/2015 18:23:30.097 Beaker[21102]: ipython-hash-stderr>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 344, in execvp
ipython-hash-stderr>    _execvpe(file, args)
07/02/2015 18:23:30.097 Beaker[21102]: ipython-hash-stderr>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 380, in _execvpe
07/02/2015 18:23:30.097 Beaker[21102]: 
ipython-hash-stderr>    func(fullname, *argrest)
07/02/2015 18:23:30.098 Beaker[21102]: ipython-hash-stderr>OSError: [Errno 2] No such file or directory
07/02/2015 18:23:30.101 Beaker[21102]: [qtp574268151-25] WARN org.eclipse.jetty.servlet.ServletHandler - /rest/plugin-services/IPython
07/02/2015 18:23:30.102 Beaker[21102]: java.lang.RuntimeException: unable to get IPython hash
07/02/2015 18:23:30.102 Beaker[21102]:  at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.hashIPythonPassword(PluginServiceLocatorRest.java:564)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.generateIPythonConfig(PluginServiceLocatorRest.java:579)
07/02/2015 18:23:30.102 Beaker[21102]:  at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.locatePluginService(PluginServiceLocatorRest.java:355)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
07/02/2015 18:23:30.103 Beaker[21102]:  at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
07/02/2015 18:23:30.103 Beaker[21102]:  at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1465)
07/02/2015 18:23:30.103 Beaker[21102]:  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
07/02/2015 18:23:30.104 Beaker[21102]: 
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
07/02/2015 18:23:30.195 Beaker[21102]: restart-nginx-R-stderr>nginx: [alert] could not open error log file: open() "/usr/local/var/log/nginx/error.log" failed (2: No such file or directory)
07/02/2015 18:23:30.198 Beaker[21102]: restart-nginx-R-stderr>2015/02/07 18:23:30 [notice] 21138#0: signal process started
07/02/2015 18:23:30.199 Beaker[21102]: Running
07/02/2015 18:23:30.200 Beaker[21102]: 0: /Applications/Beaker-v1.2pre2.app/Contents/Resources/dist/config/plugins/eval/r/rPlugin
1: 8805
07/02/2015 18:23:32.215 Beaker[21102]: looking on stdout found:Server started
Acknowledge R plugin started
07/02/2015 18:23:32.216 Beaker[21102]: R-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
07/02/2015 18:23:32.216 Beaker[21102]: R-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8805
R-stderr waiting over
07/02/2015 18:23:32.742 Beaker[21102]: Done starting R
```

**Comment by scottdraves** [comment]
Thanks for the report Jony.  Looks like another result of this problem: https://github.com/twosigma/beaker-notebook/issues/703

will make sure the solution works for ipython from homebrew too.

**Comment by JonyEpsilon** [comment]
I'm not sure I understand the start-up process well enough to know what I'm talking about. But ... I think home-brew sets the path in `/etc/paths` and I would have expected that to be set for a login shell as used in https://github.com/twosigma/beaker-notebook/blob/master/core/beaker.command#L30 .

I get

```
~ jony$ bash -cl 'which python'
/usr/local/bin/python
```

 and a similar result if I make a python script with contents

```
import os

os.execvp('bash', ['bash', '-cl', 'which python'])
```

Anyway, again, it's quite possible I don't know what I'm talking about!

**Comment by scottdraves** [comment]
you are right but then what actually trips it up is:

```
07/02/2015 18:23:29.942 Beaker[21102]: ipython-version-stderr>sh: deactivate: No such file or directory
```

that's to select a virtual env, and is a temporary hack in place to work around enough of the PATH problem to get us doing python2 and 3 in the same notebook.

I think should Python3 work for you, and finds whatever version of ipy you've got, if the path is set up as you describe.

**Comment by zhiyzuo** [comment]
Hello,

Any solutions to these problems now? I cannot start IPython from Beaker as well. My config is as follow:
```
{
  "autocomplete-parameters" : "true",
  "pref-format" : "1",
  "edit-mode" : "default",
  "languages" : {
    "Python" : {
      "path" : "/Users/zhiyzuo/.virtualenvs/PyEnv/bin"
    },
    "IPython" : {
      "path" : "/Users/zhiyzuo/.virtualenvs/PyEnv/bin"
    },
    "R" : {
      "path" : "/usr/local/bin"
    }
  }
}
```
