### ISSUE TITLE
Updating moment library broke charts

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#1344]
TypeError: undefined is not a function
    at PlotAxis.getString (http://127.0.0.1:8801/167b8b3/beaker/outputdisplay/bko-plot/plotaxis.js:172:25)
    at PlotAxis.setGridlines (http://127.0.0.1:8801/167b8b3/beaker/outputdisplay/bko-plot/plotaxis.js:124:26)
    at Scope.scope.calcGridlines (http://127.0.0.1:8801/167b8b3/beaker/outputdisplay/bko-plot/bko-plot.js:206:23)
    at Scope.scope.update (http://127.0.0.1:8801/167b8b3/beaker/outputdisplay/bko-plot/bko-plot.js:1244:17)
    at Scope.scope.init (http://127.0.0.1:8801/167b8b3/beaker/outputdisplay/bko-plot/bko-plot.js:1239:17)
    at link (http://127.0.0.1:8801/167b8b3/beaker/outputdisplay/bko-plot/bko-plot.js:1268:15)
    at nodeLinkFn (http://127.0.0.1:8801/167b8b3/beaker/vendor/bower_components/angular/angular.js:6752:13)
    at compositeLinkFn (http://127.0.0.1:8801/167b8b3/beaker/vendor/bower_components/angular/angular.js:6146:13)
    at publicLinkFn (http://127.0.0.1:8801/167b8b3/beaker/vendor/bower_components/angular/angular.js:6042:30)
    at refresh (http://127.0.0.1:8801/167b8b3/beaker/app/mainapp/components/notebook/outputdisplay/outputdisplay-directive.js:54:39) <div bko13="" model="model" class="ng-scope">

```
    ret = moment(d).tz(this.axisTimezone).format("mm:ss.SSS");
```

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/commit/5abb4ec
