### ISSUE TITLE
Kdb crashes if not found

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1443]
instead of failing with the dialog box if you don't have Kdb installed you get

Running
0: /home/spot/beaker-notebook/core/config/plugins/eval/kdb/kdbPlugin
1: 8805
looking on stdout found:Server started
Acknowledge Kdb plugin started
Kdb-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
Kdb-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8805
Kdb-stderr waiting over
Done starting Kdb
Kdb-stderr>[qtp1545996869-16] WARN org.eclipse.jetty.servlet.ServletHandler -
Kdb-stderr>javax.servlet.ServletException: java.lang.Exception: Could not start kdb
...
Kdb-stderr>Caused by: java.lang.Exception: Could not start kdb
Kdb-stderr>     at com.twosigma.beaker.kdb.rest.KdbRest.getShell(KdbRest.java:77)
...
Kdb-stderr>Caused by: java.lang.Exception: QHOME is not set
Kdb-stderr>     at com.twosigma.beaker.kdb.KdbProcess.<init>(KdbProcess.java:71)
Kdb-stderr>     at com.twosigma.beaker.kdb.KdbShell.<init>(KdbShell.java:64)
Kdb-stderr>     at com.twosigma.beaker.kdb.rest.KdbRest.getShell(KdbRest.java:74)

**Comment by scottdraves** [comment]
just start the backend sooner?
