### ISSUE TITLE
this JSON crashes the plotter

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1462]
http://sharing.beakernotebook.com/gist/anonymous/c4096a24d4b7093d13bd

produces a blank plot and the following JS console error:

TypeError: Cannot read property 'auto_range_includes_zero' of undefined
    at Object.convertGroovyData (http://127.0.0.1:8801/bc7b2ce/beaker/app/dist/beakerOutputDisplay.js:6269:19)
    at Object.standardizeModel (http://127.0.0.1:8801/bc7b2ce/beaker/app/dist/beakerOutputDisplay.js:6912:25)
    at Scope.scope.standardizeData (http://127.0.0.1:8801/bc7b2ce/beaker/app/dist/beakerOutputDisplay.js:8152:42)
    at Scope.scope.init (http://127.0.0.1:8801/bc7b2ce/beaker/app/dist/beakerOutputDisplay.js:8221:17)

which is on this line of code:

```
if (axis.auto_range_includes_zero === true) {
```

**Comment by scottdraves** [comment]
can no longer reproduce.
