### ISSUE TITLE
empty outputcontainer crashes groovy

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1485]
```
import com.twosigma.beaker.jvm.object.OutputContainer
new OutputContainer()
```

produces

Apr 15, 2015 11:54:15 PM com.twosigma.beaker.jvm.serialization.BasicObjectSerializer writeObject
SEVERE: exception in serialization
org.codehaus.jackson.map.JsonMappingException: [no message for java.lang.NullPointerException]
    at org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:625)
    at org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:256)
    at org.codehaus.jackson.map.ObjectMapper.writeValue(ObjectMapper.java:1613)
    at org.codehaus.jackson.impl.JsonGeneratorBase.writeObject(JsonGeneratorBase.java:314)
    at com.twosigma.beaker.jvm.serialization.BasicObjectSerializer.writeObject(BasicObjectSerializer.java:169)
    at com.twosigma.beaker.jvm.serialization.PlotObjectSerializer.writeObject(PlotObjectSerializer.java:39)
    at com.twosigma.beaker.jvm.object.EvaluationResult$Serializer.serialize(EvaluationResult.java:59)
    at com.twosigma.beaker.jvm.object.EvaluationResult$Serializer.serialize(EvaluationResult.java:41)
...

**Comment by ildipo** [comment]
a fix commit is in the ildipo/internalrelease branch
