### ISSUE TITLE
IPython fails to start on some windows

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1500]
```
ipython-hash-stderr>Traceback (most recent call last):
ipython-hash-stderr>  File "<stdin>", line 1, in <module>
ipython-hash-stderr>ImportError: No module named IPython.lib
[qtp1529207541-24] WARN org.eclipse.jetty.servlet.ServletHandler - /rest/plugin-services/IPython
java.lang.RuntimeException: unable to get IPython hash
        at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.hashIPythonPassword(PluginServiceLocatorRest.java:585)
```

**Comment by paulochf** [comment]
I got this error when trying to run one example on a Ubuntu 14.04.2, after running `install-dependencies.sh`. One thing to mention is that I actually program in Python and manage versions ([yyuu/pyenv](https://github.com/yyuu/pyenv)) and envs ([yyuu/pyenv-virtualenvwrapper](https://github.com/yyuu/pyenv-virtualenvwrapper)) by myself.

Even with `install-dependencies.sh` installing {i}python system-wide, it gave the same error as above. Just in case, I'm posting the full initialization messages and stack error. The notebook I ran was the "Autotranslation" example located at http://beakernotebook.com/examples.

```
~/Programs/beaker ⌚ 14:35:58
$ ./beaker.command                      
starting nginx instance (/home/paulo/Programs/beaker/nginx)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

ipython-hash-stderr>Traceback (most recent call last):
ipython-hash-stderr>  File "<stdin>", line 1, in <module>
ipython-hash-stderr>ImportError: No module named IPython.lib
[qtp165037464-24] WARN org.eclipse.jetty.servlet.ServletHandler - /rest/plugin-services/IPython
java.lang.RuntimeException: unable to get IPython hash
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.hashIPythonPassword(PluginServiceLocatorRest.java:585)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.generateIPythonConfig(PluginServiceLocatorRest.java:600)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.locatePluginService(PluginServiceLocatorRest.java:394)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1465)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
restart-nginx-R-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
restart-nginx-R-stderr>2015/04/27 14:36:28 [notice] 13433#0: signal process started
Running
0: /home/paulo/Programs/beaker/config/plugins/eval/r/rPlugin
1: 8805
looking on stdout found:Server started
Acknowledge R plugin started
R-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
R-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8805
R-stderr waiting over
Done starting R
restart-nginx-Groovy-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
restart-nginx-Groovy-stderr>2015/04/27 14:36:35 [notice] 13495#0: signal process started
Running
0: /home/paulo/Programs/beaker/config/plugins/eval/groovy/groovyPlugin
1: 8807
looking on stdout found:Server started
Acknowledge Groovy plugin started
Groovy-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
Groovy-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8807
Groovy-stderr waiting over
Done starting Groovy
```

It opened the notebook, but it cannot execute Python code. R code worked. The, I tried to turn on the other languages in the Language Manager and Julia and IRuby didn't work as well.

**Comment by scottdraves** [comment]
Thanks for the report, Paulo.  Did you try setting up you prefs with the locations of the python/ipython binaries you want to according to this page https://github.com/twosigma/beaker-notebook/wiki/Language-Preferences ?

**Comment by paulochf** [comment]
Yes, I set up the system {I}Python as below:

```
{
  "languages" : {
    "IPython" : {
      "path" : "/usr/bin/ipython3"
    },
    "Python" : {
      "path" : "/usr/bin/python"
    },
    "Python3" : {
      "path" : "/usr/bin/python3.4"
    }
  },
  "pref-format" : "1",
  "advanced-mode" : true,
  "allow-anonymous-usage-tracking" : false
}
```

**Comment by scottdraves** [comment]
OK, that doesn't look right.  the install-dependencies script puts Python3 in ~/py3k, so the path there should be something like  "/home/paulochf/py3k/bin" (with your actual username on that machine substituted for paulochf).  For IPython, "/usr/local/bin" is where pip puts it.  And there is no "Python" language in Beaker so you should delete that section.

**Comment by paulochf** [comment]
There's no `~/py3k` here; IPython is in `/usr/local/bin` as you said.

I'm running the `install-dependencies.sh` again, just in case.

**Comment by scottdraves** [comment]
OK great.  Can you run the IPython plugin now, regardless of Python3 working?
If install-dependencies.sh doesn't create ~/py3k please send a transcript of it.
Or, it sounds like you have the Python you want already installed, so no need to install more, just tell Beaker where it is with the prefs file.

**Comment by paulochf** [comment]
Yeah, I waited for the error and the `virtualenv` part was the problem. I did this step manually and resumed the script from that part. Let's see how it will end.

**Comment by paulochf** [comment]
We are making progress. As the original script creates ~/py3k virtualenv but I already manage envs with virtualenvwrapper, I created it on my own way. Then, I activated it and using the following prefs:

```
{
  "languages" : {
    "IPython" : {
      "path" : "ipython"
    },
    "Python3" : {
      "path" : "python3"
    }
  },
  "pref-format" : "1",
  "advanced-mode" : true,
  "allow-anonymous-usage-tracking" : false
}
```

I also gave 777 to /var/log/nginx, so the `could not open file` is no more. Beaker now booted IPython, but still got some errors:

```
~/Programs/beaker ⌚ 10:53:39
$ ./beaker.command                
starting nginx instance (/home/paulo/Programs/beaker/nginx)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

Running
0: /home/paulo/Programs/beaker/config/plugins/eval/ipythonPlugins/ipython/ipythonPlugin
1: 8804
looking on stderr found:[I 10:54:09.882 NotebookApp] Using existing profile dir: '/home/paulo/.beaker/v1/nginx1697326816436389614/profile_beaker_backend_IPython'
looking on stderr found:[I 10:54:09.887 NotebookApp] Writing notebook server cookie secret to /home/paulo/.beaker/v1/nginx1697326816436389614/profile_beaker_backend_IPython/security/notebook_cookie_secret
looking on stderr found:[I 10:54:09.888 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
looking on stderr found:[I 10:54:09.911 NotebookApp] Serving notebooks from local directory: /home/paulo/Programs/beaker
looking on stderr found:[I 10:54:09.912 NotebookApp] 0 active kernels 
looking on stderr found:[I 10:54:09.912 NotebookApp] The IPython Notebook is running at: http://127.0.0.1:8804/
Acknowledge IPython plugin started
IPython-stderr>[I 10:54:09.912 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Done starting IPython
IPython-stderr>[I 10:54:10.246 NotebookApp] 302 POST /login?next=%2E (127.0.0.1) 3.74ms
IPython-stderr>[W 10:54:10.289 NotebookApp] Kernel not found: python2
IPython-stderr>[E 10:54:10.290 NotebookApp] {
IPython-stderr>      "Accept": "application/json, text/javascript, */*; q=0.01",
IPython-stderr>      "Connection": "close",
IPython-stderr>      "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
IPython-stderr>      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36",
IPython-stderr>      "Content-Length": "102",
IPython-stderr>      "Accept-Language": "en-US,en;q=0.8,pt;q=0.6",
IPython-stderr>      "X-Requested-With": "XMLHttpRequest",
IPython-stderr>      "Referer": "http://127.0.0.1:8801/beaker/",
IPython-stderr>      "Accept-Encoding": "gzip, deflate",
IPython-stderr>      "Origin": "http://127.0.0.1:8801",
IPython-stderr>      "Host": "127.0.0.1:8804",
IPython-stderr>      "Cookie": "sessionid=s4zifyz75gc397475huw3ugyr9a701cn; BAYEUX_BROWSER=cd22-qtlf2y5a3srri91cenap14iq; username-127-0-0-1-8804=2|1:0|10:1430229250|23:username-127-0-0-1-8804|48:ZTA4MzJmOTUtZGUxNy00MDM3LThkZmUtMDM3NDhjZTJkMDBi|174af4c98507f2fca80389922eae831eb5326c3542f0fc2b86ae4a7c364ff386"
IPython-stderr>    }
IPython-stderr>[E 10:54:10.292 NotebookApp] 501 POST /api/sessions (127.0.0.1) 6.61ms referer=http://127.0.0.1:8801/beaker/
^CIPython-stderr>[I 10:54:30.570 NotebookApp] interrupted

shutting down beaker
IPython-stdout>Serving notebooks from local directory: /home/paulo/Programs/beaker
IPython-stdout>0 active kernels 
IPython-stderr>[C 10:54:30.572 NotebookApp] received signal 15, stopping
IPython-stdout>The IPython Notebook is running at: http://127.0.0.1:8804/
IPython-stderr>[I 10:54:30.573 NotebookApp] Shutting down kernels
done, exiting
```

Beaker indicates "Loading plugin IPython" infinitely at the web interface, while the console drew my attention at:

```
IPython-stderr>[I 10:42:14.745 NotebookApp] 302 POST /login?next=%2E (127.0.0.1) 2.62ms
IPython-stderr>[W 10:42:14.869 NotebookApp] Kernel not found: python2
IPython-stderr>[E 10:54:10.290 NotebookApp] {
IPython-stderr>      "Accept": "application/json, text/javascript, */*; q=0.01",
IPython-stderr>      "Connection": "close",
IPython-stderr>      "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
IPython-stderr>      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36",
IPython-stderr>      "Content-Length": "102",
IPython-stderr>      "Accept-Language": "en-US,en;q=0.8,pt;q=0.6",
IPython-stderr>      "X-Requested-With": "XMLHttpRequest",
IPython-stderr>      "Referer": "http://127.0.0.1:8801/beaker/",
IPython-stderr>      "Accept-Encoding": "gzip, deflate",
IPython-stderr>      "Origin": "http://127.0.0.1:8801",
IPython-stderr>      "Host": "127.0.0.1:8804",
IPython-stderr>      "Cookie": "sessionid=s4zifyz75gc397475huw3ugyr9a701cn; BAYEUX_BROWSER=cd22-qtlf2y5a3srri91cenap14iq; username-127-0-0-1-8804=2|1:0|10:1430229250|23:username-127-0-0-1-8804|48:ZTA4MzJmOTUtZGUxNy00MDM3LThkZmUtMDM3NDhjZTJkMDBi|174af4c98507f2fca80389922eae831eb5326c3542f0fc2b86ae4a7c364ff386"
IPython-stderr>    }
```

**Comment by scottdraves** [comment]
i think you misunderstand the path part of the prefs.  it should be the directory that contains the "ipython" binary that you want to use.  if you just want to use the one in your path environment variable, then you don't need to set it at all.

**Comment by paulochf** [comment]
Not setting at all takes us back to the OP, but is it a problem? Was the missing kernel above caused by this?

**Comment by scottdraves** [comment]
Do you have /usr/local/bin in your path?  I believe normally it is.
And by that I mean, if you create a terminal and say "which ipython" what does it say?

**Comment by paulochf** [comment]
Yes, /usr/local/bin is there.

As I'm using pyenv, the command is `pyenv which`, and it gives the actual python installation path, which is `/home/paulo/Programs/repos/pyenv/versions/3.4.3/bin/python`.

Isn't there any IPython configuration override from beaker?

**Comment by scottdraves** [comment]
the prefs file is the override.

if that's where your python and ipython binaries are, then you should put

```
"Python3" : {
      "path" : "/home/paulo/Programs/repos/pyenv/versions/3.4.3/bin"
    }
```

that will give you Python3 in beaker.  note that most of the tutorials are written with python2 (known as IPython in Beaker).

**Comment by paulochf** [comment]
Ok, I misunderstood the prefs file, but yet omitting the executable name from the path not worked, giving the same last error.

Time to drop to docker version, I guess. =/

**Comment by scottdraves** [comment]
I am pretty sure we almost have it figured out but true, the docker container has the languages built in so it doesn't have this kind of problem at all.

**Comment by paulochf** [comment]
Will try docker, but still, I'm being "stubborn" here but you can bet it's help exchange. If you like, we can go further with this debug.

**Comment by scottdraves** [comment]
Hi Paulo, I added a couple of sentences making this more clear in the doc: https://github.com/twosigma/beaker-notebook/wiki/Language-Preferences
Thanks for helping improve that.
