### ISSUE TITLE
katex parser error

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1647]
```
$\S$
```

produces

```
ParseError: KaTeX parse error: Expected 'EOF', got '\S' at position 2: \S̲
    at new h (http://127.0.0.1:8801/ab011a1/beaker/app/dist/beakerVendor.js:101202:4740)
    at p.expect (http://127.0.0.1:8801/ab011a1/beaker/app/dist/beakerVendor.js:101202:5254)
    at p.parseInput (http://127.0.0.1:8801/ab011a1/beaker/app/dist/beakerVendor.js:101202:5521)
    at p.parse (http://127.0.0.1:8801/ab011a1/beaker/app/dist/beakerVendor.js:101202:5363)
    at a (http://127.0.0.1:8801/ab011a1/beaker/app/dist/beakerVendor.js:101204:6421)
    at Object.p [as render] (http://127.0.0.1:8801/ab011a1/beaker/app/dist/beakerVendor.js:101202:959)
    at i (http://127.0.0.1:8801/ab011a1/beaker/app/dist/beakerVendor.js:101206:1232)
    at o (http://127.0.0.1:8801/ab011a1/beaker/app/dist/beakerVendor.js:101206:1407)
    at s (http://127.0.0.1:8801/ab011a1/beaker/app/dist/beakerVendor.js:101206:2016)
    at preview (http://127.0.0.1:8801/ab011a1/beaker/app/dist/beakerApp.js:6805:47)(anonymous function) @ angular.js:10126(anonymous function) @ angular.js:7398Scope.$apply @ angular.js:12911(anonymous function) @ markdown-editable-directive.js:139CodeMirror.signal @ codemirror.js:8033onBlur @ codemirror.js:4152(anonymous function) @ codemirror.js:8199
```

**Comment by scottdraves** [comment]
should produce 
![screenshot - 05192015 - 11 12 34 pm](https://cloud.githubusercontent.com/assets/963093/7718321/a6055322-fe7c-11e4-8016-4d2ee821820e.png)

**Comment by samccone** [comment]
Seems to not even work on http://khan.github.io/KaTeX/ with `\S`
This might be worth raising on the KaTeX repo an an issue.

**Comment by scottdraves** [comment]
https://github.com/Khan/KaTeX/issues/237

**Comment by scottdraves** [comment]
It's just not in the subset of LaTeX that is supported.

We will need to catch these errors then, and pass the source through, but with a hover that reports that KaTeX error.  Also, report it on the js console.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1770
