### ISSUE TITLE
Progress report throws console error

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#1792]
See: http://sharing.beakernotebook.com/gist/anonymous/c0cc63591e9ac28bb603

Two possible bugs found with this notebook: One occurs when running the first cell of the notebook as is:

```
TypeError: Cannot assign to read only property 'status' of 4
    at Object.bkHelper.receiveEvaluationUpdate (http://127.0.0.1:8801/eb04f18/beaker/app/dist/beakerApp.js:2099:37)
    at Object.defineProperty.value [as print] (http://127.0.0.1:8801/eb04f18/beaker/app/dist/beakerApp.js:5353:20)
    at foo (eval at <anonymous> (http://127.0.0.1:8801/eb04f18/beaker/plugin/evaluator/javaScript.js:171:31), <anonymous>:5:12)
    at eval (eval at <anonymous> (http://127.0.0.1:8801/eb04f18/beaker/plugin/evaluator/javaScript.js:171:31), <anonymous>:17:3)
    at wrappedCallback (http://127.0.0.1:8801/eb04f18/beaker/app/dist/beakerVendor.js:46305:81)
    at http://127.0.0.1:8801/eb04f18/beaker/app/dist/beakerVendor.js:46391:26
    at Scope.$eval (http://127.0.0.1:8801/eb04f18/beaker/app/dist/beakerVendor.js:47434:28)
    at Scope.$digest (http://127.0.0.1:8801/eb04f18/beaker/app/dist/beakerVendor.js:47246:31)
    at Scope.$apply (http://127.0.0.1:8801/eb04f18/beaker/app/dist/beakerVendor.js:47538:24)
    at http://127.0.0.1:8801/eb04f18/beaker/app/dist/beakerVendor.js:49049:36
```

The second occurs if the type of the second cell is changed to R:

```
TypeError: Cannot read property 'result' of undefined
    at Scope.$scope.getOutputResult (codecelloutput-directive.js:34)
    at Object.get (angular.js:10903)
    at Scope.$digest (angular.js:12642)
    at updateLoadingStatusMessage (mainapp.js:66)
    at Object._impl.updateStatus (mainapp.js:570)
    at Object.bkHelper.updateStatus (helper.js:183)
    at doNext (evaluatejobmanager.js:163)
    at evaluateJob.then.job.finished (evaluatejobmanager.js:180)
    at _fulfilled (q.js:798)
    at self.promiseDispatch.done (q.js:827)
```

**Comment by ildipo** [comment]
It looks like you cannot beaker.print('....') in a callback or deferred function.
