### ISSUE TITLE
class loader error initializing spark

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1855]
```
[ERROR] [SparkContext]: Error initializing SparkContext.
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at com.twosigma.beaker.jvm.classloader.AbstractClassLoader.loadClass(AbstractClassLoader.java:130)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
```

to reproduce:
1) download spark 1.4 (prebuilt for hadoop 2.4+)
2) download http://sharing.beakernotebook.com/gist/anonymous/c5fe218d5cb5b21f2b00
3) edit scala classpath with location of your spark jar
4) run the 1st cell

are we missing a lock?

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1861

however spark still fails trying to load a GUI.
