### ISSUE TITLE
ggmap crashes R backend

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1878]
following http://blog.dominodatalab.com/geographic-visualization-with-rs-ggmaps/:

```
library(ggmap);
qmap(location = "boston university", zoom = 14, source = "osm");
```

```
org.apache.batik.bridge.BridgeException: file:/Users/spot/.beaker/v1/nginx5848578851653442193/rplot3770598447939828330.svg:0
The URI "data:image/png;base64,iVBORw0..."
on element <image> can't be opened because:
URL data in unsupported format or corrupt
at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
...
at com.twosigma.beaker.r.utils.RServerEvaluator.addSvgResults(RServerEvaluator.java:256)
```

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2084
