### ISSUE TITLE
Trying an R plot with qmap I run into a long series of errors with transcoding

### ISSUE THREAD

**Issue by k-dahl** [twosigma/beakerx#1880]
Was doing the demo here: 

http://blog.dominodatalab.com/geographic-visualization-with-rs-ggmaps/

```
org.apache.batik.bridge.BridgeException: file:/C:/Users/<ME>/Programs/config/plugins/eval/r/rplot.svg:0
The URI "data:image/png;base64,<LONG ENCODED STRING>

on element <image> can't be opened because:
URL data in unsupported format or corrupt
    at org.apache.batik.bridge.UserAgentAdapter.getBrokenLinkDocument(Unknown Source)
    at org.apache.batik.bridge.SVGImageElementBridge.createRasterImageNode(Unknown Source)
    at org.apache.batik.bridge.SVGImageElementBridge.createImageGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.SVGImageElementBridge.buildImageGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.SVGImageElementBridge.createGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.build(Unknown Source)
    at org.apache.batik.bridge.SVGUseElementBridge.buildCompositeGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.SVGUseElementBridge.createGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.build(Unknown Source)
    at org.apache.batik.bridge.SVGPatternElementBridge.extractLocalPatternContent(Unknown Source)
    at org.apache.batik.bridge.SVGPatternElementBridge.extractPatternContent(Unknown Source)
    at org.apache.batik.bridge.SVGPatternElementBridge.createPaint(Unknown Source)
    at org.apache.batik.bridge.PaintServer.convertURIPaint(Unknown Source)
    at org.apache.batik.bridge.PaintServer.convertPaint(Unknown Source)
    at org.apache.batik.bridge.PaintServer.convertFillPaint(Unknown Source)
    at org.apache.batik.bridge.PaintServer.convertFillAndStroke(Unknown Source)
    at org.apache.batik.bridge.SVGShapeElementBridge.createShapePainter(Unknown Source)
    at org.apache.batik.bridge.SVGRectElementBridge.createShapePainter(Unknown Source)
    at org.apache.batik.bridge.SVGShapeElementBridge.buildGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildComposite(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildComposite(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildComposite(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildComposite(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.build(Unknown Source)
    at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
    at org.apache.batik.transcoder.image.ImageTranscoder.transcode(Unknown Source)
    at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
    at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
    at com.twosigma.beaker.r.utils.RServerEvaluator.addSvgResults(RServerEvaluator.java:256)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:551)
Jul 01, 2015 11:26:34 AM com.twosigma.beaker.r.utils.RServerEvaluator addSvgResults
SEVERE: ERROR converting SVG results
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
file:/C:/Users/<ME>/Programs/config/plugins/eval/r/rplot.svg:0
```

Smallest recreation:

```
#install.packages("ggmap")
library(ggmap)

qmap(location = "boston university") 
```

Same code works fine in RStudio.

**Comment by scottdraves** [comment]
Yea we will be looking at this shortly: https://github.com/twosigma/beaker-notebook/issues/1878
I was following the exact same blog :)

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2084
