### ISSUE TITLE
Using Docker Beaker notebook 1.3.1: R language backend failed

### ISSUE THREAD

**Issue by pseudonymcp** [twosigma/beakerx#1918]
When running the docker image and executing an R cell, I get an "R language backend failed!" error. 
When starting the container there is also an Nginx error message:

Stderr log from starting the container and running an R cell:

```
starting nginx instance (/home/beaker/src/core/nginx)
nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to https://c569e0a45634:8800/
Submit this password: 4API07iR6WF0MVh

restart-nginx-IPython-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
restart-nginx-IPython-stderr>2015/07/11 19:29:10 [notice] 77#0: signal process started
Running
0: /home/beaker/src/core/config/plugins/eval/ipythonPlugins/ipython/ipythonPlugin
1: 8804
IPython-stderr>[I 19:29:11.138 NotebookApp] Using existing profile dir: u'/home/beaker/.beaker/v1/nginx1353221801172463837/profile_beaker_backend_IPython'
IPython-stderr>[I 19:29:11.142 NotebookApp] Writing notebook server cookie secret to /home/beaker/.beaker/v1/nginx1353221801172463837/profile_beaker_backend_IPy
thon/security/notebook_cookie_secret
IPython-stderr>[I 19:29:11.143 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
IPython-stderr>[W 19:29:11.157 NotebookApp] Terminals not available (error was No module named terminado)
IPython-stderr>[I 19:29:11.157 NotebookApp] Serving notebooks from local directory: /home/beaker/src/core
IPython-stderr>[I 19:29:11.157 NotebookApp] 0 active kernels
IPython-stderr>[I 19:29:11.157 NotebookApp] The IPython Notebook is running at: http://127.0.0.1:8804/
IPython-stderr>[I 19:29:11.157 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Done starting IPython
IPython-stderr>[I 19:29:11.237 NotebookApp] 302 POST /login?next=%2F (127.0.0.1) 0.99ms
IPython-stderr>[I 19:29:11.331 NotebookApp] Kernel started: 52175351-dae0-406a-ae79-498d30f99be0
restart-nginx-R-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
restart-nginx-R-stderr>2015/07/11 19:29:12 [notice] 109#0: signal process started
Running
0: /home/beaker/src/core/config/plugins/eval/r/rPlugin
1: 8805
nginx-stderr>2015/07/11 19:29:12 [error] 80#0: *56 open() "/home/beaker/.beaker/v1/nginx1353221801172463837/html/restart.694315355365/present.html" failed (2: N
o such file or directory), client: 127.0.0.1, server: , request: "GET /restart.694315355365/present.html HTTP/1.1", host: "127.0.0.1:8803"
nginx-stderr>2015/07/11 19:29:12 [error] 80#0: *56 open() "/home/beaker/.beaker/v1/nginx1353221801172463837/html/restart.694315355365/present.html" failed (2: N
o such file or directory), client: 127.0.0.1, server: , request: "GET /restart.694315355365/present.html HTTP/1.1", host: "127.0.0.1:8803"
nginx-stderr>2015/07/11 19:29:12 [error] 80#0: *56 open() "/home/beaker/.beaker/v1/nginx1353221801172463837/html/restart.694315355365/present.html" failed (2: N
o such file or directory), client: 127.0.0.1, server: , request: "GET /restart.694315355365/present.html HTTP/1.1", host: "127.0.0.1:8803"
nginx-stderr>2015/07/11 19:29:12 [error] 80#0: *56 open() "/home/beaker/.beaker/v1/nginx1353221801172463837/html/restart.694315355365/present.html" failed (2: N
o such file or directory), client: 127.0.0.1, server: , request: "GET /restart.694315355365/present.html HTTP/1.1", host: "127.0.0.1:8803"
Done starting R
nginx-stderr>2015/07/11 19:29:12 [error] 113#0: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.59.3, server: c569e
0a45634, request: "GET /3072e5e/r.611479655664/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "192.168.59.103:8800", referrer
: "https://192.168.59.103:8800/beaker/"
nginx-stderr>2015/07/11 19:29:12 [error] 113#0: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.59.3, server: c569e
0a45634, request: "GET /3072e5e/r.611479655664/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "192.168.59.103:8800", referrer
: "https://192.168.59.103:8800/beaker/"
nginx-stderr>2015/07/11 19:29:12 [error] 113#0: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.59.3, server: c569e
0a45634, request: "GET /3072e5e/r.611479655664/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "192.168.59.103:8800", referrer
: "https://192.168.59.103:8800/beaker/"
nginx-stderr>2015/07/11 19:29:12 [error] 113#0: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.59.3, server: c569e
0a45634, request: "GET /3072e5e/r.611479655664/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "192.168.59.103:8800", referrer
: "https://192.168.59.103:8800/beaker/"
nginx-stderr>2015/07/11 19:29:12 [error] 113#0: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.59.3, server: c569e
0a45634, request: "GET /3072e5e/r.611479655664/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "192.168.59.103:8800", referrer
: "https://192.168.59.103:8800/beaker/"
nginx-stderr>2015/07/11 19:29:12 [error] 113#0: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.59.3, server: c569e
0a45634, request: "GET /3072e5e/r.611479655664/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "192.168.59.103:8800", referrer
: "https://192.168.59.103:8800/beaker/"
nginx-stderr>2015/07/11 19:29:12 [error] 113#0: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.59.3, server: c569e
0a45634, request: "GET /3072e5e/r.611479655664/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "192.168.59.103:8800", referrer
: "https://192.168.59.103:8800/beaker/"
nginx-stderr>2015/07/11 19:29:13 [error] 113#0: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.59.3, server: c569e
0a45634, request: "GET /3072e5e/r.611479655664/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "192.168.59.103:8800", referrer
: "https://192.168.59.103:8800/beaker/"
R-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
nginx-stderr>2015/07/11 19:29:13 [error] 113#0: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.59.3, server: c569e
0a45634, request: "GET /3072e5e/r.611479655664/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "192.168.59.103:8800", referrer
: "https://192.168.59.103:8800/beaker/"
nginx-stderr>2015/07/11 19:29:13 [error] 113#0: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.59.3, server: c569e
0a45634, request: "GET /3072e5e/r.611479655664/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "192.168.59.103:8800", referrer
: "https://192.168.59.103:8800/beaker/"
R-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8805
R-stderr waiting over
R-stderr>Jul 11, 2015 7:29:14 PM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
R-stderr>SEVERE: exception starting RServe
R-stderr>org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127
R-stderr>       at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:234)
R-stderr>       at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:431)
R-stderr>       at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:460)
R-stderr>Jul 11, 2015 7:29:14 PM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
R-stderr>SEVERE: exception starting RServe
R-stderr>org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127
R-stderr>       at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:234)
R-stderr>       at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:431)
R-stderr>       at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:473)
```

**Comment by scottdraves** [comment]
Thanks for the bug report.  Let me see what I can do about that, I think it should just be a matter of cherry picking the fix and pushing the container.

https://github.com/twosigma/beaker-notebook/commit/cd664b34ccd3bc19e365d4c1f7150694af02967c

**Comment by scottdraves** [comment]
container updated to v1.3.2

```
build time: 2015-07-12 03:08 UTC
version: v1.3.2-0-g2da061b
```
