### ISSUE TITLE
Groovy cell's not functional 

### ISSUE THREAD

**Issue by datafig** [twosigma/beakerx#2070]
Hi, 

First of all thanks for such a phenomenal product and open sourcing it. I have been able to make most of the languages work easily but having difficulty with Groovy. 

I get the following error when i create a Groovy cell and am not sure what's causing it. My setup is Mac OS X Yosemite with Homebrew and Anaconda Python Distribution. 

``` java
Groovy-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8805
Groovy-stderr waiting over
Groovy-stderr>[qtp1790421142-20] WARN org.eclipse.jetty.servlet.ServletHandler - Error for /rest/groovysh/ready
Groovy-stderr>java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
Groovy-stderr>  at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119)
Groovy-stderr>  at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:649)
Groovy-stderr>  at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
Groovy-stderr>  at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
Groovy-stderr>  at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
Groovy-stderr>  at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
Groovy-stderr>  at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
Groovy-stderr>  at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
Groovy-stderr>  at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
Groovy-stderr>  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1465)
Groovy-stderr>  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
Groovy-stderr>  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
Groovy-stderr>  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
Groovy-stderr>  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
Groovy-stderr>  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
Groovy-stderr>  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
Groovy-stderr>  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
Groovy-stderr>  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Groovy-stderr>  at org.eclipse.jetty.server.Server.handle(Server.java:370)
Groovy-stderr>  at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
Groovy-stderr>  at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
Groovy-stderr>  at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
Groovy-stderr>  at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
Groovy-stderr>  at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
Groovy-stderr>  at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
Groovy-stderr>  at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
Groovy-stderr>  at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
Groovy-stderr>  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
Groovy-stderr>  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
Groovy-stderr>  at java.lang.Thread.run(Thread.java:745)

```

**Comment by scottdraves** [comment]
Thank you you are very welcome! What version of Beaker are you using?

**Comment by scottdraves** [comment]
am not yet able to reproduce.

**Comment by datafig** [comment]
I have tried the latest DMG from the site. But now I am on the `master` of GitHub. Using `gradle run` for execution. 

Are there any external environment variables that beaker depends upon? Wondering if I am missing some external dependency.

**Comment by scottdraves** [comment]
That's baffling.  For Groovy there are no external deps.

**Comment by scottdraves** [comment]
That stack trace doesn't even have any of our code in it.

**Comment by datafig** [comment]
This `stacktrace` actually is repeated several times before it eventually fails. And I am experiencing this exact issue on all three machines I have (they are very similar all Yosemite/Homebrew).

**Comment by scottdraves** [comment]
What about the other JVM languages like Java, Scala, and Clojure?

**Comment by datafig** [comment]
Clojure and Scala works as soon as I click the button for adding a Groovy cell it errors out. 
![scrnsht](https://cloud.githubusercontent.com/assets/12907357/9153121/c9f70c14-3df9-11e5-8450-12ce28625c97.png)

**Comment by scottdraves** [comment]
Hm I am going to guess that it's not a dependency that's missing, but something in your env that confuses it.  Do you have JAVA_HOME or CLASSPATH set?

**Comment by datafig** [comment]
I have JAVA_HOME set to `/usr/libexec/java_home` which resolves to `/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home`

There is no CLASSPATH set

**Comment by scottdraves** [comment]
Well it's a long shot but you could try not defining it.  It is not necessary for the application in the DMG.
Remove it and any other envars from your .bash_profile.

Another possibility is some kind of class conflict.  Groovy loads in a bunch of jars that the other JVM languages do not.  Try editing `plugin/groovy/build.gradle` and remove the dependencies from org.apache.ivy to groovycsv and seee what happens.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/2193
