### ISSUE TITLE
Can't run multiple instances with 0.52.4

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#214]
I get these errors when trying to launch a second instance

nginx-stderr>2014/05/03 23:09:13 [emerg] 39099#0: bind() to 127.0.0.1:8801 failed (48: Address already in use)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
nginx-stderr>2014/05/03 23:09:13 [emerg] 39099#0: bind() to 127.0.0.1:8801 failed (48: Address already in use)
nginx-stderr>2014/05/03 23:09:13 [emerg] 39099#0: bind() to 127.0.0.1:8801 failed (48: Address already in use)
[main] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED SelectChannelConnector@127.0.0.1:8802: java.net.BindException: Address already in use
java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:444)
    at sun.nio.ch.Net.bind(Net.java:436)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
    at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
    at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.Server.doStart(Server.java:293)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at com.twosigma.beaker.core.Main.main(Main.java:102)
[main] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.Server@7740c621: java.net.BindException: Address already in use
java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:444)
    at sun.nio.ch.Net.bind(Net.java:436)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
    at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
    at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.Server.doStart(Server.java:293)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at com.twosigma.beaker.core.Main.main(Main.java:102)
Exception in thread "main" java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:444)
    at sun.nio.ch.Net.bind(Net.java:436)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
    at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
    at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.Server.doStart(Server.java:293)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at com.twosigma.beaker.core.Main.main(Main.java:102)
nginx-stderr>2014/05/03 23:09:13 [emerg] 39099#0: bind() to 127.0.0.1:8801 failed (48: Address already in use)
nginx-stderr>2014/05/03 23:09:13 [emerg] 39099#0: bind() to 127.0.0.1:8801 failed (48: Address already in use)
nginx-stderr>2014/05/03 23:09:13 [emerg] 39099#0: still could not bind()

**Comment by scottdraves** [comment]
does not happen on ubuntu or windows.
on mac the code that we have always used to test if a port is free seems to always return true.
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/java/com/twosigma/beaker/core/Main.java#L188

**Comment by scottdraves** [comment]
upgrading from u51 to u55 did nothing.

**Comment by scottdraves** [comment]
best hit from web research is https://bugs.openjdk.java.net/browse/JDK-6875176
but that was windows and closed years ago.

**Comment by jchendy** [comment]
I wonder if it's caused by an OS X update? I'm able to run multiple instance on my work Mac but not my personal Mac.

**Comment by scottdraves** [comment]
what OS versions are they?

**Comment by jchendy** [comment]
Work is OS X 10.9.2 (13C1021).

'java -version' produces:
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

Not sure about home.

**Comment by jchendy** [comment]
Okay, I figured out why I was confused yesterday. 

I can start any number of instances of 0.51, and after that I can start one instance of 52.4. But the second instance of 52.4 always fails. The port checker must be getting confused by the switch to 127.0.0.1.
