### ISSUE TITLE
Error using sqldf and tcltk libraries in R code

### ISSUE THREAD

**Issue by carloshdezv** [twosigma/beakerx#2298]
Hi,

Iam trying to use library(tcltk) in R code, but I got this error:

Error
 The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on **THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC**() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on **THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC**() to debug.
 **\* caught segfault ***
address 0x110, cause 'memory not mapped'
Traceback:
 1: fun(libname, pkgname)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(fun(libname, pkgname), error = identity)
 6: runHook(".onLoad", env, package.lib, package)
 7: loadNamespace(package, c(which.lib.loc, lib.loc))
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("E
rror in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcal
l, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(ms
g[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
12: try({    ns <- loadNamespace(package, c(which.lib.loc, lib.loc))    env <- attachNamespace(ns, pos = pos, deps)})
13: library(tcltk)
14: doTryCatch(return(expr), name, parentenv, handler)
15: tryCatchOne(expr, names, parentenv, handlers[[1L]])
16: tryCatchList(expr, classes, parentenv, handlers)
17: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("E
rror in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcal
l, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(ms
g[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
18: try({    library(tcltk)}, silent = TRUE)
19: withVisible(try({    library(tcltk)}, silent = TRUE))
aborting ...
 eval failed

<img width="1243" alt="screen shot 2015-09-05 at 18 14 46" src="https://cloud.githubusercontent.com/assets/13800686/9701688/298cbeb0-53fa-11e5-9634-37968787ca7c.png">

stderr:
java.net.SocketException: Protocol wrong type for socket
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:209)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:231)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:542)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:231)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:498)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:231)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:542)

Same behaviour with library(sqldf):

Error
 Loading required package: gsubfn
Loading required package: proto
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on **THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC**() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on **THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC**() to debug.
 **\* caught segfault ***
address 0x110, cause 'memory not mapped'
Traceback:
 1: fun(libname, pkgname)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(fun(libname, pkgname), error = identity)
 6: runHook(".onLoad", env, package.lib, package)
 7: loadNamespace(package, ...)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch(loadNamespace(package, ...), error = function(e) e)
12: requireNamespace("tcltk", quietly = TRUE)
13: fun(libname, pkgname)
14: doTryCatch(return(expr), name, parentenv, handler)
15: tryCatchOne(expr, names, parentenv, handlers[[1L]])
16: tryCatchList(expr, classes, parentenv, handlers)
17: tryCatch(fun(libname, pkgname), error = identity)
18: runHook(".onAttach", ns, dirname(nspath), nsname)
19: attachNamespace(ns, pos = pos, deps)
20: doTryCatch(return(expr), name, parentenv, handler)
21: tryCatchOne(expr, names, parentenv, handlers[[1L]])
22: tryCatchList(expr, classes, parentenv, handlers)
23: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("E
rror in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcal
l, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(ms
g[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
24: try({    ns <- loadNamespace(package, c(which.lib.loc, lib.loc))    env <- attachNamespace(ns, pos = pos, deps)})
25: library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc,     quietly = quietly)
26: .getRequiredPackages2(pkgInfo, quietly = quietly)
27: library(sqldf)
28: doTryCatch(return(expr), name, parentenv, handler)
29: tryCatchOne(expr, names, parentenv, handlers[[1L]])
30: tryCatchList(expr, classes, parentenv, handlers)
31: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("E
rror in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcal
l, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(ms
g[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
 eval failed

stderr:
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:231)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:498)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:231)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:542)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:231)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:498)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:231)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:542)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:231)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:498)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:231)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:542)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:172)
    at org.rosuda.REngine.Rserve.RConnection.shutdown(RConnection.java:320)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:570)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:209)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:231)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:542)

![image](https://cloud.githubusercontent.com/assets/13800686/9701695/c7c615a4-53fa-11e5-9366-994c027c0ae0.png)

Thanks

**Comment by carloshdezv** [comment]
This libraries work fine in ipython:

![image](https://cloud.githubusercontent.com/assets/13800686/9701700/6623eb54-53fb-11e5-8be7-15f58c754cf3.png)

**Comment by scottdraves** [comment]
thanks for the report, I'll look into it.

**Comment by scottdraves** [comment]
worked on master: https://pub.beakernotebook.com/#/publications/55ecea1c-a354-4a15-8c35-c95a72c99df7

**Comment by scottdraves** [comment]
and the error reproduces on 1.3.4, so this should be fixed in 1.4 coming up at the end of the month.
