### ISSUE TITLE
race condition in pub, redir breaks

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2502]
sometimes when i publish a notebook, instead of getting directed to the page for it, i get a blank web page with the following in the JS console:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module publications due to:
Error: [$injector:nomod] Module 'publications' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.28/$injector/nomod?p0=publications
    at VALIDITY_STATE_PROPERTY (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:34700:12)
    at https://pub.beakernotebook.com/js/beaker/beakerVendor.js:36299:17
    at ensure (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:36223:38)
    at module (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:36297:14)
    at https://pub.beakernotebook.com/js/beaker/beakerVendor.js:38499:22
    at forEach (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:34947:18)
    at loadModules (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:38493:5)
    at createInjector (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:38433:11)
    at doBootstrap (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:36066:20)
    at bootstrap (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:36081:12)
http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=publications&p1=Er…A%2F%2Fpub.beakernotebook.com%2Fjs%2Fbeaker%2FbeakerVendor.js%3A36081%3A12)VALIDITY_STATE_PROPERTY @ beakerVendor.js:34700(anonymous function) @ beakerVendor.js:38527forEach @ beakerVendor.js:34947loadModules @ beakerVendor.js:38493createInjector @ beakerVendor.js:38433doBootstrap @ beakerVendor.js:36066bootstrap @ beakerVendor.js:36081angularInit @ beakerVendor.js:35990(anonymous function) @ beakerVendor.js:56771jQuery.Callbacks.fire @ beakerVendor.js:8920jQuery.Callbacks.self.fireWith @ beakerVendor.js:9032jQuery.extend.ready @ beakerVendor.js:6405completed @ beakerVendor.js:6100
extensions::uncaught_exception_handler:8 Error in event handler for extension.onRequest: TypeError: Cannot read property 'removeEventListener' of null
    at bindShortcuts (chrome-extension://nlipoenfbbikpbjkfpfillcgkoblgpmj/javascripts/content_script.js:1:9506)
    at chrome-extension://nlipoenfbbikpbjkfpfillcgkoblgpmj/javascripts/content_script.js:1:13966handler @ extensions::uncaught_exception_handler:8
```

**Comment by grin** [comment]
@scottdraves looking at that error stack trace you included I can see there is an error `TypeError: Cannot read property 'removeEventListener' of null` at the bottom and that seems to be coming from a chrome extension. My current hypothesis is that it's one of your chrome extensions failing while trying to load/parse publications code and this in turn prevents the main publications module from loading. 

Could you re-test it with chrome extensions disabled? Thanks.

**Comment by scottdraves** [comment]
thanks for looking i see this now and then but if nobody else does & it's just an extension then forget it
