### ISSUE TITLE
stack trace on undefined name

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2507]
user error should only go in cell output, do not present stack trace in stderr window:

<img width="783" alt="screen shot 2015-09-27 at 1 27 50 pm" src="https://cloud.githubusercontent.com/assets/963093/10124146/c70437b8-651b-11e5-94b6-78ea4337122c.png">

**Comment by scottdraves** [comment]
syntax errors too:

```
SEVERE: null
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO CITY VALUES ($ CITIES[*][0].CID , ?, ?, ?) "; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO city VALUES ($ cities[0].cid , ?, ?, ?) [42001-189]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
    at org.h2.message.DbException.getSyntaxError(DbException.java:205)
    at org.h2.command.Parser.getSyntaxError(Parser.java:524)
    at org.h2.command.Parser.read(Parser.java:3120)
```

**Comment by scottdraves** [comment]
missing column:

```
SEVERE: null
org.h2.jdbc.JdbcSQLException: Column "COLOR" not found; SQL statement:
SELECT * FROM color WHERE color LIKE 'A%' [42122-189]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
    at org.h2.message.DbException.get(DbException.java:179)
    at org.h2.message.DbException.get(DbException.java:155)
    at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
    at org.h2.expression.CompareLike.optimize(CompareLike.java:87)
    at org.h2.command.dml.Select.prepare(Select.java:838)
    at org.h2.command.Parser.prepareCommand(Parser.java:246)
    at org.h2.engine.Session.prepareLocal(Session.java:461)
    at org.h2.engine.Session.prepareCommand(Session.java:403)
    at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
    at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
    at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
    at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:293)
    at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:293)
    at com.twosigma.beaker.sqlsh.utils.QueryExecutor.executeQuery(QueryExecutor.java:147)
    at com.twosigma.beaker.sqlsh.utils.QueryExecutor.executeQuery(QueryExecutor.java:79)
```
