### ISSUE TITLE
ipython backends broken in Docker

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2591]
beaker no longer seems to work with ipython v4 and even if I got back to https://github.com/twosigma/beaker-notebook/pull/2280
it still doesn't work.  what happened??

**Comment by scottdraves** [comment]
```
Python-stderr>Traceback (most recent call last):
IPython-stderr>  File "/Users/spot/beaker-notebook/core/config/plugins/eval/ipythonPlugins/ipython/ipythonPluginStart.py", line 24, in <module>
IPython-stderr>    sys.exit(start_ipython(["notebook", "--config=" + os.environ["beaker_ipython_notebook_config"]]))
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
IPython-stderr>    return launch_new_instance(argv=argv, **kwargs)
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
IPython-stderr>    app.initialize(argv)
IPython-stderr>  File "<decorator-gen-111>", line 2, in initialize
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
IPython-stderr>    return method(app, *args, **kwargs)
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
IPython-stderr>    super(TerminalIPythonApp, self).initialize(argv)
IPython-stderr>  File "<decorator-gen-7>", line 2, in initialize
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
IPython-stderr>    return method(app, *args, **kwargs)
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 386, in initialize
IPython-stderr>    self.parse_command_line(argv)
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
IPython-stderr>    return super(TerminalIPythonApp, self).parse_command_line(argv)
IPython-stderr>  File "<decorator-gen-4>", line 2, in parse_command_line
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
IPython-stderr>    return method(app, *args, **kwargs)
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
IPython-stderr>    return self.initialize_subcommand(subc, subargv)
IPython-stderr>  File "<decorator-gen-3>", line 2, in initialize_subcommand
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
IPython-stderr>    return method(app, *args, **kwargs)
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
IPython-stderr>    subapp = import_item(subapp)
IPython-stderr>  File "/Users/spot/anaconda/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
IPython-stderr>    module = __import__(package, fromlist=[obj])
IPython-stderr>ImportError: No module named notebook.notebookapp
```

**Comment by scottdraves** [comment]
False alarm (mostly).  On my mac this was a case of badly installed ipython.  `conda install jupyter` was required, not just `conda install ipython=4.0.0`.

but on the docker container (and probably in our ubuntu install deps sh), we prob need to update the installation.

**Comment by scottdraves** [comment]
That fixes IPython but Python3 crapping out with:

```
Python3-stderr>[W 02:52:52.179 NotebookApp] Unrecognized alias: '--ipython-dir=/home/beaker/.beaker/v1/nginx4653631866367739599', it will probably have no effect.
Python3-stderr>[C 02:52:52.184 NotebookApp] Bad config encountered during initialization:
Python3-stderr>[C 02:52:52.184 NotebookApp] Invalid argument: '--ipython-dir=/home/beaker/.beaker/v1/nginx4653631866367739599'
Python3-stdout>The Jupyter HTML Notebook.
Python3-stdout>This launches a Tornado based HTML Notebook Server that serves up an
Python3-stdout>HTML5/Javascript Notebook client.
Python3-stdout>Subcommands
Python3-stdout>-----------
Python3-stdout>Subcommands are launched as `jupyter-notebook cmd [args]`. For information on
Python3-stdout>using subcommand 'cmd', do: `jupyter-notebook cmd -h`.
Python3-stdout>list
Python3-stdout>    List currently running notebook servers in this profile.
Python3-stdout>Options
Python3-stdout>-------
```

**Comment by scottdraves** [comment]
```
IRuby-stderr>[I 03:07:53.146 NotebookApp] 302 POST /login?next=%2F (127.0.0.1) 0.86ms
IRuby-stderr>[W 03:07:53.261 NotebookApp] Kernel not found: ruby
```

**Comment by scottdraves** [comment]
For Ruby I think we just have to revert this:
https://github.com/twosigma/beaker-notebook/commit/eb1e974719b9e1c8b21cc82ea49c41c3f0838171#diff-9652288da9c8facb008f4f7b2ed61a5bL22

and go back to iruby cmd.
