### ISSUE TITLE
missing kdb results in stack trace and hang

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2605]
```
[qtp398572781-17] WARN org.eclipse.jetty.servlet.ServletHandler - 
javax.servlet.ServletException: java.lang.Exception: Could not start kdb
...
Caused by: java.lang.Exception: QHOME is not set
    at com.twosigma.beaker.kdb.KdbProcess.<init>(KdbProcess.java:71)
    at com.twosigma.beaker.kdb.KdbShell.<init>(KdbShell.java:64)
    at com.twosigma.beaker.kdb.rest.KdbRest.getShell(KdbRest.java:82)
    ... 47 more
[qtp398572781-17] WARN org.eclipse.jetty.servlet.ServletHandler - /rest/kdb/getShell
java.lang.Exception: Could not start kdb
    at com.twosigma.beaker.kdb.rest.KdbRest.getShell(KdbRest.java:85)
```

**Comment by scottdraves** [comment]
it should pop up the dialog about how to install the language.
instead the light goes yellow, sticks and blocks any other language from loading.

**Comment by scottdraves** [comment]
this looks great, please apply to all languages.
