### ISSUE TITLE
many notebooks broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2675]
https://pub.beakernotebook.com/#/publications/560b4ea6-5a57-4298-84e3-a3057c1ee4b4?fullscreen=true
![screen shot 2015-10-08 at 5 55 05 pm](https://cloud.githubusercontent.com/assets/963093/10382095/6c3318f0-6dee-11e5-8e8e-9e5398004fd5.png)

**Comment by scottdraves** [comment]
related? https://github.com/twosigma/beaker-notebook/issues/2673

**Comment by ildipo** [comment]
Not related. The real error is this one:

`6beakerVendor.js:44748 Error: [$injector:cdep] Circular dependency found: bkOutputDisplayDirective <- bkOutputDisplayFactory <- bkOutputDisplayDirective
http://errors.angularjs.org/1.2.28/$injector/cdep?p0=bkOutputDisplayDirective%20%3C-%20bkOutputDisplayFactory%20%3C-%20bkOutputDisplayDirective
    at VALIDITY_STATE_PROPERTY (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:34700:12)
    at Object.getService [as get] (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:38543:17)
    at addDirective (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:41426:51)
    at collectDirectives (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:40817:11)
    at compileNodes (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:40702:22)
    at compileNodes (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:40718:15)
    at compileNodes (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:40718:15)
    at compileNodes (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:40718:15)
    at compileNodes (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:40718:15)
    at compile (https://pub.beakernotebook.com/js/beaker/beakerVendor.js:40639:15) <div ng-include="getCellTypeUrl()" class="ng-scope">`

**Comment by ildipo** [comment]
Which is in beaker output displays. It actually works perfectly if you navigate to the notebook from the publication home page but it does not if you use the direct link, but if you toggle on and off the fullscreen it works

**Comment by ildipo** [comment]
There's a circular dependency in beaker output displays which we should remove.

**Comment by ildipo** [comment]
The other exception should be removed too.

**Comment by ildipo** [comment]
fixed and deployed
