### ISSUE TITLE
Unable to start beaker

### ISSUE THREAD

**Issue by ArthurZ** [twosigma/beakerx#2690]
On Ubuntu 14.04
Attempting to start Beaker with beaker.command
getting
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/twosigma/beaker/core/Main : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by scottdraves** [comment]
Thanks for the report.  What version of java do you have installed & how was it installed?
Did you run the install-dependencies.sh script?

**Comment by ArthurZ** [comment]
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

**Comment by scottdraves** [comment]
java 7 is at end-of-life, you should def upgrade :)

"after April 2015, Oracle will not post further updates of Java SE 7 to its public download sites"

**Comment by ArthurZ** [comment]
Turned out I have multiple versions of Java installed including Java 8. I switch to it with sudo update-alternatives --config java
But got the same Exception in thread "main" java.lang.UnsupportedClassVersionError: com/twosigma/beaker/core/Main : Unsupported major.minor version 52.0 error
Executing the install-dependencies.sh script

**Comment by ArthurZ** [comment]
Installing the dependencies took a while, the error did not go away:
bash: ./beaker.command.sh: No such file or directory
arthur@zareason-strata7440:~/Beaker/beaker-notebook-1.4.1-0-ge8427bf-ubuntu$ ./beaker.command
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/twosigma/beaker/core/Main : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by scottdraves** [comment]
do you have the JAVA_HOME environment set?
if so, unset it.  or make sure it points to Java8.

**Comment by ArthurZ** [comment]
Now set JAVA_HOME and got
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-8-oracle/jre/bin/java

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
If I check for Java installations I get
There are 5 choices for the alternative java (providing /usr/bin/java).

##   Selection    Path                                            Priority   Status

  0            /usr/lib/jvm/java-7-oracle/jre/bin/java          1074      auto mode
  1            /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java   1061      manual mode
  2            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      manual mode
  3            /usr/lib/jvm/java-7-oracle/jre/bin/java          1074      manual mode
- 4            /usr/lib/jvm/java-8-oracle/jre/bin/java          1073      manual mode
  5            /usr/local/java/jdk1.7.0_51/bin/java             1         manual mode

**Comment by ArthurZ** [comment]
Wrong path of course, needs to be /usr/lib/jvm/java-8-oracle
Finally, it is a victory, Beaker starts in my own browser.
A big thank you Scott!

**Comment by ArthurZ** [comment]
Python works, but not R. 
Error symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar

**Comment by ArthurZ** [comment]
stderr:

Oct 10, 2015 12:17:59 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve

SEVERE: exception starting RServe

org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused

```
at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)

at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)

at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:421)

at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:472)
```

Oct 10, 2015 12:18:03 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve

SEVERE: exception starting RServe

org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused

```
at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)

at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)

at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:421)

at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:472)
```

Oct 10, 2015 12:21:49 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve

SEVERE: exception starting RServe

org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused

```
at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)

at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)

at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:421)

at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:459)
```

Oct 10, 2015 12:21:49 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve

SEVERE: exception starting RServe

org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused

```
at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)

at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)

at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:421)

at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:472)
```

**Comment by scottdraves** [comment]
did you install the R packages listed at http://beakernotebook.com/getting-started?

```
install.packages('Rserve')
install.packages('ggplot2')
install.packages('devtools')
install.packages('RCurl')
install.packages('RJSONIO')
install.packages('jpeg')
install.packages('png')
install.packages('base64enc')
```

**Comment by ArthurZ** [comment]
I have a problem with the base R. Looks like Anaconda took over it. 
error Error symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar

**Comment by decisionstats** [comment]
still getting error.

ajay@Inspiron-3542:~/Downloads/beaker-notebook-1.4.2-0-ge55c059-ubuntu/beaker-notebook-1.4.2-0-ge55c059-ubuntu$ ./beaker.command

ERROR: JAVA_HOME is set to an invalid directory: /usr/local/jdk1.7.0_80

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

ajay@Inspiron-3542:~/Downloads/beaker-notebook-1.4.2-0-ge55c059-ubuntu/beaker-notebook-1.4.2-0-ge55c059-ubuntu$ echo $JAVA_HOME
/usr/local/jdk1.7.0_80
ajay@Inspiron-3542:~/Downloads/beaker-notebook-1.4.2-0-ge55c059-ubuntu/beaker-notebook-1.4.2-0-ge55c059-ubuntu$  sudo update-alternatives --config java
[sudo] password for ajay: 
There are 3 choices for the alternative java (providing /usr/bin/java).

##   Selection    Path                                           Priority   Status

  0            /usr/lib/jvm/java-8-oracle/jre/bin/java         1062      auto mode
  1            /usr/lib/jvm/java-6-openjdk-i386/jre/bin/java   1061      manual mode
  2            /usr/lib/jvm/java-7-oracle/jre/bin/java         2         manual mode
- 3            /usr/lib/jvm/java-8-oracle/jre/bin/java         1062      manual mode

Press enter to keep the current choice[*], or type selection number: 0
ajay@Inspiron-3542:~/Downloads/beaker-notebook-1.4.2-0-ge55c059-ubuntu/beaker-notebook-1.4.2-0-ge55c059-ubuntu$ echo $JAVA_HOME
/usr/local/jdk1.7.0_80
ajay@Inspiron-3542:~/Downloads/beaker-notebook-1.4.2-0-ge55c059-ubuntu/beaker-notebook-1.4.2-0-ge55c059-ubuntu$ ./beaker.command

ERROR: JAVA_HOME is set to an invalid directory: /usr/local/jdk1.7.0_80

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

ajay@Inspiron-3542:~/Downloads/beaker-notebook-1.4.2-0-ge55c059-ubuntu/beaker-notebook-1.4.2-0-ge55c059-ubuntu$

**Comment by decisionstats** [comment]
ok I fixed it with this

export JAVA_HOME="$(update-alternatives --query java | grep 'Value: ' | grep -o '/.*/jre')"
