### ISSUE TITLE
unable to run code after beaker successfully started

### ISSUE THREAD

**Issue by kaosbeat** [twosigma/beakerx#276]
Hi after installing beaker and all it's dependencies I get constantly get errors like 

```
nginx-stderr>2014/05/22 09:55:55 [error] 13681#0: *79 open() "/Users/kaos/.beaker/v1/nginx7675330217786563764/html/r.588897223782/cometd/connect" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "POST /r.588897223782/cometd/connect HTTP/1.1", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2014/05/22 09:55:56 [error] 13681#0: *64 open() "/Users/kaos/.beaker/v1/nginx7675330217786563764/html/groovy.087854565762/cometd/connect" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "POST /groovy.087854565762/cometd/connect HTTP/1.1", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2014/05/22 09:55:56 [error] 13681#0: *66 open() "/Users/kaos/.beaker/v1/nginx7675330217786563764/html/r.107172382742/cometd/connect" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "POST /r.107172382742/cometd/connect HTTP/1.1", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/" 

```

code is never evaluated

![_tutorial_bkr](https://cloud.githubusercontent.com/assets/204628/3051121/dc935920-e186-11e3-9475-01f6fd328b34.jpg)

ipython works from the commandline

```
solidKAOS:~ kaos$ ipython
Python 2.7.6 |Anaconda 1.9.2 (x86_64)| (default, Jan 10 2014, 11:23:15) 
Type "copyright", "credits" or "license" for more information.

IPython 1.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: 

```

as well as julia, R, node

Is this an nginx problem?

**Comment by scottdraves** [comment]
Thanks for the bug report.  What version OS do you have?  What browser are you using?  Do you see any errors on the JavaScript console?

It looks like the evaluator plugins are not loading, the background of the code cell should be green or blue.

**Comment by kaosbeat** [comment]
I'm using the latest chrome. Indeed the Python cells are not green, the R cells are blue though and can be evaluated using ctrl-Enter. I also cannot add a python cell from the insert menu.

![_tutorial_bkr](https://cloud.githubusercontent.com/assets/204628/3053959/b8226f4c-e1b1-11e3-931f-a7f5a1cfc600.jpg)

And I do have some console errors. Like I said, I can run ipython just fine

```
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 2), not all, not all, not all, only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) 
Using ipython 1.x compatibility mode: true ipython.js?_=1400763683815:335
POST http://127.0.0.1:8801/ipython.562667767968/kernels/?notebook=kernel.DXQAqM.7845F648F0754C948344D155B7F467B0 502 (Bad Gateway) jquery.js:7845
x.support.cors.e.crossDomain.send jquery.js:7845
x.extend.ajax jquery.js:7301
x.(anonymous function) jquery.js:7447
Kernel.start kernel.js?_=1400763687706:80
IPythonProto.newShell ipython.js?_=1400763683815:54
IPythonShell ipython.js?_=1400763683815:313
(anonymous function) evaluatorManager.js:113
pluginObj.onReady evaluatorManager.js:153
(anonymous function) ipython.js?_=1400763683815:320
(anonymous function) angular.js:7553
wrappedCallback angular.js:10905
wrappedCallback angular.js:10905
(anonymous function) angular.js:10991
Scope.$eval angular.js:11906
Scope.$digest angular.js:11734
Scope.$apply angular.js:12012
done angular.js:7818
completeRequest angular.js:7991
xhr.onreadystatechange angular.js:7947
TIMED OUT - waiting for ipython kernel to start ipython.js?_=1400763683815:103
Uncaught TypeError: Cannot read property 'send' of null kernel.js?_=1400763687706:321
backup  DXQAqM bkSession.js:37
2
Uncaught TypeError: Cannot read property 'send' of null kernel.js?_=1400763687706:321
backup  DXQAqM bkSession.js:37
6
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 2), not all, not all, not all, only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) epiceditor.js:133
6
Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 2), not all, not all, not all, only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) epiceditor.js:133
Using ipython 1.x compatibility mode: true ipython.js?_=1400763802844:335
POST http://127.0.0.1:8801/ipython.562667767968/kernels/?notebook=kernel.DXQAqM.93103E3D5F4A49E38AC51A82E32D1496 502 (Bad Gateway) jquery.js:7845
Uncaught TypeError: Cannot read property 'send' of null kernel.js?_=1400763687706:321
TIMED OUT - waiting for ipython kernel to start ipython.js?_=1400763802844:103
Uncaught TypeError: Cannot read property 'send' of null kernel.js?_=1400763808639:321
Uncaught TypeError: Cannot read property 'send' of null kernel.js?_=1400763687706:321
backup  DXQAqM bkSession.js:37
Uncaught TypeError: Cannot read property 'send' of null kernel.js?_=1400763808639:321
Uncaught TypeError: Cannot read property 'send' of null kernel.js?_=1400763687706:321
Uncaught TypeError: Cannot read property 'send' of null kernel.js?_=1400763808639:321
Uncaught TypeError: Cannot read property 'send' of null kernel.js?_=1400763687706:321
backup  DXQAqM bkSession.js:37
Uncaught TypeError: Cannot read property 'send' of null 
```

**Comment by scottdraves** [comment]
OK at least R works, that's good.  What happens if you run "ipython notebook" on your command line?

**Comment by kaosbeat** [comment]
ah seems like we're getting there:

```
solidKAOS:~ kaos$ ipython notebook
Traceback (most recent call last):
  File "//anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "//anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 544, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "//anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 312, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "//anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 362, in initialize
    self.parse_command_line(argv)
  File "//anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 307, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "//anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 474, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "//anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 89, in catch_config_error
    return method(app, *args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 405, in initialize_subcommand
    subapp = import_item(subapp)
  File "//anaconda/lib/python2.7/site-packages/IPython/utils/importstring.py", line 42, in import_item
    module = __import__(package, fromlist=[obj])
  File "//anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 73, in <module>
    from IPython.consoleapp import IPythonConsoleApp
  File "//anaconda/lib/python2.7/site-packages/IPython/consoleapp.py", line 43, in <module>
    from IPython.kernel.zmq.kernelapp import (
  File "//anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/kernelapp.py", line 54, in <module>
    from ipkernel import Kernel
  File "//anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/ipkernel.py", line 49, in <module>
    from zmqshell import ZMQInteractiveShell
  File "//anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/zmqshell.py", line 36, in <module>
    from IPython.core.payloadpage import install_payload_page
  File "//anaconda/lib/python2.7/site-packages/IPython/core/payloadpage.py", line 24, in <module>
    from docutils.core import publish_string
  File "//anaconda/lib/python2.7/site-packages/docutils/core.py", line 20, in <module>
    from docutils import frontend, io, utils, readers, writers
  File "//anaconda/lib/python2.7/site-packages/docutils/frontend.py", line 41, in <module>
    import docutils.utils
  File "//anaconda/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "//anaconda/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "//anaconda/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "//anaconda/python.app/Contents/lib/python2.7/locale.py", line 511, in getdefaultlocale
    return _parse_localename(localename)
  File "//anaconda/python.app/Contents/lib/python2.7/locale.py", line 443, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by scottdraves** [comment]
Looks like you have IPython installed but not IPython notebooks.  What platform are you on and how did you install IPython?

**Comment by kaosbeat** [comment]
Mac OSX,  I installed through anaconda, like mentioned on the install page for beaker

![beaker_notebook_-_getting_started](https://cloud.githubusercontent.com/assets/204628/3055198/04b9f4da-e1bf-11e3-88cf-a0c7ec08b0e8.jpg)

**Comment by scottdraves** [comment]
In a terminal can you run the command `conda list | grep ipython`

**Comment by kaosbeat** [comment]
```

$ conda list | grep ipython
ipython                   1.1.0                    py27_0  
ipython-notebook          1.1.0                    py27_1  
ipython-qtconsole         1.1.0                    py27_1 


```

**Comment by scottdraves** [comment]
Well if you installed with anaconda you should have the latest 2.0 of IPython.
Not sure how you got 1.1 and one that doesn't work at that.
Perhaps if you uninstall/reinstall IPython it will work.
You definitely need to be able to do `ipython notebook`
