### ISSUE TITLE
R backend error

### ISSUE THREAD

**Issue by upendrak** [twosigma/beakerx#2948]
I am very new to Beaker and when i opened a default notebook and ran R i got this error. The ipython shell works perfectly fine

Nov 15, 2015 11:06:23 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:422)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:473)
Nov 15, 2015 11:06:56 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:422)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:473)
Nov 15, 2015 11:07:02 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:422)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:473)

**Comment by scottdraves** [comment]
did you install the packages that Beaker depends on?
make sure you do so with the command-line R (not RStudio).
here's the exact list: http://beakernotebook.com/getting-started#R

**Comment by upendrak** [comment]
I missed that part. Yes, it works now after all those installations. Thanks

**Comment by scottdraves** [comment]
cool glad you got it going and thanks for closing the loop.
please don't hesitate to let us know of any other issues or questions you have.

**Comment by pyvinyas** [comment]
Hey I have the same error. All dependencies installed.
IPython works fine.
R just wont startup.
Getting a R Backend Failure.
`Apr 30, 2016 9:26:38 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused: connect
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:435)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:473)`

**Comment by scottdraves** [comment]
see https://stackoverflow.com/questions/36612451/cant-use-r-language-with-beaker-notebook-error-r-language-backend-failed for Vinyas's solution

**Comment by pyvinyas** [comment]
@scottdraves Me and him are the same person :)
