### ISSUE TITLE
exception in worker

### ISSUE THREAD

**Issue by mathsong** [twosigma/beakerx#2974]
one line in R:

```
library(babynames)
library(dplyr)
print(babynames, n=20)
```

I got error message below and was wondering if it was about "REXP" related to dplyr.

```
stderr:
Nov 19, 2015 1:31:27 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread run
SEVERE: exception in worker:
java.lang.OutOfMemoryError: Java heap space
    at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:149)
    at java.lang.StringCoding.decode(StringCoding.java:193)
    at java.lang.String.<init>(String.java:426)
    at org.rosuda.REngine.Rserve.protocol.REXPFactory.parseREXP(REXPFactory.java:354)
    at org.rosuda.REngine.Rserve.protocol.REXPFactory.parseREXP(REXPFactory.java:310)
    at org.rosuda.REngine.Rserve.protocol.REXPFactory.parseREXP(REXPFactory.java:310)
    at org.rosuda.REngine.Rserve.protocol.REXPFactory.parseREXP(REXPFactory.java:310)
    at org.rosuda.REngine.Rserve.RConnection.parseEvalResponse(RConnection.java:215)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:233)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:501)
```

**Comment by scottdraves** [comment]
works fine for me https://pub.beakernotebook.com/#/publications/564fb6e9-86b6-4368-a29e-ec63e81cc919

can you reproduce reliably?

**Comment by mathsong** [comment]
Then I guess it was "OutOfMemoryError". Thanks.
