### ISSUE TITLE
node.js cell / expression with modulus operator throws error

### ISSUE THREAD

**Issue by nrfm** [twosigma/beakerx#2979]
When evaluating the expression (3 % 4) in a  node.js cell the following error is thrown...

`Error
 URIError: URI malformed
    at decodeURIComponent (native)
    at /Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/node/app/app.js:31:48
    at callbacks (/Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/node/app/node_modules/express/lib/router/index.js:164:37)
    at param (/Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/node/app/node_modules/express/lib/router/index.js:138:11)
    at pass (/Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/node/app/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/node/app/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/node/app/node_modules/express/lib/router/index.js:33:10)
    at next (/Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/node/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.handle (/Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/node/app/node_modules/express/node_modules/connect/lib/middleware/basicAuth.js:99:9)
    at next (/Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/node/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)`

**Comment by scottdraves** [comment]
Thanks for the report, will look into this.
