### ISSUE TITLE
':plugin:node:installNodePackages' fails on Windows

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#2990]
Version 53da3fc.
Error message:

```
Caused by: org.gradle.process.internal.ExecException: Process 'command 'cmd'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
        at org.gradle.api.tasks.AbstractExecTask.exec(AbstractExecTask.java:54)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 99 more
```

**Comment by scottdraves** [comment]
thanks will look into this.  what version of node do you have?

**Comment by altavir** [comment]
Don't know. Just cloned the repository and tried to run build.

**Comment by scottdraves** [comment]
The windows dev docs say you should install node: https://github.com/twosigma/beaker-notebook/wiki/Windows-build-and-run
and put it in your path, so you should just be able open a cmd shell and type `node --version`

**Comment by altavir** [comment]
Ok, I don't need a node plugin anyway, so I slightly changed `installPlugin` task to allow selective plugin build:

```
task installPlugins {
  def pluginProjects
  if(project.hasProperty('beakerPlugins')){
      def selectedPlugins = beakerPlugins.split(",")
      pluginProjects = project.subprojects.grep {it.project.path.startsWith(':plugin:') && ( it.project.name.equals("core") || selectedPlugins.contains(it.project.name)) }
  } else {
      pluginProjects = project.subprojects.grep { it.project.path.startsWith(':plugin:') }
  }
  pluginProjects.each {
    installPlugins.dependsOn(it.project.path + ":installApp")
  }
}
```

Now (with `gradle build -PbeakerPlugins="jvm,groovy"` from gitcmd), I've got the following:

```
:core:npmInstall
'npm' is not recognized as an internal or external command,
operable program or batch file.
```

I just turned node plugin off, why do I need something from node package manager? Or it is necessary part of beaker installation?

**Comment by scottdraves** [comment]
it's needed for the build in general.

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by altavir** [comment]
Ok, thank you for the reply.
