### ISSUE TITLE
Windows: java.lang.UnsupportedOperationException: 'posix:permissions'

### ISSUE THREAD

**Issue by prosconi** [twosigma/beakerx#308]
When I try to run Beaker Notebook on Windows, I get the following stack trace:

```
Exception in thread "main" com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
  at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.<init>(DefaultBeakerConfig.java:60)
  at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.class(DefaultBeakerConfig.java:60)
  while locating com.twosigma.beaker.core.module.config.DefaultBeakerConfig
  while locating com.twosigma.beaker.core.module.config.BeakerConfig
    for parameter 0 at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.<init>(PluginServiceLocatorRest.java:69)
  at com.twosigma.beaker.core.module.URLConfigModule.configureServlets(URLConfigModule.java:69)
  while locating com.twosigma.beaker.core.rest.PluginServiceLocatorRest

1 error
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
        at com.twosigma.beaker.core.Main.main(Main.java:98)
Caused by: java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
        at java.nio.file.Files.createDirectory(Unknown Source)
        at java.nio.file.TempFileHelper.create(Unknown Source)
        at java.nio.file.TempFileHelper.createTempDirectory(Unknown Source)
        at java.nio.file.Files.createTempDirectory(Unknown Source)
        at com.twosigma.beaker.shared.module.util.GeneralUtilsImpl.createTempDirectory(GeneralUtilsImpl.java:188)
        at com.twosigma.beaker.shared.module.util.GeneralUtilsImpl.createTempDirectory(GeneralUtilsImpl.java:200)
        at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.<init>(DefaultBeakerConfig.java:75)
        at com.twosigma.beaker.core.module.config.DefaultBeakerConfig$$FastClassByGuice$$d3b17bd0.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        ... 2 more
```

[GeneralUtilsImpl.java](https://github.com/twosigma/beaker-notebook/blob/ccdd078aee94bd61728f9fbbf4dc2c26767c642b/shared/src/main/java/com/twosigma/beaker/shared/module/util/GeneralUtilsImpl.java#L188)

**Comment by scottdraves** [comment]
what do you get from `java -version`?

**Comment by prosconi** [comment]
```
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)
```

**Comment by scottdraves** [comment]
Thanks for the bug report, I'll fix this shortly.

**Comment by scottdraves** [comment]
fixed by https://github.com/twosigma/beaker-notebook/commit/deae060e7974fc6de2e9aede57bf049638b08fe1

**Comment by AnushaUKumar** [comment]
Exception in thread "main" java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:496)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
        at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
        at java.nio.file.Files.createTempDirectory(Files.java:950)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:296)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:245)
getting this error

**Comment by xgxxxxxxxxxxxxxxxxx** [comment]
how to solve it,please?

**Comment by Souvik-karmakar** [comment]
:\hadoop\sbin>hadoop jar C:\hadoop\share\hadoop\tools\lib\hadoop-streaming-3.4.0.jar -files "file:///C:/Users/aishw/OneDrive/Documents/mapper.py,file:///C:/Users/aishw/OneDrive/Documents/reducer.py" -mapper "C:\Users\aishw\AppData\Local\Programs\Python\Python311\python C:/Users/aishw/OneDrive/Documents/mapper.py" -reducer "C:\Users\aishw\AppData\Local\Programs\Python\Python311\python C:/Users/aishw/OneDrive/Documents/reducer.py" -input /user/hadoop/input/agg_user.csv -output /user/hadoop/output_new
Exception in thread "main" java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:492)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
        at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
        at java.nio.file.Files.createTempDirectory(Files.java:950)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:296)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:245)  
gettting this error?
