### ISSUE TITLE
Broken httpclient version 4.3.1 breaks other libraries?

### ISSUE THREAD

**Issue by jkarjala** [twosigma/beakerx#3209]
It seems Beaker currently includes a broken version of the Apache http client (4.3.1).

Trying to use Java libraries like the Google API client from Scala will break with an exception:

java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer

  at org.apache.http.params.AbstractHttpParams.getIntParameter(AbstractHttpParams.java:70)
  at org.apache.http.client.params.HttpClientParamConfig.getRequestConfig(HttpClientParamConfig.java:54)
  at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:806)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
  at com.google.api.client.http.apache.ApacheHttpRequest.execute(ApacheHttpRequest.java:67)
  at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
...

The same thing seems to happen with other libraries as well, e.g. see this discussion http://stackoverflow.com/questions/20613854/exception-when-getting-a-list-of-buckets-on-s3-using-jets3t. 

The httpclient version 4.3.2 would fix this issue. However, if I try to replace 4.3.1 with that in my Beaker installation, Beaker doesn't even start any more. 

Any ideas for a workaround or fix?

**Comment by scottdraves** [comment]
Thanks for the report.  Can you please publish the notebook that has this problem so I can see it and reproduce it?

**Comment by jkarjala** [comment]
It happens in our closed source library, but I will try to isolate it to a smaller example.

If I publish a scala notebook, will it include the jars defined in notebook scala classpath settings? Or do I have to upload them somewhere separately?

On 30 December 2015 19:50:52 EET, Scott Draves notifications@github.com wrote:

> Thanks for the report.  Can you please publish the notebook that has
> this problem so I can see it and reproduce it?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/twosigma/beaker-notebook/issues/3209#issuecomment-168044782

**JPK

**Comment by jkarjala** [comment]
I could reproduce this with a small notebook using the plain Google HTTP client v1.20.

I published the notebook to https://pub.beakernotebook.com/#/publications/5684e4b4-33ee-40ca-8938-24376f79e05a (first time publish, I hope it it OK).

**Comment by scottdraves** [comment]
thanks.  you should get the fix in v1.5 to be released in about 2 weeks.

**Comment by scottdraves** [comment]
Here's the notebook without the error:
https://pub.beakernotebook.com/#/publications/56859ada-2f80-4a7b-ba34-17e4395bd904
