### ISSUE TITLE
iruby broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#336]
on fresh ubuntu 14.04 build:

```
Running: /home/beaker/beaker-notebook/core/config/plugins/eval/ipythonPlugins/iruby/irubyPlugin  8807 8802
looking on stderr found:[ProfileCreate] Generating default config file: u'/home/beaker/.config/iruby/profile_default/ipython_config.py'
looking on stderr found:[ProfileCreate] Generating default config file: u'/home/beaker/.config/iruby/profile_default/ipython_notebook_config.py'
looking on stderr found:[ProfileCreate] Generating default config file: u'/home/beaker/.config/iruby/profile_default/ipython_nbconvert_config.py'
looking on stderr found:/var/lib/gems/1.9.1/gems/iruby-0.1.9/lib/iruby/command.rb:90:in `symlink': File exists - (/var/lib/gems/1.9.1/gems/iruby-0.1.9/lib/iruby/static, /home/beaker/.config/iruby/profile_default/static) (Errno::EEXIST)
looking on stderr found:        from /var/lib/gems/1.9.1/gems/iruby-0.1.9/lib/iruby/command.rb:90:in `create_profile'
looking on stderr found:        from /var/lib/gems/1.9.1/gems/iruby-0.1.9/lib/iruby/command.rb:61:in `run_ipython'
looking on stderr found:        from /var/lib/gems/1.9.1/gems/iruby-0.1.9/lib/iruby/command.rb:17:in `run'
looking on stderr found:        from /var/lib/gems/1.9.1/gems/iruby-0.1.9/bin/iruby:6:in `<top (required)>'
looking on stderr found:        from /usr/local/bin/iruby:23:in `load'
looking on stderr found:        from /usr/local/bin/iruby:23:in `<main>'
```

**Comment by scottdraves** [comment]
works on ubuntu 12.04 at home.

**Comment by scottdraves** [comment]
works on my main mac

**Comment by scottdraves** [comment]
Looks like this is an IRuby issue
https://github.com/minad/iruby/issues/26
