### ISSUE TITLE
Windows 7 - unable to start Beaker Notebook 1.5.1

### ISSUE THREAD

**Issue by mindtd** [twosigma/beakerx#3431]
Check Java -

C:\Beaker>java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)

C:\Beaker>echo %JAVA_HOME%
C:\Beaker\jre1.8.0_65

When starting Beaker Notebook from command line, c:\Beaker>beaker.command
Error -
c:\Beaker>REM limitations under the License.
Exception in thread "main" com.google.inject.ProvisionException: Guice provision
 errors:

1) Error injecting constructor, java.lang.NullPointerException
  at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.<init>(DefaultBe
akerConfig.java:91)
  at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.class(DefaultBea
kerConfig.java:91)
  while locating com.twosigma.beaker.core.module.config.DefaultBeakerConfig
  while locating com.twosigma.beaker.core.module.config.BeakerConfig
    for parameter 0 at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.<i
nit>(PluginServiceLocatorRest.java:69)
  at com.twosigma.beaker.core.module.URLConfigModule.configureServlets(URLConfig
Module.java:77)
  while locating com.twosigma.beaker.core.rest.PluginServiceLocatorRest

1 error
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java
:1013)
        at com.twosigma.beaker.core.Main.main(Main.java:211)
Caused by: java.lang.NullPointerException
        at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.<init>(Def
aultBeakerConfig.java:134)
        at com.twosigma.beaker.core.module.config.DefaultBeakerConfig$$FastClass
ByGuice$$d3b17bd0.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance
(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInsta
nce(DefaultConstructionProxyFactory.java:60)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorI
njector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(Constru
ctorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(Pr
oviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.ja
va:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(Provi
derToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(Inter
nalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParam
eterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParam
eterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorI
njector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(Constru
ctorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(Pr
oviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.ja
va:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(Provi
derToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(Inter
nalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:97
8)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.ja
va:1024)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        ... 2 more

**Comment by scottdraves** [comment]
thanks for the report, will have to look into this.
