### ISSUE TITLE
R Error ... R language backend failed.

### ISSUE THREAD

**Issue by amannj** [twosigma/beakerx#3439]
Hi there,

system:
os: ubuntu gnome 15.10
beaker:  version: 1.5.1-0-g6e6bdd3

thanks for your help

stderr:
Jan 28, 2016 10:53:25 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:431)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:469)
Jan 28, 2016 10:53:25 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:431)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:482)

running `installed.packages()` in terminal:
https://gist.github.com/amannj/1868e02b4d0d8360b7c2

**Comment by KnowledgeGarden** [comment]
Wow! All that info would be best put in a gist and linked.
Still, I am seeing a similar failure to start the R server on Win7. Hard to do a differential diagnosis because, no matter what I do, keep getting the message that it cannot start IPython, even though I followed the instructions to the letter, in both python 27 and python 34.

**Comment by amannj** [comment]
@KnowledgeGarden thanks, just fixed it. still open for suggestions.

**Comment by KnowledgeGarden** [comment]
May I ask how you fixed it? We can all learn from your experience!

**Comment by scottdraves** [comment]
I think he meant he fixed the long issue by using a gist.
i haven't seen this yet but will try to reproduce.
thanks both of you for the report.

**Comment by scottdraves** [comment]
dup https://github.com/twosigma/beaker-notebook/issues/3422
