### ISSUE TITLE
ipython notebook deprecated

### ISSUE THREAD

**Issue by ybahador** [twosigma/beakerx#3522]
I'm using the latest version of beaker (1.5.1) and ipython (4.1.1).

Initiating an ipython kernel would result in the following exception:

```
IPython-stderr>[TerminalIPythonApp] WARNING | Subcommand ipython notebook is deprecated and will be removed in future versions.
IPython-stderr>[TerminalIPythonApp] WARNING | You likely want to use jupyter notebook... continue in 5 sec. Press Ctrl-C to quit now.
IPython-stderr>Traceback (most recent call last):
IPython-stderr>  File "/home/b/Downloads/beaker-notebook-1.5.1-0-g6e6bdd3-ubuntu/beaker-notebook-1.5.1-0-g6e6bdd3-ubuntu/config/plugins/eval/ipythonPlugins/ipython/ipythonPluginStart.py", line 24, in <module>
IPython-stderr>    sys.exit(start_ipython(["notebook", "--config=" + os.environ["beaker_ipython_notebook_config"]]))
IPython-stderr>  File "/usr/lib/python2.7/site-packages/IPython/__init__.py", line 119, in start_ipython
IPython-stderr>    return launch_new_instance(argv=argv, **kwargs)
IPython-stderr>  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 588, in launch_instance
IPython-stderr>    app.initialize(argv)
IPython-stderr>  File "<decorator-gen-111>", line 2, in initialize
IPython-stderr>  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
IPython-stderr>    return method(app, *args, **kwargs)
IPython-stderr>  File "/usr/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 297, in initialize
IPython-stderr>    super(TerminalIPythonApp, self).initialize(argv)
IPython-stderr>  File "<decorator-gen-7>", line 2, in initialize
IPython-stderr>  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
IPython-stderr>    return method(app, *args, **kwargs)
IPython-stderr>  File "/usr/lib/python2.7/site-packages/IPython/core/application.py", line 401, in initialize
IPython-stderr>    self.parse_command_line(argv)
IPython-stderr>  File "/usr/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 292, in parse_command_line
IPython-stderr>    return super(TerminalIPythonApp, self).parse_command_line(argv)
IPython-stderr>  File "<decorator-gen-4>", line 2, in parse_command_line
IPython-stderr>  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
IPython-stderr>    return method(app, *args, **kwargs)
IPython-stderr>  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 485, in parse_command_line
IPython-stderr>    return self.initialize_subcommand(subc, subargv)
IPython-stderr>  File "/usr/lib/python2.7/site-packages/IPython/core/application.py", line 211, in initialize_subcommand
IPython-stderr>    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
IPython-stderr>  File "<decorator-gen-3>", line 2, in initialize_subcommand
IPython-stderr>  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
IPython-stderr>    return method(app, *args, **kwargs)
IPython-stderr>  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 416, in initialize_subcommand
IPython-stderr>    subapp = import_item(subapp)
IPython-stderr>  File "/usr/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
IPython-stderr>    module = __import__(package, fromlist=[obj])
IPython-stderr>ImportError: No module named notebook.notebookapp
```

Which is the output you would get if you would run the **ipython notebook** command manually.
Is it possible to fix this issue by launching the ipython session using the **jupyter-notebook** command?

**Comment by scottdraves** [comment]
it's recently been deprecated but it still works.
the real error is down below: `No module named notebook.notebookapp`
and if you google that error, it takes you here: http://stackoverflow.com/questions/31397421/ipython-server-cant-launch-no-module-named-notebook-notebookapp
which makes it sound like you don't have a complete installation, and you should 

```
pip install jupyter
```

**Comment by ybahador** [comment]
I had the notebook package installed for python3, installing it for python2 solved the issue.

Thanks.
