### ISSUE TITLE
Shebang at top of ipythonPlugin should be /usr/bin/env python

### ISSUE THREAD

**Issue by hxu** [twosigma/beakerx#3929]
I had an issue where I couldn't start any IPython shells because the Beaker was using the wrong Python interpreter.  Here's the stack trace from the server:

```
[qtp1727361096-20] WARN org.eclipse.jetty.servlet.ServletHandler - /rest/plugin-services/IPython
java.lang.RuntimeException: unable to get IPython hash
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.hashIPythonPassword(PluginServiceLocatorRest.java:614)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.generateIPythonConfig(PluginServiceLocatorRest.java:632)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.locatePluginService(PluginServiceLocatorRest.java:432)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
```

I had set the interpreter in beaker.pref.json, but it wasn't being respected, and I could launch the ipython notebook separately without a problem.

The fix for me was to change the shebang at the top of `config/plugins/eval/ipythonPlugins/ipython/ipythonPlugin` from `/usr/bin/python` to `/usr/bin/env python`, while having the virtualenv that contained ipython active.

Note that I did not use `install-dependencies`, and python was installed into a separate conda environment.

**Comment by scottdraves** [comment]
thanks for the report, i think you are onto something, we'll have to look at that.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/3927
