### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by mnavasiolava** [twosigma/beakerx#4288]
`gradle realclean build`
...

```
> gulp compile

[14:27:54] Using gulpfile ~/work/projects/beaker/beaker-notebook/core/gulpfile.js
[14:27:54] Starting 'compile'...
[14:27:54] Starting 'namespaceIPythonCss'...
[14:27:54] Finished 'namespaceIPythonCss' after 159 ms
[14:27:54] Starting 'compileBeakerScss'...
[14:27:54] Finished 'compileBeakerScss' after 603 ms
[14:27:54] Starting 'compileBeakerTemplates'...
[14:27:55] Finished 'compileBeakerTemplates' after 153 ms
[14:27:55] Starting 'buildIndexTemplate'...
[14:27:55] Finished 'buildIndexTemplate' after 1.3 ms
[14:27:55] Starting 'buildOutputDisplayTemplate'...
[14:27:55] Finished 'buildOutputDisplayTemplate' after 12 ms
[14:27:55] Finished 'compile' after 933 ms
fs.js:887
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/Users/mnavasiolava/work/projects/beaker/beaker-notebook/core/src/main/web/app/genweb/beakerApp.css'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at DestroyableTransform.TransformStream [as _transform] (/Users/mnavasiolava/work/projects/beaker/beaker-notebook/core/node_modules/gulp-header/index.js:38:12)
    at DestroyableTransform.Transform._read (/Users/mnavasiolava/work/projects/beaker/beaker-notebook/core/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/mnavasiolava/work/projects/beaker/beaker-notebook/core/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/mnavasiolava/work/projects/beaker/beaker-notebook/core/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/mnavasiolava/work/projects/beaker/beaker-notebook/core/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/mnavasiolava/work/projects/beaker/beaker-notebook/core/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Users/mnavasiolava/work/projects/beaker/beaker-notebook/core/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/mnavasiolava/work/projects/beaker/beaker-notebook/core/node_modules/readable-stream/lib/_stream_readable.js:632:7)

```

**Comment by mnavasiolava** [comment]
gulp-header 1.8.3 version has been released several hours ago. since then our build is broken.
if we fix gulp-header version at 1.8.2 this will solve the problem
