### ISSUE TITLE
out of memory error from autotranslation

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4747]
https://pub.beakernotebook.com/publications/fed86842-8029-11e6-9f10-0b35cd1c9021?fullscreen=true

it should clearly say the 16MB autotranslation limit has been exceeded in both the stack trace on the console (below) and in the python one in the cell.

```
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:569)
        at java.lang.StringBuilder.append(StringBuilder.java:190)
        at com.sun.jersey.core.util.ReaderWriter.readFromAsString(ReaderWriter.java:172)
        at com.sun.jersey.core.util.ReaderWriter.readFromAsString(ReaderWriter.java:157)
        at com.sun.jersey.core.provider.AbstractMessageReaderWriterProvider.readFromAsString(AbstractMessageReaderWriterProvider.java:114)
        at com.sun.jersey.core.impl.provider.entity.BaseFormProvider.readFrom(BaseFormProvider.java:67)
        at com.sun.jersey.core.impl.provider.entity.FormProvider.readFrom(FormProvider.java:73)
        at com.sun.jersey.core.impl.provider.entity.FormProvider.readFrom(FormProvider.java:58)
        at com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:488)
        at com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:552)
        at com.sun.jersey.server.impl.model.method.dispatch.FormDispatchProvider.processForm(FormDispatchProvider.java:103)
        at com.sun.jersey.server.impl.model.method.dispatch.FormDispatchProvider.access$000(FormDispatchProvider.java:68)
        at com.sun.jersey.server.impl.model.method.dispatch.FormDispatchProvider$FormParameterProvider.getInjectableValues(FormDispatchProvider.java:115)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$EntityParamInInvoker.getParams(AbstractResourceMethodDispatchProv\
ider.java:153)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.j\
ava:183)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
```

**Comment by scottdraves** [comment]
OK the user visible error has been improved but the real question is why the server ran out of memory?
It seems 5000x5000x20 = 500MB, which should be no problem.
Is there a leak or some other pathology that can be fixed so the server does not crash on this request?

**Comment by jaroslawmalekcodete** [comment]
I think the problem lies in jersey implementation
there is a method 
`com.sun.jersey.core.impl.provider.entity.BaseFormProvider-> readFrom->readFromAsString`
which uses
`com.sun.jersey.core.util.ReaderWriter -> readFromAsString`

public static final String readFromAsString(Reader reader) throws IOException {
       StringBuilder sb = new StringBuilder();
       char[] c = new char[BUFFER_SIZE];
       int l;
       while ((l = reader.read(c)) != -1) {
           sb.append(c, 0, l);
       }
       return sb.toString();
   }

where sb.append and sb.toString use method Arrays.copyOf(value, newCapacity) 
and the method Arrays.copyOf is called a lot of time and each time it allocates memory by
 `char[] copy = new char[newLength];`
and I think this is a problem, too many times Arrays.copyOf is called
Maybe we should try diffrent jax-rs implementation

**Comment by scottdraves** [comment]
OK error reporting has been improved.  Will look into reducing the memory used later.
