### ISSUE TITLE
object with bad toString method can crash backend

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4783]
the following groovy code:

```
class Qux {
  public String toString() {
    return this.failmenow()
  }
}
new Qux()
```

crashes the server with the folowing stack trace

```
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>[ObservableUpdater-4] ERROR com.twosigma.beaker.jvm.serialization.BasicObjectSerializer - exception in serialization
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>org.codehaus.jackson.map.JsonMappingException: No signature of method: Qux.failmenow() is applicable for argument types: ()\
 values: []
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:625)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:256)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ObjectMapper.writeValue(ObjectMapper.java:1613)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.impl.JsonGeneratorBase.writeObject(JsonGeneratorBase.java:314)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at com.twosigma.beaker.jvm.serialization.BasicObjectSerializer.writeObject(BasicObjectSerializer.java:202)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at com.twosigma.beaker.jvm.serialization.PlotObjectSerializer.writeObject(PlotObjectSerializer.java:45)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at com.twosigma.beaker.jvm.object.SimpleEvaluationObject$Serializer.serialize(SimpleEvaluationObject.java:228)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at com.twosigma.beaker.jvm.object.SimpleEvaluationObject$Serializer.serialize(SimpleEvaluationObject.java:190)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ser.std.MapSerializer.serializeFields(MapSerializer.java:262)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:186)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:23)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:610)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:256)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ObjectMapper._configAndWriteValue(ObjectMapper.java:2575)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ObjectMapper.writeValueAsString(ObjectMapper.java:2097)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.cometd.common.JacksonJSONContext.generate(JacksonJSONContext.java:85)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.cometd.server.BayeuxServerImpl.freeze(BayeuxServerImpl.java:863)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.cometd.server.ServerSessionImpl.doDeliver(ServerSessionImpl.java:261)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.cometd.server.ServerSessionImpl.deliver(ServerSessionImpl.java:232)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.cometd.server.ServerSessionImpl.deliver(ServerSessionImpl.java:241)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at com.twosigma.beaker.jvm.updater.Updater.deliverUpdate(Updater.java:37)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at com.twosigma.beaker.jvm.updater.ObservableUpdaterFactory$ObservableUpdater.run(ObservableUpdaterFactory.java:77)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at java.lang.Thread.run(Thread.java:745)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>Caused by: groovy.lang.MissingMethodException: No signature of method: Qux.failmenow() is applicable for argument types: ()\
 values: []
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:56)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:78)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:155)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at Qux.toString(script14752591070871110785707.groovy:3)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at com.twosigma.beaker.jvm.object.EvaluationResult$Serializer.serialize(EvaluationResult.java:60)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at com.twosigma.beaker.jvm.object.EvaluationResult$Serializer.serialize(EvaluationResult.java:41)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   at org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:610)
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - Groovy-stderr>   ... 28 more

```

**Comment by scottdraves** [comment]
perhaps the error should be caught here:
https://github.com/twosigma/beaker-notebook/blob/master/plugin/jvm/src/main/java/com/twosigma/beaker/jvm/updater/Updater.java#L37
and so if the update fails, then an error update should be delivered instead.
