### ISSUE TITLE
crash during startup if missing backend

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4845]
we can't call the backends to initialize the nginx config, since they might not exist.

should just assume python2 rules, and not touch the backend until it is started.

```
Exception in thread "main" java.io.FileNotFoundException: /Users/davidepasetto/.beaker/v1/nginx5973035524365097510/profile_beaker_backend_IRuby/ipython_notebook_config.py (No such file or directory)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at java.io.PrintWriter.<init>(PrintWriter.java:263)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.writePrivateFile(PluginServiceLocatorRest.java:636)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.generateIPythonConfig(PluginServiceLocatorRest.java:683)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.createPluginConfig(PluginServiceLocatorRest.java:551)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.createPluginConfigs(PluginServiceLocatorRest.java:336)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.startReverseProxy(PluginServiceLocatorRest.java:319)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.start(PluginServiceLocatorRest.java:315)
    at com.twosigma.beaker.core.Main.main(Main.java:228)
[Thread-3] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - shutting down beaker
Exception in thread "Thread-3" java.lang.NullPointerException
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.shutdown(PluginServiceLocatorRest.java:345)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.access$100(PluginServiceLocatorRest.java:70)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest$1.run(PluginServiceLocatorRest.java:265)
```

**Comment by scottdraves** [comment]
i deleted my ~/anaconda directory and got this: 

```
:dev:run[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - ipython-version-stderr>Traceback (most recent call last):
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - ipython-version-stderr>  File "/Users/spot/beaker-notebook/core/config/plugins/eval/ipythonPlugins/ipyt\
hon/ipythonPlugin", line 25, in <module>
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - ipython-version-stderr>    os.execlp("ipython", "ipython", "--version")
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - ipython-version-stderr>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/o\
s.py", line 329, in execlp
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - ipython-version-stderr>    execvp(file, args)
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - ipython-version-stderr>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/o\
s.py", line 346, in execvp
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - ipython-version-stderr>    _execvpe(file, args)
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - ipython-version-stderr>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/o\
s.py", line 382, in _execvpe
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - ipython-version-stderr>    func(fullname, *argrest)
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - ipython-version-stderr>OSError: [Errno 2] No such file or directory
Exception in thread "main" java.lang.NullPointerException
        at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.createPluginConfigs(PluginServiceLocatorRest.java:334)
        at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.startReverseProxy(PluginServiceLocatorRest.java:319)
        at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.start(PluginServiceLocatorRest.java:315)
        at com.twosigma.beaker.core.Main.main(Main.java:228)
[Thread-3] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - shutting down beaker
Exception in thread "Thread-3" java.lang.NullPointerException
        at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.shutdown(PluginServiceLocatorRest.java:345)
        at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.access$100(PluginServiceLocatorRest.java:70)
        at com.twosigma.beaker.core.rest.PluginServiceLocatorRest$1.run(PluginServiceLocatorRest.java:265)
 FAILED
:run FAILED
```

**Comment by scottdraves** [comment]
> we will have to settle on assuming ipython2, and if a request comes in for 1, then allocate it dynamically as master does now.

from https://github.com/twosigma/beaker-notebook/pull/4791#issuecomment-251512756
