### ISSUE TITLE
async calls

### ISSUE THREAD

**Issue by brandonmp** [twosigma/beakerx#4949]
I'm using beaker notebook in the Beaker Lab environment, and it seems I'm unable to execute async calls in javascript. Is this a known limitation, or is there a setting I can adjust somewhere?

e.g.:
```
// fetch headers 
fetch('http://www.google.com', 
      {method: 'HEAD'})
  .then((res) => beaker.print(res))
  .catch(err =>beaker.print(err))
```

results in a perpetual 'loading' spinner:

![image](https://cloud.githubusercontent.com/assets/14139991/20438379/6df2e242-ad85-11e6-8ba9-c83b4b587591.png)

the `cancel` button doesn't work, have to reload the page to break the process.

ETA: 
- same issue if `console.log` is used instead of `beaker.print`
- returning just the `res` or `err` results in a small blank table
- `res` in this instance is of type `ObservableStream`, i believe, so i'm not sure if that complicates anything

Looking @ console reveals an infinite loop of this error/stacktrace:

```
TypeError: Cannot read property 'innertype' of null
    at Object.$scope.model.getOutputSummary (http://127.0.0.1:8805/4c05020/beaker/app/dist/beakerApp.js:16151:65)
    at Scope.$scope.getOutputSummary (http://127.0.0.1:8805/4c05020/beaker/app/dist/beakerApp.js:12657:89)
    at fn (eval at <anonymous> (http://127.0.0.1:8805/4c05020/beaker/app/dist/beakerVendor.js:63924:15), <anonymous>:4:239)
    at expressionInputWatch (http://127.0.0.1:8805/4c05020/beaker/app/dist/beakerVendor.js:65017:31)
    at Scope.$digest (http://127.0.0.1:8805/4c05020/beaker/app/dist/beakerVendor.js:66556:34)
    at computeElapsed (http://127.0.0.1:8805/4c05020/beaker/app/dist/beakerOutputDisplay.js:3550:19)
    at http://127.0.0.1:8805/4c05020/beaker/app/dist/beakerOutputDisplay.js:3554:11
    at callback (http://127.0.0.1:8805/4c05020/beaker/app/dist/beakerVendor.js:61859:11)
    at completeOutstandingRequest (http://127.0.0.1:8805/4c05020/beaker/app/dist/beakerVendor.js:55361:10)
    at http://127.0.0.1:8805/4c05020/beaker/app/dist/beakerVendor.js:55637:7(anonymous function) @ beakerVendor.js:63042(anonymous function) @ beakerVendor.js:59717Scope.$digest @ beakerVendor.js:66583computeElapsed @ beakerOutputDisplay.js:3550(anonymous function) @ beakerOutputDisplay.js:3554callback @ beakerVendor.js:61859completeOutstandingRequest @ beakerVendor.js:55361(anonymous function) @ beakerVendor.js:55637
```

**Comment by scottdraves** [comment]
hi, thanks for reporting this issue.

it does handle async, an example is in the JavaScript tutorial: https://lab.beakernotebook.com/publications/87a444cc-fb85-11e5-9870-6f83c54cb849?fullscreen=true

but it's set up to recognize a deferred value.

https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/plugin/evaluator/javaScript.js#L277

I have to look at exactly what fetch returns to see why it's not working, will do that later.

**Comment by scottdraves** [comment]
it returns a promise, instead of a deferred value.  so this code works:

```
var d = beaker.newDeferred();
fetch('http://www.google.com', 
      {method: 'HEAD'})
  .then((res) => d.resolve(res))
  .catch((err) =>d.reject(err+""));
d
```

so i think there are two bugs.  one is the promise crashes it, it should just appear as a promise.  i don't know if promises can be made to work correctly like deferred values, but at least it should not crash.  2nd, the `+""` in the working code should not be needed.
