### ISSUE TITLE
Docker NodeJS (111: Connection refused)

### ISSUE THREAD

**Issue by disarticulate** [twosigma/beakerx#5027]
```
docker run -p 8800:8800 beakernotebook/beaker
```
Load NodeJS cell

get:
```
[main] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - starting nginx instance (/home/beaker/src/core/nginx)
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO com.twosigma.beaker.core.module.elfinder.impl.DefaultFsService - mounted A: LocalFsVolume [/home/beaker]
[main] INFO com.twosigma.beaker.core.module.elfinder.impl.DefaultFsService - mounted B: LocalFsVolume [/]
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to https://274288fc624b:8800/
Submit this password: 7oppjkk44fmrj8g0dl6q

[qtp406765571-26] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - Running
[qtp406765571-26] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - 0: /home/beaker/src/core/config/plugins/eval/node/nodePlugin
[qtp406765571-26] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - 1: 8817
[qtp406765571-26] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - looking on stdout found:Server Starting
[qtp406765571-26] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - Acknowledge Node plugin started due to Server Starting
[qtp406765571-26] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - Done starting Node
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>2017/02/15 15:07:59 [error] 48#48: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: 274288fc624b, request: "GET /6dac09a/node.340154652993/pulse HTTP/1.1", upstream: "http://127.0.0.1:8817/pulse", host: "localhost:8800", referrer: "https://localhost:8800/beaker/"
```
In the browser :
```
Error: evalmachine.:1
process
^
process is not defined
evalmachine.:1
process
^
ReferenceError: process is not defined
    at evalmachine.:1:1
    at Object.exports.runInContext (vm.js:64:17)
    at processCode (/home/beaker/src/core/config/plugins/eval/node/app/app.js:134:17)
    at execute (/home/beaker/src/core/config/plugins/eval/node/app/app.js:79:26)
    at response.statusCode (/home/beaker/src/core/config/plugins/eval/node/app/app.js:113:5)
    at trycatchit (/home/beaker/src/core/config/plugins/eval/node/app/node_modules/trycatch/lib/trycatch.js:184:13)
    at runInDomain (/home/beaker/src/core/config/plugins/eval/node/app/node_modules/trycatch/lib/trycatch.js:166:13)
    at trycatch (/home/beaker/src/core/config/plugins/eval/node/app/node_modules/trycatch/lib/trycatch.js:60:3)
    at /home/beaker/src/core/config/plugins/eval/node/app/app.js:112:3
    at Layer.handle [as handle_request] (/home/beaker/src/core/config/plugins/eval/node/app/node_modules/express/lib/router/layer.js:95:5)

```
Doesn't look like the node service is starting.

I saw node was recently upgrades from 0.x to 6.x ?

I expect process to be available. Maybe I'm confused.

**Comment by scottdraves** [comment]
Hi, thanks for the report.  Sounds like the container did not get the node version update.
