### ISSUE TITLE
font is set too late

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5537]
the notebook loads and then the fonts flash.
can it be immediately set?

**Comment by jszalek** [comment]
As far as I know it is impossible if we want to keep this code in our extensions.
Jupyter loads extensions with small delay.

**Comment by scottdraves** [comment]
indeed there is no way to do it from extension.js but there are other ways.

we could have our install.py write into ~/.jupyter/custom/custom.css, though this would unfortunately not be specific to the conda env and also be difficult to deal with user's who have configured it themselves already.

also, even if we wrote the css there, the fonts themselves would not be available until the extension loads.  could they also be written to the custom directory?

**Comment by scottdraves** [comment]
look into how these work:
https://github.com/transcranial/jupyter-themer
https://github.com/dunovank/jupyter-themes

**Comment by scottdraves** [comment]
jupyter-themes install is giving me
```
Installing collected packages: scipy, cycler, pyparsing, matplotlib, seaborn, setuptools, ipython, ply, lesscpy, jupyterthemes
  Found existing installation: setuptools 27.2.0
    Uninstalling setuptools-27.2.0:
      Successfully uninstalled setuptools-27.2.0
  Found existing installation: ipython 6.1.0
    DEPRECATION: Uninstalling a distutils installed project (ipython) has been deprecated and will be removed in a future version. This is due to the fact that unin\
stalling a distutils project will only partially uninstall the project.
    Uninstalling ipython-6.1.0:
      Successfully uninstalled ipython-6.1.0
Successfully installed cycler-0.10.0 ipython-5.4.1 jupyterthemes-0.16.4 lesscpy-0.12.0 matplotlib-2.0.2 ply-3.10 pyparsing-2.2.0 scipy-0.19.1 seaborn-0.7.1 setuptoo\
ls-36.0.1
Traceback (most recent call last):
  File "/Users/spot/anaconda/envs/testx2/bin/pip", line 6, in <module>
    sys.exit(pip.main())
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/__init__.py", line 249, in main
    return command.main(cmd_args)
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Users/spot/anaconda/envs/testx2/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg'
```

**Comment by scottdraves** [comment]
jupyter-themer does
```
$ cat $CONDA_PREFIX/lib/python3.5/site-packages/notebook/static/custom/custom.css
.CodeMirror { font-family: "Ubuntu Mono"; }
.output * { font-family: "Ubuntu Mono" !important;}
```
and it loads without a flash, and it gets replaced by ~/.jupyter/custom/custom.css.
so we should be able to do that.

Kuba can you please prepare a custom.css for us?  we can arrange to have it installed.
not sure about the font assets themselves, maybe in the same directory?
this custom.css can be generated by webpack (best), or it can be a plain file used as it is in the src.

**Comment by scottdraves** [comment]
yes i confirmed all files in the custom directory get served at the same location.

**Comment by jszalek** [comment]
```
.CodeMirror pre,
.rendered_html pre, 
.rendered_html code,
.output_area pre {
  font-family: "Roboto Mono", monospace, sans-serif;
}
.rendered_html, 
.cm-header-1, 
.cm-header-2, 
.cm-header-3, 
.cm-header-4, 
.cm-header-5, 
.cm-header-6 {
  font-family: "Lato", Helvetica, sans-serif;
}
```

**Comment by jszalek** [comment]
@scottdraves I added 'custom' directory with fonts and css to repository.
