### ISSUE TITLE
MessageCreator.createErrorResult throws exception when error is not a string

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#5579]
`createErrorResult` assumes that `getPayload` will always be a string, but sometimes it may be an exception.  Here is a sample stack trace:

```
java.lang.ClassCastException: java.lang.IllegalStateException cannot be cast to java.lang.String
	at com.twosigma.beakerx.kernel.msg.MessageCreator.createErrorResult(MessageCreator.java:213)
	at com.twosigma.beakerx.kernel.msg.MessageCreator.createResultForSupportedStatus(MessageCreator.java:165)
	at com.twosigma.beakerx.kernel.msg.MessageCreator.createMessage(MessageCreator.java:150)
	at com.twosigma.beakerx.kernel.threads.ExecutionResultSender.update(ExecutionResultSender.java:49)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at com.twosigma.beakerx.jvm.object.SimpleEvaluationObject.error(SimpleEvaluationObject.java:84)
	at com.twosigma.beakerx.scala.evaluator.ScalaEvaluatorGlue.evaluate(ScalaEvaluatorGlue.scala:110)
	at com.twosigma.beakerx.scala.evaluator.ScalaEvaluator$workerThread$MyRunnable.run(ScalaEvaluator.java:347)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
(This was generated by entering `new Points` into a Scala notebook.  The underlying complaint in the exception is "java.lang.IllegalStateException: Please provide X coordinate" coming from the serializer.)

The obvious fix is to change the string cast in `createErrorResult` to `.toString()`.

**Comment by scottdraves** [comment]
confirmed, thanks for the report.

**Comment by scottdraves** [comment]
and the fix! 👍
