### ISSUE TITLE
Install failed on Windows... again

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#5650]
Just tried a clean install on windows with python build system. I used elevated command prompt instead of powershell due to #5616. Got this:
```
Installing collected packages: beakerx
  Running setup.py develop for beakerx
    Running command C:\Anaconda\envs\beakerx\python.exe -c "import setuptools, tokenize;__file__='D:\\Work\\beakerx\\beakerx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    running develop
    running js
    running nb_conda_kernels
    Enabling BeakerX server config...
    Enabled BeakerX server config
    running nb_custom_css
    C:\Anaconda\envs\beakerx\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\dist.py:331: UserWarning: Normalizing '0.1.0.dev' to '0.1.0.dev0'
    error: [Errno 2] No such file or directory: 'C:\\Anaconda\\envs\\beakerx\\lib\\python3.5\\site-packages\\notebook\\static\\custom\\custom.css'
Cleaning up...
Command "C:\Anaconda\envs\beakerx\python.exe -c "import setuptools, tokenize;__file__='D:\\Work\\beakerx\\beakerx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in D:\Work\beakerx\beakerx\
Exception information:
Traceback (most recent call last):
  File "C:\Anaconda\envs\beakerx\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Anaconda\envs\beakerx\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Anaconda\envs\beakerx\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Anaconda\envs\beakerx\lib\site-packages\pip\req\req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
  File "C:\Anaconda\envs\beakerx\lib\site-packages\pip\req\req_install.py", line 1007, in install_editable
    show_stdout=False)
  File "C:\Anaconda\envs\beakerx\lib\site-packages\pip\utils\__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "C:\Anaconda\envs\beakerx\python.exe -c "import setuptools, tokenize;__file__='D:\\Work\\beakerx\\beakerx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in D:\Work\beakerx\beakerx\
```
Just to be sure:
```
(beakerx) darksnake@DAETRON D:\Work\beakerx
$ conda info --env
# conda environments:
#
beakerx               *  C:\Anaconda\envs\beakerx
root                     C:\Anaconda
```

**Comment by scottdraves** [comment]
thank you. we are aware of this and it should be corrected soon.
