### ISSUE TITLE
bad wildcard should not crash

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5741]
just report a nice error to the user, do not crash:

```
Exception in thread "Thread-0" java.lang.IllegalStateException: Wildcard can only appear at end of classpath: demoResources/*.jar
        at com.twosigma.beakerx.kernel.commands.MagicCommand.validateWildcardPath(MagicCommand.java:220)
        at com.twosigma.beakerx.kernel.commands.MagicCommand.addJars(MagicCommand.java:202)
```

**Comment by michalgce** [comment]
May we close it? @scottdraves
