### ISSUE TITLE
Error  for developer Install

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#5862]
run `pip install -e . --verbose`
get error 
```
(beakerx) d:\PR\TWOSIGMA\beakerx\beakerx>pip install -e . --verbose
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Obtaining file:///D:/PR/TWOSIGMA/beakerx/beakerx
  Running setup.py (path:D:\PR\TWOSIGMA\beakerx\beakerx\setup.py) egg_info for p
ackage from file:///D:/PR/TWOSIGMA/beakerx/beakerx
    Running command python setup.py egg_info
    running egg_info
    writing requirements to beakerx.egg-info\requires.txt
    writing entry points to beakerx.egg-info\entry_points.txt
    writing top-level names to beakerx.egg-info\top_level.txt
    writing beakerx.egg-info\PKG-INFO
    writing dependency_links to beakerx.egg-info\dependency_links.txt
    C:\Aconda3\envs\beakerx\lib\site-packages\setuptools-27.2.0-py3.5.egg\setupt
ools\dist.py:331: UserWarning: Normalizing '0.2.2.dev' to '0.2.2.dev0'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'beakerx.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'CONTRIBUTING.md'
    warning: no files found matching 'README.md'
    writing manifest file 'beakerx.egg-info\SOURCES.txt'
  Source in d:\pr\twosigma\beakerx\beakerx has version 0.2.2.dev0, which satisfi
es requirement beakerx==0.2.2.dev0 from file:///D:/PR/TWOSIGMA/beakerx/beakerx
Requirement already satisfied: notebook>=4.3.1 in c:\aconda3\envs\beakerx\lib\si
te-packages (from beakerx==0.2.2.dev0)
Requirement already satisfied: ipywidgets<=6.0.0,>=5.1.5 in c:\aconda3\envs\beak
erx\lib\site-packages (from beakerx==0.2.2.dev0)
Requirement already satisfied: pandas in c:\aconda3\envs\beakerx\lib\site-packag
es (from beakerx==0.2.2.dev0)
Requirement already satisfied: python-dateutil>=2 in c:\aconda3\envs\beakerx\lib
\site-packages (from pandas->beakerx==0.2.2.dev0)
Requirement already satisfied: pytz>=2011k in c:\aconda3\envs\beakerx\lib\site-p
ackages (from pandas->beakerx==0.2.2.dev0)
Requirement already satisfied: numpy>=1.7.0 in c:\aconda3\envs\beakerx\lib\site-
packages (from pandas->beakerx==0.2.2.dev0)
Requirement already satisfied: six>=1.5 in c:\aconda3\envs\beakerx\lib\site-pack
ages (from python-dateutil>=2->pandas->beakerx==0.2.2.dev0)
Installing collected packages: beakerx
  Running setup.py develop for beakerx
    Running command C:\Aconda3\envs\beakerx\python.exe -c "import setuptools, to
kenize;__file__='D:\\PR\\TWOSIGMA\\beakerx\\beakerx\\setup.py';f=getattr(tokeniz
e, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(co
mpile(code, __file__, 'exec'))" develop --no-deps
    running develop
    running js
    C:\Aconda3\envs\beakerx\lib\site-packages\setuptools-27.2.0-py3.5.egg\setupt
ools\dist.py:331: UserWarning: Normalizing '0.2.2.dev' to '0.2.2.dev0'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\PR\TWOSIGMA\beakerx\beakerx\setup.py", line 115, in <module>
        setup(**setup_args)
      File "C:\Aconda3\envs\beakerx\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Aconda3\envs\beakerx\lib\distutils\dist.py", line 955, in run_com
mands
        self.run_command(cmd)
      File "C:\Aconda3\envs\beakerx\lib\distutils\dist.py", line 974, in run_com
mand
        cmd_obj.run()
      File "D:\PR\TWOSIGMA\beakerx\beakerx\setupbase.py", line 546, in run
        [self.run_command(cmd) for cmd in cmds]
      File "D:\PR\TWOSIGMA\beakerx\beakerx\setupbase.py", line 546, in <listcomp
>
        [self.run_command(cmd) for cmd in cmds]
      File "C:\Aconda3\envs\beakerx\lib\distutils\cmd.py", line 313, in run_comm
and
        self.distribution.run_command(command)
      File "C:\Aconda3\envs\beakerx\lib\distutils\dist.py", line 974, in run_com
mand
        cmd_obj.run()
      File "D:\PR\TWOSIGMA\beakerx\beakerx\setupbase.py", line 289, in run
        if not which("yarn"):
      File "D:\PR\TWOSIGMA\beakerx\beakerx\setupbase.py", line 500, in which
        os.path.insert(0, os.curdir)
    AttributeError: module 'ntpath' has no attribute 'insert'
Cleaning up...
Command "C:\Aconda3\envs\beakerx\python.exe -c "import setuptools, tokenize;__fi
le__='D:\\PR\\TWOSIGMA\\beakerx\\beakerx\\setup.py';f=getattr(tokenize, 'open',
open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code,
 __file__, 'exec'))" develop --no-deps" failed with error code 1 in D:\PR\TWOSIG
MA\beakerx\beakerx\
Exception information:
Traceback (most recent call last):
  File "C:\Aconda3\envs\beakerx\lib\site-packages\pip\basecommand.py", line 215,
 in main
    status = self.run(options, args)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\pip\commands\install.py", line
 342, in run
    prefix=options.prefix_path,
  File "C:\Aconda3\envs\beakerx\lib\site-packages\pip\req\req_set.py", line 784,
 in install
    **kwargs
  File "C:\Aconda3\envs\beakerx\lib\site-packages\pip\req\req_install.py", line
845, in install
    install_options, global_options, prefix=prefix)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\pip\req\req_install.py", line
1007, in install_editable
    show_stdout=False)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\pip\utils\__init__.py", line 7
07, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "C:\Aconda3\envs\beakerx\python.exe -c
 "import setuptools, tokenize;__file__='D:\\PR\\TWOSIGMA\\beakerx\\beakerx\\setu
p.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed
 with error code 1 in D:\PR\TWOSIGMA\beakerx\beakerx\
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
Current age based on date: 13112
Freshness lifetime from max-age: 600
The cached response is "stale" with no etag, purging
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 72983
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching b/c date exists and max-age > 0
```

**Comment by EfimovVladimir** [comment]
fixed PR  #5863
