### ISSUE TITLE
Problem with console mode and magic commands

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#6210]
A bunch of console issues were fixed in #5195.  One that slipped by or got introduced more recently involves magic commands.  It looks like any magic command will cause the console to error out.

Here's an example:

```
(beakerx) Joes-MacBook-Air:~ joe$ jupyter console --kernel=groovy
Jupyter console 5.1.0

BeakerX master
Groovy 2.4.3
hash 492c381
build time 2017-10-25 10:04 PDT


In [1]: 3 + 4
Out[1]: 7

In [2]: %lsmagic
Available magic commands:
%%javascript 
%%html 
%%bash 
%lsmagic 
%classpath add jar <jar path>
%classpath add mvn <group name version>
%classpath remove <jar path>
%classpath 
%import static <classpath>
%import <classpath>
%unimport <classpath>
%time 
%%time 
%timeit 
%%timeit Traceback (most recent call last):
  File "/Users/joe/miniconda2/envs/beakerx/bin/jupyter-console", line 5, in <module>
    app.main()
  File "/Users/joe/miniconda2/envs/beakerx/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/joe/miniconda2/envs/beakerx/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/joe/miniconda2/envs/beakerx/lib/python3.5/site-packages/jupyter_console/app.py", line 155, in start
    self.shell.mainloop()
  File "/Users/joe/miniconda2/envs/beakerx/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 490, in mainloop
    self.interact()
  File "/Users/joe/miniconda2/envs/beakerx/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 482, in interact
    self.run_cell(code, store_history=True)
  File "/Users/joe/miniconda2/envs/beakerx/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 546, in run_cell
    self.handle_execute_reply(msg_id, timeout=0.05)
  File "/Users/joe/miniconda2/envs/beakerx/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 564, in handle_execute_reply
    status = content['status']
KeyError: 'status'
(beakerx) Joes-MacBook-Air:~ joe$ 
```

The problem doesn't seem to be specific to the magic command (I found it with `%classpath`) or the kernel.

**Comment by scottdraves** [comment]
Thank you so much for this.
We will have to add console to our e2e tests.
I never use it myself so basic problems like this can sneak in.

**Comment by scottdraves** [comment]
vladimir is still seeing this, but i am unable to check now, reopening until it's resolved.

**Comment by EfimovVladimir** [comment]
After I create new environment and install beakerx, then jupyter console works without that error.
