### ISSUE TITLE
Fix continuous build GitHub integration

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6301]
Jenksin github-api-plugin 1.90 was released on Nov 1 which fixes this issue. Would you be able to upgrade to the latest version of the plugin?

I like Travis quite a bit better than Jenkins and would recommend taking a look at switching to it. It's quite easy to setup and free for open source projects.

The errors appearing in the Jenkins logs:
>Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.HttpException: Server returned HTTP response code: 201, message: 'Created' for URL: https://api.github.com/repos/twosigma/beakerx/statuses/63164ae9f3129ebe6f6ec708ce60d06e06312470
	at org.kohsuke.github.Requester.parse(Requester.java:540)
	at org.kohsuke.github.Requester._to(Requester.java:251)
	at org.kohsuke.github.Requester.to(Requester.java:213)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:932)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:273)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:232)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:194)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:17)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:211)
	at hudson.model.Run.execute(Run.java:1769)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Caused by: java.io.IOException: Failed to deserialize {"url":"https://api.github.com/repos/twosigma/beakerx/statuses/63164ae9f3129ebe6f6ec708ce60d06e06312470","id":4310598754,"state":"success","description":"Build finished. ","target_url":"http://ec2-54-175-192-115.compute-1.amazonaws.com:8080/job/BeakerX%20PR/3580/","context":"default","created_at":"2017-11-12T20:01:00Z","updated_at":"2017-11-12T20:01:00Z","creator":{"login":"ildipo","id":8972575,"avatar_url":"https://avatars3.githubusercontent.com/u/8972575?v=4","gravatar_id":"","url":"https://api.github.com/users/ildipo","html_url":"https://github.com/ildipo","followers_url":"https://api.github.com/users/ildipo/followers","following_url":"https://api.github.com/users/ildipo/following{/other_user}","gists_url":"https://api.github.com/users/ildipo/gists{/gist_id}","starred_url":"https://api.github.com/users/ildipo/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ildipo/subscriptions","organizations_url":"https://api.github.com/users/ildipo/orgs","repos_url":"https://api.github.com/users/ildipo/repos","events_url":"https://api.github.com/users/ildipo/events{/privacy}","received_events_url":"https://api.github.com/users/ildipo/received_events","type":"User","site_admin":false}}
	at org.kohsuke.github.Requester.parse(Requester.java:530)
	... 13 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4310598754) out of range of int
 at [Source: java.io.StringReader@29f28f8b; line: 1, column: 121] (through reference chain: org.kohsuke.github.GHCommitStatus["id"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1311)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
	at org.kohsuke.github.Requester.parse(Requester.java:528)
	... 13 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (4310598754) out of range of int
 at [Source: java.io.StringReader@29f28f8b; line: 1, column: 121]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:847)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:643)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:306)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:319)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:301)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	... 17 more

**Comment by scottdraves** [comment]
sorry i don't know what issue you mean?

**Comment by benmccann** [comment]
Go to a pull request and look under the "checks". You can find a link to the Jenkins build that ran the tests for that PR. Then click "Console Output" and you'll see a page like: http://ec2-54-175-192-115.compute-1.amazonaws.com:8080/job/BeakerX%20PR/3634/console

There's lots of errors on that page because Jenkins has been setup to run the tests of each PR and is using an outdated version of the github-api-plugin Jenkins plugin.
