### ISSUE TITLE
CircleCI test failing: doesn't seem to recognize use of python 3.5

### ISSUE THREAD

**Issue by jmsdnns** [twosigma/beakerx#6528]
Two tests on CircleCI are failing. They seem to think the python version we're running fails this check: `python_version >= 3.4 or python_version == 2.7`

The full error log:

```
+ /feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/bin/beakerx-install
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/bin/beakerx-install", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytest; python_version >= "3.4" or python_version == "2.7" and extra == "test"' distribution was not found and is required by jupyter-client

ERROR:conda.core.link:An error occurred while installing package 'local::beakerx-0.10.0-py35_0'.
LinkError: post-link script failed for package local::beakerx-0.10.0-py35_0
running your command again with `-v` will provide additional information
location of failed script: /feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/bin/.beakerx-post-link.sh
==> script messages <==
+ /feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/bin/beakerx-install
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/bin/beakerx-install", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/feedstock_root/build_artefacts/beakerx_1513631553610/_t_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytest; python_version >= "3.4" or python_version == "2.7" and extra == "test"' distribution was not found and is required by jupyter-client
```

**Comment by scottdraves** [comment]
only close to relevant changes i could find are
https://github.com/twosigma/beakerx/commit/c0d7b330d0e20911a82d9da30244f360830e91d7
https://github.com/twosigma/beakerx/commit/9ef1740a2473e0aed81b1fd537806194dd458cdc

**Comment by scottdraves** [comment]
same as https://github.com/twosigma/beakerx/issues/6579
