### ISSUE TITLE
pexpect console test fails

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6561]
```
(beakerx) Scotts-MacBook-Pro:test spot$ python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import test_console
>>> result = test_console.test_lsmagic()
Traceback (most recent call last):
  File "/Users/spot/anaconda/envs/beakerx/lib/python3.6/site-packages/pexpect/expect.py", line 98, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/Users/spot/anaconda/envs/beakerx/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 469, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/Users/spot/anaconda/envs/beakerx/lib/python3.6/site-packages/pexpect/spawnbase.py", line 162, in read_nonblocking
    raise EOF('End Of File (EOF). Empty string style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/spot/src/beakerx/test/test_console.py", line 47, in test_lsmagic
    p, pexpect, t = start_console()
  File "/Users/spot/src/beakerx/test/test_console.py", line 30, in start_console
    p.expect(r'In \[\d+\]', timeout=t)
  File "/Users/spot/anaconda/envs/beakerx/lib/python3.6/site-packages/pexpect/spawnbase.py", line 327, in expect
    timeout, searchwindowsize, async_)
  File "/Users/spot/anaconda/envs/beakerx/lib/python3.6/site-packages/pexpect/spawnbase.py", line 355, in expect_list
    return exp.expect_loop(timeout)
  File "/Users/spot/anaconda/envs/beakerx/lib/python3.6/site-packages/pexpect/expect.py", line 104, in expect_loop
    return self.eof(e)
  File "/Users/spot/anaconda/envs/beakerx/lib/python3.6/site-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
<pexpect.pty_spawn.spawn object at 0x10d73fe48>
command: /Users/spot/anaconda/envs/beakerx/bin/jupyter
args: ['/Users/spot/anaconda/envs/beakerx/bin/jupyter', 'console', '--kernel=groovy']
buffer (last 100 chars): b''
before (last 100 chars): b'3, in get_kernel_spec\r\n    raise NoSuchKernel(kernel_name)\r\njupyter_client.kernelspec.NoSuchKernel\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 49115
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("b'In \\[\\d+\\]'")
```

**Comment by scottdraves** [comment]
hm weird in fact if i try to run `jupyter console --kernel=groovy` it does fail but it's claiming python 2.7????
```
$ jupyter console --kernel=groovy
Traceback (most recent call last):
  File "/Users/spot/anaconda/bin/jupyter-console", line 5, in <module>
    app.main()
  File "/Users/spot/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/spot/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/Users/spot/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/spot/anaconda/lib/python2.7/site-packages/jupyter_console/app.py", line 136, in initialize
    self.init_shell()
  File "/Users/spot/anaconda/lib/python2.7/site-packages/jupyter_console/app.py", line 103, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/Users/spot/anaconda/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 329, in initialize
    self.init_kernel_manager()
  File "/Users/spot/anaconda/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 283, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/Users/spot/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 231, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/Users/spot/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 171, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/Users/spot/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/Users/spot/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 143, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel
```

**Comment by scottdraves** [comment]
indeed, this was because i hadn't done a "conda install jupyter_console" in my env.
the tests just need to document this dependency.

**Comment by scottdraves** [comment]
```
>>> import test_console
>>> result = test_console.test_lsmagic()
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
test_lsmagic return code= 0
```
i would guess `pgrep -f jupyter` had an empty result so we just tried to run `kill -9` without any process...
