### ISSUE TITLE
uninstall leaves server extension

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6760]
to reproduce:
1) install beakerx conda package into a fresh env.
2) "conda remove beakerx"
3) "jupyter notebook"

result:
```
$ jupyter notebook
[W 19:02:52.952 NotebookApp] Error loading server extension beakerx
    Traceback (most recent call last):
      File "/Users/spot/anaconda/envs/beakerx/lib/python3.6/site-packages/notebook/notebookapp.py", line 1451, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/spot/anaconda/envs/beakerx/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'beakerx'
```

because:
```
$ cat /Users/spot/anaconda/envs/beakerx/etc/jupyter/jupyter_notebook_config.json
{
  "NotebookApp": {
    "nbserver_extensions": {
      "beakerx": true
    }
  },
```

**Comment by geyang** [comment]
How to fix this? thanks.

**Comment by geyang** [comment]
for future travelings:
```
(plan2vec) ➜  zdoom git:(master) ✗ jupyter labextension disable beakerx
(plan2vec) ➜  zdoom git:(master) ✗ jupyter labextension disable beakerx-jupyterlab
(plan2vec) ➜  zdoom git:(master) ✗ jupyter labextension uninstall beakerx-jupyterlab
```
