### ISSUE TITLE
conda build failing on windows

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6793]
eg https://ci.appveyor.com/project/conda-forge/beakerx-feedstock/build/1.0.66/job/irpgnop1b0v2qtw7

```
TEST START: C:\bld\win-64\beakerx-0.12.2-py35_1.tar.bz2
Deleting work directory, C:\bld\beakerx_1517933192435\work\beakerx-0.12.2
The following NEW packages will be INSTALLED:
    attrs:               17.4.0-py_0            conda-forge
    beakerx:             0.12.2-py35_1          local      
    bleach:              2.0.0-py_1             conda-forge
    ca-certificates:     2017.11.5-0            conda-forge
    certifi:             2017.11.5-py35_0       conda-forge
    colorama:            0.3.9-py35_0           conda-forge
    decorator:           4.1.2-py35_0           conda-forge
    entrypoints:         0.2.3-py35_1           conda-forge
    html5lib:            1.0.1-py_0             conda-forge
    icc_rt:              2017.0.4-h97af966_0    defaults   
    icu:                 58.2-vc14_0            conda-forge [vc14]
    intel-openmp:        2018.0.0-hd92c6cd_8    defaults   
    ipykernel:           4.8.0-py35_0           conda-forge
    ipython:             6.2.1-py35_1           conda-forge
    ipython_genutils:    0.2.0-py35_0           conda-forge
    ipywidgets:          7.1.1-py35_0           conda-forge
    jedi:                0.11.1-py35_0          conda-forge
    jinja2:              2.10-py35_0            conda-forge
    jpeg:                9b-vc14_2              conda-forge [vc14]
    jsonschema:          2.6.0-py35_1           conda-forge
    jupyter:             1.0.0-py35_0           conda-forge
    jupyter_client:      5.2.2-py35_0           conda-forge
    jupyter_console:     5.2.0-py35_0           conda-forge
    jupyter_core:        4.4.0-py_0             conda-forge
    libiconv:            1.14-vc14_4            conda-forge [vc14]
    libpng:              1.6.34-vc14_0          conda-forge [vc14]
    libsodium:           1.0.15-vc14_1          conda-forge [vc14]
    libtiff:             4.0.9-vc14_0           conda-forge [vc14]
    libxml2:             2.9.3-vc14_9           conda-forge [vc14]
    markupsafe:          1.0-py35_0             conda-forge
    maven:               3.5.0-0                conda-forge
    mistune:             0.8.3-py_0             conda-forge
    mkl:                 2018.0.1-h2108138_4    defaults   
    nbconvert:           5.3.1-py_1             conda-forge
    nbformat:            4.4.0-py35_0           conda-forge
    notebook:            5.4.0-py35_0           conda-forge
    numpy:               1.14.0-py35h4a99626_1  defaults   
    openjdk:             8.0.144-zulu8.23.0.3_1 conda-forge
    openssl:             1.0.2n-vc14_0          conda-forge [vc14]
    pandas:              0.22.0-py35_0          conda-forge
    pandoc:              2.1.1-0                conda-forge
    pandocfilters:       1.4.1-py35_0           conda-forge
    parso:               0.1.1-py_0             conda-forge
    pickleshare:         0.7.4-py35_0           conda-forge
    pluggy:              0.6.0-py_0             conda-forge
    prompt_toolkit:      1.0.15-py35_0          conda-forge
    py:                  1.5.2-py_0             conda-forge
    pygments:            2.2.0-py35_0           conda-forge
    pyqt:                5.6.0-py35_4           conda-forge
    pytest:              3.4.0-py35_0           conda-forge
    python:              3.5.4-3                conda-forge
    python-dateutil:     2.6.1-py35_0           conda-forge
    pytz:                2017.3-py_2            conda-forge
    pywinpty:            0.5-py35_0             conda-forge
    pyzmq:               16.0.2-py35_3          conda-forge
    qt:                  5.6.2-vc14_1           conda-forge [vc14]
    qtconsole:           4.3.1-py35_0           conda-forge
    send2trash:          1.4.2-py_0             conda-forge
    setuptools:          38.4.0-py35_0          conda-forge
    simplegeneric:       0.8.1-py35_0           conda-forge
    sip:                 4.18-py35_1            conda-forge
    six:                 1.11.0-py35_1          conda-forge
    sqlite:              3.20.1-vc14_2          conda-forge [vc14]
    terminado:           0.8.1-py35_0           conda-forge
    testpath:            0.3.1-py35_0           conda-forge
    tornado:             4.5.3-py35_0           conda-forge
    traitlets:           4.3.2-py35_0           conda-forge
    vc:                  14-0                   conda-forge
    vs2015_runtime:      14.0.25420-0           conda-forge
    wcwidth:             0.1.7-py35_0           conda-forge
    webencodings:        0.5-py35_0             conda-forge
    widgetsnbextension:  3.1.3-py35_0           conda-forge
    win_unicode_console: 0.5-py35_0             conda-forge
    wincertstore:        0.2-py35_0             conda-forge
    winpty:              0.4.3-vc14_2           conda-forge [vc14]
    zeromq:              4.2.3-vc14_2           conda-forge [vc14]
    zlib:                1.2.11-vc14_0          conda-forge [vc14]
Traceback (most recent call last):
  File "C:\bld\beakerx_1517933192435\_t_env\Scripts\beakerx-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\bld\beakerx_1517933192435\_t_env\lib\site-packages\pkg_resources\__init__.py", line 3147, in <module>
    @_call_aside
  File "C:\bld\beakerx_1517933192435\_t_env\lib\site-packages\pkg_resources\__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "C:\bld\beakerx_1517933192435\_t_env\lib\site-packages\pkg_resources\__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\bld\beakerx_1517933192435\_t_env\lib\site-packages\pkg_resources\__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "C:\bld\beakerx_1517933192435\_t_env\lib\site-packages\pkg_resources\__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\bld\beakerx_1517933192435\_t_env\lib\site-packages\pkg_resources\__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ipykernel>=4.5.1' distribution was not found and is required by ipywidgets
ERROR:conda.core.link:An error occurred while installing package 'local::beakerx-0.12.2-py35_1'.

```

**Comment by lmitusinski** [comment]
It seems that new ipykernel version (4.8.0) has been released on conda-forge few days ago.
After some test i figured out that creating conda env and installing ipykernel 4.7.0 solves the problem and beakerx can be installed.

I am not sure, but windows packages from the last ipykernel release are missing "ipykernel-4.8.0.dist-info" and this may be the case.

**Comment by EfimovVladimir** [comment]
:+1:  The problem is on version ipykernel.
When I add `- ipykernel =4.7.0` to meta.yaml to `run` section then conda build will successful.

**Comment by scottdraves** [comment]
https://github.com/conda-forge/beakerx-feedstock/pull/24

**Comment by scottdraves** [comment]
https://github.com/ipython/ipykernel/pull/306
