### ISSUE TITLE
beaker.command can't find nginx on Ubuntu

### ISSUE THREAD

**Issue by jc00ke** [twosigma/beakerx#690]
```
~/Downloads/beaker-notebook-v1.0-0-g5644b78-ubuntu  
$> ./beaker.command
running nginx: nginx -p /home/jesse/.beaker/v1/nginx2503765817366375387 -c /home/jesse/.beaker/v1/nginx2503765817366375387/conf/nginx.conf
Exception in thread "main" java.io.IOException: Cannot run program "nginx": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at java.lang.Runtime.exec(Runtime.java:617)
    at java.lang.Runtime.exec(Runtime.java:450)
    at java.lang.Runtime.exec(Runtime.java:388)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.startReverseProxy(PluginServiceLocatorRest.java:240)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.start(PluginServiceLocatorRest.java:233)
    at com.twosigma.beaker.core.Main.main(Main.java:163)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 6 more

shutting down beaker
Exception in thread "Thread-3" java.lang.NullPointerException
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.shutdown(PluginServiceLocatorRest.java:251)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.access$000(PluginServiceLocatorRest.java:69)
    at com.twosigma.beaker.core.rest.PluginServiceLocatorRest$1.run(PluginServiceLocatorRest.java:193)
```

**Comment by scottdraves** [comment]
try installing the dependencies first.

**Comment by jc00ke** [comment]
With the dependencies installed the command runs successfully. Might I recommend a friendlier error message?

**Comment by scottdraves** [comment]
Yes, please do :)

https://github.com/twosigma/beaker-notebook/issues/221
