### ISSUE TITLE
Shift + Tab doesn't work on windows

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#6951]
![image](https://user-images.githubusercontent.com/17744188/37096580-1be0d99e-222a-11e8-8120-95cc91861eb7.png)

console log
```
[I 14:07:15.788 NotebookApp] Kernel started: d0a39400-56ca-4720-a765-e0b0c615a41
2
[I 14:07:17.988 NotebookApp] Adapting to protocol v5.1 for kernel d0a39400-56ca-
4720-a765-e0b0c615a412
Exception in thread "Thread-1" java.nio.file.InvalidPathException: Illegal char
<:> at index 2: /D:/PR/TWOSIGMA/beakerx/beakerx/beakerx/kernel/base/lib/base.jar

       at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
       at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
       at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
       at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
       at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
       at java.nio.file.Paths.get(Paths.java:84)
       at com.twosigma.beakerx.inspect.Inspect.getInspectFile(Inspect.java:61)
       at com.twosigma.beakerx.inspect.Inspect.doInspect(Inspect.java:48)
       at com.twosigma.beakerx.evaluator.BaseEvaluator.inspect(BaseEvaluator.java:264)
       at com.twosigma.beakerx.evaluator.EvaluatorManager.inspect(EvaluatorManager.java:64)
       at com.twosigma.beakerx.kernel.Kernel.inspect(Kernel.java:195)
       at com.twosigma.beakerx.handler.InspectHandler.handleMsg(InspectHandler.java:55)
       at com.twosigma.beakerx.handler.InspectHandler.lambda$handle$0(InspectHandler.java:47)
       at com.twosigma.beakerx.handler.KernelHandlerWrapper.wrapBusyIdle(KernelHandlerWrapper.java:25)
       at com.twosigma.beakerx.handler.InspectHandler.handle(InspectHandler.java:46)
       at com.twosigma.beakerx.handler.InspectHandler.handle(InspectHandler.java:32)
       at com.twosigma.beakerx.socket.KernelSocketsZMQ.handleShell(KernelSocketsZMQ.java:184)
       at com.twosigma.beakerx.socket.KernelSocketsZMQ.run(KernelSocketsZMQ.java:163)
[I 14:07:39.780 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel d0a39400-56ca-4720-a765-e0b0c615a412 restarted
```

**Comment by EfimovVladimir** [comment]
looks like wrong path there
https://github.com/twosigma/beakerx/blob/3e607e72525c26b241306036fb71e6fb47a50561/kernel/base/src/main/java/com/twosigma/beakerx/inspect/Inspect.java#L62

**Comment by EfimovVladimir** [comment]
I just delete first `/` there
BeakerxWidget.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath().substring(1)
and this fixed error.
but for that should be better solution than my
