### ISSUE TITLE
Home path resolution exception in kotlin

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#7039]
Just tried kotlin with latest beakerx and immediately encountered an exception on start:

```
java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
        at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:97)
        at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.findBinFile(PathManager.java:173)
        at org.jetbrains.kotlin.com.intellij.util.lang.UrlClassLoader.loadPlatformLibrary(UrlClassLoader.java:320)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:48)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:77)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:69)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.setFileStampAndLength(ZipHandler.java:69)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:51)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:47)
        at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:66)
        at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:52)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.getCachedZipFileHandle(ZipHandler.java:112)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.createEntriesMap(ZipHandler.java:87)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:190)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:42)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarFileSystem.java:37)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarFileSystem.java:33)
        at org.jetbrains.kotlin.com.intellij.util.containers.FactoryMap.get(FactoryMap.java:58)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:50)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRoot(KotlinCoreEnvironment.kt:359)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRootToVirtualFile(KotlinCoreEnvironment.kt:340)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.access$contentRootToVirtualFile(KotlinCoreEnvironment.kt:114)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$5.invoke(KotlinCoreEnvironment.kt:223)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$5.invoke(KotlinCoreEnvironment.kt:114)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:70)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:230)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:114)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:409)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplChecker.<init>(GenericReplChecker.kt:63)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:53)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplInterpreter$scriptCompiler$2.invoke(ReplInterpreter.kt:80)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplInterpreter$scriptCompiler$2.invoke(ReplInterpreter.kt:34)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplInterpreter.getScriptCompiler(ReplInterpreter.kt)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplInterpreter.access$getScriptCompiler$p(ReplInterpreter.kt:34)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplInterpreter$scriptEvaluator$2.invoke(ReplInterpreter.kt:83)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplInterpreter$scriptEvaluator$2.invoke(ReplInterpreter.kt:34)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplInterpreter.getScriptEvaluator(ReplInterpreter.kt)
        at org.jetbrains.kotlin.cli.jvm.repl.ReplInterpreter.eval(ReplInterpreter.kt:94)
        at com.twosigma.beakerx.kotlin.evaluator.ReplWithClassLoaderFactory.createReplInterpreter(ReplWithClassLoaderFactory.java:84)
        at com.twosigma.beakerx.kotlin.evaluator.ReplWithClassLoaderFactory.createReplWithKotlinParentClassLoader(ReplWithClassLoaderFactory.java:43)
        at com.twosigma.beakerx.kotlin.evaluator.KotlinEvaluator.createRepl(KotlinEvaluator.java:75)
        at com.twosigma.beakerx.kotlin.evaluator.KotlinEvaluator.<init>(KotlinEvaluator.java:61)
        at com.twosigma.beakerx.kotlin.evaluator.KotlinEvaluator.<init>(KotlinEvaluator.java:55)
        at com.twosigma.beakerx.kotlin.kernel.Kotlin.lambda$main$0(Kotlin.java:70)
        at com.twosigma.beakerx.kernel.KernelRunner.run(KernelRunner.java:24)
        at com.twosigma.beakerx.kotlin.kernel.Kotlin.main(Kotlin.java:68)
```

I do not know what it is about, but it seems that kernel tries to find external kotlin installation and fails. The cell evaluation works fine though. Autocomplete does not work (#6914 ). Maybe it is connected?

**Comment by scottdraves** [comment]
thanks for the report.  latest as in master from github compiled yourself, or our last release 0.14.0 installed with conda?  this is on windows?

**Comment by altavir** [comment]
0.14.0 on Windows. Freshly updated via conda.

**Comment by EfimovVladimir** [comment]
Doesn't reproduced on my Windows.

**Comment by EfimovVladimir** [comment]
```
java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
```
Looks like error related with IntelliJ IIDEA.
What if try run build on command line `gradlew clean build` from kernel directory.

**Comment by altavir** [comment]
I am not able to install developers version right now, but I've reinstalled the beakerx plugin and still have the same exception.

**Comment by EfimovVladimir** [comment]
By the way. This bug reproduced for me too.
