### ISSUE TITLE
beakerx 0.14.0 fails to install when run with `conda env update --json -q -f <conda_env>.yml` with `No module named 'pandas'`

### ISSUE THREAD

**Issue by vishnu2kmohan** [twosigma/beakerx#7095]
Given the following conda environment yml:
```
name: root
channels:
- conda-forge
dependencies:
- awscli
- beakerx
- bokeh
- dask
- distributed
- ipywidgets
- libhdfs3
- jupyterhub
- jupyterlab
- nbconvert
- pandas
- pyarrow
- s3fs
- tensorflow=1.5.0=py36_0
- xgboost
```
beakerx 0.14.0 fails to deploy when run with `conda env update --json -q -f <conda_env>.yml` with:
```
/opt/conda/lib/python3.6/site-packages/conda_env/env.py:68: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.                                                                     
Use 'load(stream, Loader=ruamel_yaml.Loader)' explicitly if that is OK.                                                                              
Alternatively include the following in your code:                                                                                                    

  import warnings                                                                                                                                    
  warnings.simplefilter('ignore', ruamel_yaml.error.UnsafeLoaderWarning)                                                                             

In most other cases you should consider using 'safe_load(stream)'                                                                                    
  data = yaml.load(yamlstr)                                                                                                                          
+ /opt/conda/bin/beakerx install                                                                                                                     
Traceback (most recent call last):                                                                                                                   
  File "/opt/conda/bin/beakerx", line 4, in <module>                                                                                                 
    import beakerx                                                                                                                                   
  File "/opt/conda/lib/python3.6/site-packages/beakerx/__init__.py", line 15, in <module>                                                            
    from .runtime import BeakerX                                                                                                                     
  File "/opt/conda/lib/python3.6/site-packages/beakerx/runtime.py", line 17, in <module>                                                             
    import os, json, pandas, numpy                                                                                                                   
ModuleNotFoundError: No module named 'pandas'                                                                                                        

ERROR conda.core.link:_execute_actions(339): An error occurred while installing package 'conda-forge::beakerx-0.14.0-py36_1'.                        
LinkError: post-link script failed for package conda-forge::beakerx-0.14.0-py36_1                                                                    
running your command again with `-v` will provide additional information                                                                             
location of failed script: /opt/conda/bin/.beakerx-post-link.sh                                                                                      
==> script messages <==                                                                                                                              
+ /opt/conda/bin/beakerx install                                                                                                                     
Traceback (most recent call last):                                                                                                                   
  File "/opt/conda/bin/beakerx", line 4, in <module>                                                                                                 
    import beakerx                                                                                                                                   
  File "/opt/conda/lib/python3.6/site-packages/beakerx/__init__.py", line 15, in <module>                                                            
    from .runtime import BeakerX                                                                                                                     
  File "/opt/conda/lib/python3.6/site-packages/beakerx/runtime.py", line 17, in <module>                                                             
    import os, json, pandas, numpy                                                                                                                   
ModuleNotFoundError: No module named 'pandas'                                                                                                        


Attempting to roll back.                                                                                                                             

{
  "error": "Multiple Errors Encountered.",
  "errors": [
    {
      "caused_by": "None",
      "error": "LinkError: post-link script failed for package conda-forge::beakerx-0.14.0-py36_1\nrunning your command again with `-v` will provide additional information\nlocation of failed script: /opt/conda/bin/.beakerx-post-link.sh\n==> script messages <==\n+ /opt/conda/bin/beakerx install\nTraceback (most recent call last):\n  File \"/opt/conda/bin/beakerx\", line 4, in <module>\n    import beakerx\n  File \"/opt/conda/lib/python3.6/site-packages/beakerx/__init__.py\", line 15, in <module>\n    from .runtime import BeakerX\n  File \"/opt/conda/lib/python3.6/site-packages/beakerx/runtime.py\", line 17, in <module>\n    import os, json, pandas, numpy\nModuleNotFoundError: No module named 'pandas'\n\n",
      "exception_name": "LinkError",
      "exception_type": "<class 'conda.exceptions.LinkError'>",
      "message": "post-link script failed for package conda-forge::beakerx-0.14.0-py36_1\nrunning your command again with `-v` will provide additional information\nlocation of failed script: /opt/conda/bin/.beakerx-post-link.sh\n==> script messages <==\n+ /opt/conda/bin/beakerx install\nTraceback (most recent call last):\n  File \"/opt/conda/bin/beakerx\", line 4, in <module>\n    import beakerx\n  File \"/opt/conda/lib/python3.6/site-packages/beakerx/__init__.py\", line 15, in <module>\n    from .runtime import BeakerX\n  File \"/opt/conda/lib/python3.6/site-packages/beakerx/runtime.py\", line 17, in <module>\n    import os, json, pandas, numpy\nModuleNotFoundError: No module named 'pandas'\n\n"
    }
  ],
  "exception_name": "CondaMultiError",
  "exception_type": "<class 'conda.CondaMultiError'>"
}
```
Ref: https://github.com/vishnu2kmohan/beakerx-dcos-docker/blob/master/Dockerfile#L171-L185

**Comment by scottdraves** [comment]
Thanks for the report Vishnu, will try to reproduce and get back to you.

**Comment by scottdraves** [comment]
What was in the environment you were updating?

**Comment by vishnu2kmohan** [comment]
Nothing special Scott, it's the stock Miniconda3 (`Miniconda3-4.3.31-Linux-x86_64.sh`) `root` environment that I then `conda update --all` before attempting to update it again with the conda env yml (`beakerx-root-conda-env.yml`)

Steps to reproduce (while running as `root` since I'm installing to `/opt/conda`):
```
bash Miniconda3-4.3.31-Linux-x86_64.sh -u -b -p /opt/conda \
    && /opt/conda/bin/conda config --system --prepend channels conda-forge \
    && /opt/conda/bin/conda config --system --set auto_update_conda false \
    && /opt/conda/bin/conda config --system --set show_channel_urls true \
    && /opt/conda/bin/conda update --json --all -yq \
    && /opt/conda/bin/conda env update --json -q -f beakerx-root-conda-env.yml
```

**Comment by scottdraves** [comment]
OK can reproduce with the following Dockerfile and the above yml:
```
# debian:9.3 - linux; amd64
# https://github.com/docker-library/repo-info/blob/master/repos/debian/tag-details.md#debian93---linux-amd64
FROM debian@sha256:02741df16aee1b81c4aaff4c48d75cc2c308bade918b22679df570c170feef7c

ARG CONDA_DIR="/opt/conda"
ARG CONDA_ENV_YML="beakerx-root-conda-base-env.yml"
ARG CONDA_INSTALLER="Miniconda3-4.3.31-Linux-x86_64.sh"
ARG CONDA_MD5="7fe70b214bee1143e3e3f0467b71453c"
ARG CONDA_URL="https://repo.continuum.io/miniconda"

ARG DISTRO="debian"
ARG REPO="http://cdn-fastly.deb.debian.org"
ARG CODENAME="stretch"

COPY --chown="1000:100" "${CONDA_ENV_YML}" "${CONDA_DIR}/"

RUN echo "deb ${REPO}/${DISTRO} ${CODENAME} main" \
         >> /etc/apt/sources.list \
    echo "deb ${REPO}/${DISTRO}-security ${CODENAME}/updates main" \
         >> /etc/apt/sources.list \
    && apt-get update -yq --fix-missing \
    && apt-get install -yq --no-install-recommends locales \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen \
    && apt-get install -yq --no-install-recommends apt-utils \
    && apt-get -yq dist-upgrade \
    && apt-get install -yq --no-install-recommends \
       bash-completion \
       bzip2 \
       ca-certificates \
       curl

RUN cd /tmp \
    && curl --retry 3 -fsSL -O "${CONDA_URL}/${CONDA_INSTALLER}" \
    && echo "${CONDA_MD5}  ${CONDA_INSTALLER}" | md5sum -c - \
    && bash "./${CONDA_INSTALLER}" -u -b -p "${CONDA_DIR}" \
    && /opt/conda/bin/conda config --system --prepend channels conda-forge \
    && /opt/conda/bin/conda config --system --set auto_update_conda false \
    && /opt/conda/bin/conda config --system --set show_channel_urls true
RUN /opt/conda/bin/conda update --json --all -yq
RUN /opt/conda/bin/conda env update --json -q -f /opt/conda/beakerx-root-conda-base-env.yml
```

**Comment by scottdraves** [comment]
if i just install pandas in a separate conda cmd then it works:
```
RUN /opt/conda/bin/conda update --json --all -yq
RUN /opt/conda/bin/conda install pandas
RUN /opt/conda/bin/conda env update --json -q -f /opt/conda/beakerx-root-conda-base-env.yml
```
here's where beakerx declares a dependency on pandas:
https://github.com/conda-forge/beakerx-feedstock/blob/master/recipe/meta.yaml#L35
so conda appears to be running beakerx post-link before its dependency is installed.
doesn't that make this a conda bug?

**Comment by vishnu2kmohan** [comment]
Heh, I had worked around it the same way you did and given beakerx explicitly depends on `pandas` in its feedstock `meta.yaml` it's almost certainly a conda bug.

Thanks for investigating. We can close this issue. I'll try with a newer conda version (4.4.x) later and see if it resolves deps correctly.

**Comment by scottdraves** [comment]
Cool glad you are not blocked on this.

I have seen similar behavior from conda in other situations & would like to track this down with them.
If this isn't something we can rely on then I would account for it in our installation procedure and documentation. For example, we don't really use pandas during the install, so we could probably refactor a bit to avoid this particular error. We do depend on some of the jupyter utilities so could not avoid it completely but it might be a useful mitigation. Also possible we could remove the "beakerx install" from the conda install complete and leave it to the user to run.  Just need to make sure https://mybinder.org/ could be configured to run it some other way.

**Comment by scottdraves** [comment]
@vishnu2kmohan sounds like conda agrees it should work and they have fixing it on their agenda now.

**Comment by scottdraves** [comment]
note that version 0.15.0 works around this problem by adding a dependency on numpy https://github.com/conda-forge/beakerx-feedstock/commit/f1c92d9611bd1a25fc4190efedfdb19accf233a8
