### ISSUE TITLE
enum not supported with Groovy

### ISSUE THREAD

**Issue by kdorff** [twosigma/beakerx#7208]
I'm running BeakerX 0.15.2. This was also an issue with 0.14.0.

I have an empty Groovy notebook. I add a single code cell

```
enum X {
    A,
    B,
    C
}
```

and execute the notebook. BeakerX response with

```
java.lang.InstantiationException: X
	at com.twosigma.beakerx.groovy.evaluator.GroovyCodeRunner.call(GroovyCodeRunner.java:60)
	at com.twosigma.beakerx.groovy.evaluator.GroovyCodeRunner.call(GroovyCodeRunner.java:36)
Caused by: java.lang.NoSuchMethodException: X.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	at com.twosigma.beakerx.groovy.evaluator.GroovyCodeRunner.call(GroovyCodeRunner.java:60)
	at com.twosigma.beakerx.groovy.evaluator.GroovyCodeRunner.call(GroovyCodeRunner.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

It is possible this is related to https://github.com/twosigma/beakerx/issues/7185 but the reporter of that issue didn't report the specific error.

**Comment by scottdraves** [comment]
thanks.  not related but legit!
