### ISSUE TITLE
BeakerX 0.16.0: Invoking ipython throws AttributeError: 'TerminalInteractiveShell' object has no attribute 'kernel' at beakerx_magics/kernel_magic.py", line 110  while trying to load_ipython_extension

### ISSUE THREAD

**Issue by vishnu2kmohan** [twosigma/beakerx#7288]
```
$ docker run --rm -it vishnumohan/beakerx-dcos bash
beakerx@ac6698017c48:~$ ipython
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.
[TerminalIPythonApp] WARNING | Error in loading extension: beakerx_magics.kernel_magic
Check your config files in /home/beakerx/.ipython/profile_default
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/shellapp.py", line 244, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/extensions.py", line 92, in load_extension
    if self._call_load_ipython_extension(mod):
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/extensions.py", line 139, in _call_load_ipython_extension
    mod.load_ipython_extension(self.shell)
  File "/opt/conda/lib/python3.6/site-packages/beakerx_magics/kernel_magic.py", line 110, in load_ipython_extension
    ipython.kernel.shell_handlers['comm_msg'] = comm_msg
AttributeError: 'TerminalInteractiveShell' object has no attribute 'kernel'
```

**Comment by vishnu2kmohan** [comment]
Removing BeakerX 0.16.0 (`conda remove beakerx`) and downgrading to 0.15.2 (`conda install beakerx=0.15.2`) allows `ipython` to start without any issues:
```
$ conda list | grep beakerx
beakerx                   0.15.2                   py36_1    conda-forge
$ ipython
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
```
Upgrading (back) to BeakerX 0.16.0 (`conda install beakerx=0.16.0`) reproduces the issue:
```
$ conda list | grep beakerx
beakerx                   0.16.0                   py36_1    conda-forge
$ ipython
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.
[TerminalIPythonApp] WARNING | Error in loading extension: beakerx_magics.kernel_magic
Check your config files in /home/beakerx/.ipython/profile_default
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/shellapp.py", line 244, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/extensions.py", line 92, in load_extension
    if self._call_load_ipython_extension(mod):
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/extensions.py", line 139, in _call_load_ipython_extension
    mod.load_ipython_extension(self.shell)
  File "/opt/conda/lib/python3.6/site-packages/beakerx_magics/kernel_magic.py", line 110, in load_ipython_extension
    ipython.kernel.shell_handlers['comm_msg'] = comm_msg
AttributeError: 'TerminalInteractiveShell' object has no attribute 'kernel'

In [1]:
```
Note: Attempting to downgrade directly (i.e., without `conda remove beakerx`) to 0.15.2 from 0.16.2 fails with: `FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.6/site-packages/beakerx/kernel/sparkex/kernel.json'`
```
$ conda install beakerx=0.15.2
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs: 
    - beakerx=0.15.2


The following packages will be DOWNGRADED:

    beakerx: 0.16.0-py36_1 conda-forge --> 0.15.2-py36_1 conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: | + /opt/conda/bin/beakerx uninstall
Disabling tree extension beakerx/tree...
      - Validating: OK
Disabling notebook extension beakerx/extension...
      - Validating: OK
Uninstalling beakerx beakerx/tree
Removing: /opt/conda/share/jupyter/nbextensions/beakerx
Uninstalling beakerx beakerx/extension
Disabling: beakerx
- Writing config: /opt/conda/etc/jupyter
[RemoveKernelSpec] Removed /opt/conda/share/jupyter/kernels/clojure
[RemoveKernelSpec] Removed /opt/conda/share/jupyter/kernels/groovy
[RemoveKernelSpec] Removed /opt/conda/share/jupyter/kernels/java
[RemoveKernelSpec] Removed /opt/conda/share/jupyter/kernels/kotlin
[RemoveKernelSpec] Removed /opt/conda/share/jupyter/kernels/scala
[RemoveKernelSpec] Removed /opt/conda/share/jupyter/kernels/sql

- + /opt/conda/bin/beakerx install
Installing /opt/conda/lib/python3.6/site-packages/beakerx/static -> beakerx
Symlinking: /opt/conda/share/jupyter/nbextensions/beakerx -> /opt/conda/lib/python3.6/site-packages/beakerx/static
- Validating: OK
Installing /opt/conda/lib/python3.6/site-packages/beakerx/static -> beakerx
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable beakerx --py --sys-prefix
    
Enabling tree extension beakerx/tree...
      - Validating: OK
Enabling notebook extension beakerx/extension...
      - Validating: OK
Enabling: beakerx
- Writing config: /opt/conda/etc/jupyter
    - Validating...
      beakerx  OK
[InstallKernelSpec] Installed kernelspec clojure in /opt/conda/share/jupyter/kernels/clojure
[InstallKernelSpec] Installed kernelspec groovy in /opt/conda/share/jupyter/kernels/groovy
[InstallKernelSpec] Installed kernelspec java in /opt/conda/share/jupyter/kernels/java
[InstallKernelSpec] Installed kernelspec kotlin in /opt/conda/share/jupyter/kernels/kotlin
[InstallKernelSpec] Installed kernelspec scala in /opt/conda/share/jupyter/kernels/scala
[InstallKernelSpec] Installed kernelspec sql in /opt/conda/share/jupyter/kernels/sql
Traceback (most recent call last):
  File "/opt/conda/bin/beakerx", line 6, in <module>
    sys.exit(beakerx.run())
  File "/opt/conda/lib/python3.6/site-packages/beakerx/__init__.py", line 47, in run
    parse()
  File "/opt/conda/lib/python3.6/site-packages/beakerx/commands.py", line 65, in parse
    args.func(args)
  File "/opt/conda/lib/python3.6/site-packages/beakerx/install.py", line 203, in install
    _install_beakerx(args)
  File "/opt/conda/lib/python3.6/site-packages/beakerx/install.py", line 194, in _install_beakerx
    _install_kernels()
  File "/opt/conda/lib/python3.6/site-packages/beakerx/install.py", line 98, in _install_kernels
    'beakerx', os.path.join('kernel', kernel, 'kernel.json'))
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1149, in resource_string
    self, resource_name
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1393, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1516, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.6/site-packages/beakerx/kernel/sparkex/kernel.json'

failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::beakerx-0.15.2-py36_1'.
LinkError: post-link script failed for package conda-forge::beakerx-0.15.2-py36_1
running your command again with `-v` will provide additional information
location of failed script: /opt/conda/bin/.beakerx-post-link.sh
==> script messages <==
+ /opt/conda/bin/beakerx install
Installing /opt/conda/lib/python3.6/site-packages/beakerx/static -> beakerx
Symlinking: /opt/conda/share/jupyter/nbextensions/beakerx -> /opt/conda/lib/python3.6/site-packages/beakerx/static
- Validating: OK
Installing /opt/conda/lib/python3.6/site-packages/beakerx/static -> beakerx
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable beakerx --py --sys-prefix
    
Enabling tree extension beakerx/tree...
      - Validating: OK
Enabling notebook extension beakerx/extension...
      - Validating: OK
Enabling: beakerx
- Writing config: /opt/conda/etc/jupyter
    - Validating...
      beakerx  OK
[InstallKernelSpec] Installed kernelspec clojure in /opt/conda/share/jupyter/kernels/clojure
[InstallKernelSpec] Installed kernelspec groovy in /opt/conda/share/jupyter/kernels/groovy
[InstallKernelSpec] Installed kernelspec java in /opt/conda/share/jupyter/kernels/java
[InstallKernelSpec] Installed kernelspec kotlin in /opt/conda/share/jupyter/kernels/kotlin
[InstallKernelSpec] Installed kernelspec scala in /opt/conda/share/jupyter/kernels/scala
[InstallKernelSpec] Installed kernelspec sql in /opt/conda/share/jupyter/kernels/sql
Traceback (most recent call last):
  File "/opt/conda/bin/beakerx", line 6, in <module>
    sys.exit(beakerx.run())
  File "/opt/conda/lib/python3.6/site-packages/beakerx/__init__.py", line 47, in run
    parse()
  File "/opt/conda/lib/python3.6/site-packages/beakerx/commands.py", line 65, in parse
    args.func(args)
  File "/opt/conda/lib/python3.6/site-packages/beakerx/install.py", line 203, in install
    _install_beakerx(args)
  File "/opt/conda/lib/python3.6/site-packages/beakerx/install.py", line 194, in _install_beakerx
    _install_kernels()
  File "/opt/conda/lib/python3.6/site-packages/beakerx/install.py", line 98, in _install_kernels
    'beakerx', os.path.join('kernel', kernel, 'kernel.json'))
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1149, in resource_string
    self, resource_name
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1393, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1516, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.6/site-packages/beakerx/kernel/sparkex/kernel.json'


Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::beakerx-0.15.2-py36_1
running your command again with `-v` will provide additional information
location of failed script: /opt/conda/bin/.beakerx-post-link.sh
==> script messages <==
+ /opt/conda/bin/beakerx install
Installing /opt/conda/lib/python3.6/site-packages/beakerx/static -> beakerx
Symlinking: /opt/conda/share/jupyter/nbextensions/beakerx -> /opt/conda/lib/python3.6/site-packages/beakerx/static
- Validating: OK
Installing /opt/conda/lib/python3.6/site-packages/beakerx/static -> beakerx
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable beakerx --py --sys-prefix
    
Enabling tree extension beakerx/tree...
      - Validating: OK
Enabling notebook extension beakerx/extension...
      - Validating: OK
Enabling: beakerx
- Writing config: /opt/conda/etc/jupyter
    - Validating...
      beakerx  OK
[InstallKernelSpec] Installed kernelspec clojure in /opt/conda/share/jupyter/kernels/clojure
[InstallKernelSpec] Installed kernelspec groovy in /opt/conda/share/jupyter/kernels/groovy
[InstallKernelSpec] Installed kernelspec java in /opt/conda/share/jupyter/kernels/java
[InstallKernelSpec] Installed kernelspec kotlin in /opt/conda/share/jupyter/kernels/kotlin
[InstallKernelSpec] Installed kernelspec scala in /opt/conda/share/jupyter/kernels/scala
[InstallKernelSpec] Installed kernelspec sql in /opt/conda/share/jupyter/kernels/sql
Traceback (most recent call last):
  File "/opt/conda/bin/beakerx", line 6, in <module>
    sys.exit(beakerx.run())
  File "/opt/conda/lib/python3.6/site-packages/beakerx/__init__.py", line 47, in run
    parse()
  File "/opt/conda/lib/python3.6/site-packages/beakerx/commands.py", line 65, in parse
    args.func(args)
  File "/opt/conda/lib/python3.6/site-packages/beakerx/install.py", line 203, in install
    _install_beakerx(args)
  File "/opt/conda/lib/python3.6/site-packages/beakerx/install.py", line 194, in _install_beakerx
    _install_kernels()
  File "/opt/conda/lib/python3.6/site-packages/beakerx/install.py", line 98, in _install_kernels
    'beakerx', os.path.join('kernel', kernel, 'kernel.json'))
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1149, in resource_string
    self, resource_name
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1393, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1516, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.6/site-packages/beakerx/kernel/sparkex/kernel.json'

beakerx@9b04ac7d116d:~$ conda list | grep beakerx
beakerx                   0.16.0                   py36_1    conda-forge
```

**Comment by scottdraves** [comment]
thank you, can reproduce.

**Comment by scottdraves** [comment]
We have merged a fix that avoids the error but something seems really funky about ipykernel when run in ipython compared to jupyter.  maybe related to comment at the top of this file:
https://github.com/ipython/ipykernel/blob/master/ipykernel/zmqshell.py
the method we use to install our magic just isn't there.

**Comment by scottdraves** [comment]
@vishnu2kmohan the workaround for this has been released in 0.16.1.
no error is thrown when ipython starts, but our magics are not installed.
will look into if that is fixable.
