### ISSUE TITLE
Failed to create local dir in /var/lib/mesos/slave/... when trying to connect to Spark

### ISSUE THREAD

**Issue by djannot** [twosigma/beakerx#7490]
I do the following:
```
%classpath add mvn org.apache.spark spark-sql_2.11 2.2.1
org.apache.log4j.Logger.getRootLogger().setLevel(org.apache.log4j.Level.ERROR);
import org.apache.spark.sql.SparkSession
```
Then:
```
val spark = SparkSession.builder()
                        .appName("Simple Application")
                        .master("mesos://leader.mesos:5050")
                        .config("spark.ui.enabled", "false")
                        .getOrCreate()
```
And it restarts the Kernel with the error below:
```
2018-06-06 15:51:53:398 +0000 [scala0] ERROR DiskBlockManager - Failed to create local dir in /var/lib/mesos/slave/slaves/5a1203fc-e150-417d-a56b-0377440ab9c8-S8/frameworks/5a1203fc-e150-417d-a56b-0377440ab9c8-0001/executors/beakerx.e8b68ab1-6974-11e8-a996-fa0f57afcde7.1/runs/6ee20820-45a8-4522-a739-68c8d3f791b1. Ignoring this directory.
java.io.IOException: Failed to create a temp directory (under /var/lib/mesos/slave/slaves/5a1203fc-e150-417d-a56b-0377440ab9c8-S8/frameworks/5a1203fc-e150-417d-a56b-0377440ab9c8-0001/executors/beakerx.e8b68ab1-6974-11e8-a996-fa0f57afcde7.1/runs/6ee20820-45a8-4522-a739-68c8d3f791b1) after 10 attempts!
	at org.apache.spark.util.Utils$.createDirectory(Utils.scala:290)
	at org.apache.spark.storage.DiskBlockManager$$anonfun$createLocalDirs$1.apply(DiskBlockManager.scala:141)
	at org.apache.spark.storage.DiskBlockManager$$anonfun$createLocalDirs$1.apply(DiskBlockManager.scala:139)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
	at org.apache.spark.storage.DiskBlockManager.createLocalDirs(DiskBlockManager.scala:139)
	at org.apache.spark.storage.DiskBlockManager.<init>(DiskBlockManager.scala:42)
	at org.apache.spark.storage.BlockManager.<init>(BlockManager.scala:131)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:351)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:175)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:257)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:432)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2516)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:918)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:910)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:910)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:77)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:82)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:84)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:86)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:88)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:90)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:92)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:94)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:96)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:98)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:100)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:102)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:104)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:106)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:108)
	at $line21.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:110)
	at $line21.$read$$iw$$iw$$iw$$iw.<init>(<console>:112)
	at $line21.$read$$iw$$iw$$iw.<init>(<console>:114)
	at $line21.$read$$iw$$iw.<init>(<console>:116)
	at $line21.$read$$iw.<init>(<console>:118)
	at $line21.$read.<init>(<console>:120)
	at $line21.$read$.<init>(<console>:124)
	at $line21.$read$.<clinit>(<console>)
	at $line21.$eval$.$print$lzycompute(<console>:7)
	at $line21.$eval$.$print(<console>:6)
	at $line21.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.twosigma.beakerx.scala.evaluator.ScalaEvaluatorGlue.evaluate(ScalaEvaluatorGlue.scala:118)
	at com.twosigma.beakerx.scala.evaluator.ScalaCodeRunner.call(ScalaCodeRunner.java:47)
	at com.twosigma.beakerx.scala.evaluator.ScalaCodeRunner.call(ScalaCodeRunner.java:29)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-06-06 15:51:53:430 +0000 [scala0] ERROR DiskBlockManager - Failed to create any local dir.
2018-06-06 17:11:36:331 +0000 [scala0] ERROR DiskBlockManager - Failed to create local dir in /var/lib/mesos/slave/slaves/5a1203fc-e150-417d-a56b-0377440ab9c8-S8/frameworks/5a1203fc-e150-417d-a56b-0377440ab9c8-0001/executors/beakerx.e8b68ab1-6974-11e8-a996-fa0f57afcde7.1/runs/6ee20820-45a8-4522-a739-68c8d3f791b1. Ignoring this directory.
java.io.IOException: Failed to create a temp directory (under /var/lib/mesos/slave/slaves/5a1203fc-e150-417d-a56b-0377440ab9c8-S8/frameworks/5a1203fc-e150-417d-a56b-0377440ab9c8-0001/executors/beakerx.e8b68ab1-6974-11e8-a996-fa0f57afcde7.1/runs/6ee20820-45a8-4522-a739-68c8d3f791b1) after 10 attempts!
	at org.apache.spark.util.Utils$.createDirectory(Utils.scala:290)
	at org.apache.spark.storage.DiskBlockManager$$anonfun$createLocalDirs$1.apply(DiskBlockManager.scala:141)
	at org.apache.spark.storage.DiskBlockManager$$anonfun$createLocalDirs$1.apply(DiskBlockManager.scala:139)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
	at org.apache.spark.storage.DiskBlockManager.createLocalDirs(DiskBlockManager.scala:139)
	at org.apache.spark.storage.DiskBlockManager.<init>(DiskBlockManager.scala:42)
	at org.apache.spark.storage.BlockManager.<init>(BlockManager.scala:131)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:351)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:175)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:257)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:432)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2516)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:918)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:910)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:910)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:77)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:82)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:84)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:86)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:88)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:90)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:92)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:94)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:96)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:98)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:100)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:102)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:104)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:106)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:108)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:110)
	at $line16.$read$$iw$$iw$$iw$$iw.<init>(<console>:112)
	at $line16.$read$$iw$$iw$$iw.<init>(<console>:114)
	at $line16.$read$$iw$$iw.<init>(<console>:116)
	at $line16.$read$$iw.<init>(<console>:118)
	at $line16.$read.<init>(<console>:120)
	at $line16.$read$.<init>(<console>:124)
	at $line16.$read$.<clinit>(<console>)
	at $line16.$eval$.$print$lzycompute(<console>:7)
	at $line16.$eval$.$print(<console>:6)
	at $line16.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.twosigma.beakerx.scala.evaluator.ScalaEvaluatorGlue.evaluate(ScalaEvaluatorGlue.scala:118)
	at com.twosigma.beakerx.scala.evaluator.ScalaCodeRunner.call(ScalaCodeRunner.java:47)
	at com.twosigma.beakerx.scala.evaluator.ScalaCodeRunner.call(ScalaCodeRunner.java:29)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-06-06 17:11:36:335 +0000 [scala0] ERROR DiskBlockManager - Failed to create any local dir.
2018-06-06 17:13:03:075 +0000 [scala0] ERROR DiskBlockManager - Failed to create local dir in /var/lib/mesos/slave/slaves/5a1203fc-e150-417d-a56b-0377440ab9c8-S8/frameworks/5a1203fc-e150-417d-a56b-0377440ab9c8-0001/executors/beakerx.e8b68ab1-6974-11e8-a996-fa0f57afcde7.1/runs/6ee20820-45a8-4522-a739-68c8d3f791b1. Ignoring this directory.
java.io.IOException: Failed to create a temp directory (under /var/lib/mesos/slave/slaves/5a1203fc-e150-417d-a56b-0377440ab9c8-S8/frameworks/5a1203fc-e150-417d-a56b-0377440ab9c8-0001/executors/beakerx.e8b68ab1-6974-11e8-a996-fa0f57afcde7.1/runs/6ee20820-45a8-4522-a739-68c8d3f791b1) after 10 attempts!
	at org.apache.spark.util.Utils$.createDirectory(Utils.scala:290)
	at org.apache.spark.storage.DiskBlockManager$$anonfun$createLocalDirs$1.apply(DiskBlockManager.scala:141)
	at org.apache.spark.storage.DiskBlockManager$$anonfun$createLocalDirs$1.apply(DiskBlockManager.scala:139)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
	at org.apache.spark.storage.DiskBlockManager.createLocalDirs(DiskBlockManager.scala:139)
	at org.apache.spark.storage.DiskBlockManager.<init>(DiskBlockManager.scala:42)
	at org.apache.spark.storage.BlockManager.<init>(BlockManager.scala:131)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:351)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:175)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:257)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:432)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2516)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:918)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:910)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:910)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:77)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:82)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:84)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:86)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:88)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:90)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:92)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:94)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:96)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:98)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:100)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:102)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:104)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:106)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:108)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:110)
	at $line16.$read$$iw$$iw$$iw$$iw.<init>(<console>:112)
	at $line16.$read$$iw$$iw$$iw.<init>(<console>:114)
	at $line16.$read$$iw$$iw.<init>(<console>:116)
	at $line16.$read$$iw.<init>(<console>:118)
	at $line16.$read.<init>(<console>:120)
	at $line16.$read$.<init>(<console>:124)
	at $line16.$read$.<clinit>(<console>)
	at $line16.$eval$.$print$lzycompute(<console>:7)
	at $line16.$eval$.$print(<console>:6)
	at $line16.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.twosigma.beakerx.scala.evaluator.ScalaEvaluatorGlue.evaluate(ScalaEvaluatorGlue.scala:118)
	at com.twosigma.beakerx.scala.evaluator.ScalaCodeRunner.call(ScalaCodeRunner.java:47)
	at com.twosigma.beakerx.scala.evaluator.ScalaCodeRunner.call(ScalaCodeRunner.java:29)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-06-06 17:13:03:078 +0000 [scala0] ERROR DiskBlockManager - Failed to create any local dir.
2018-06-06 17:18:16:059 +0000 [Thread-0] ERROR DiskBlockManager - Failed to create local dir in /var/lib/mesos/slave/slaves/5a1203fc-e150-417d-a56b-0377440ab9c8-S8/frameworks/5a1203fc-e150-417d-a56b-0377440ab9c8-0001/executors/beakerx.e8b68ab1-6974-11e8-a996-fa0f57afcde7.1/runs/6ee20820-45a8-4522-a739-68c8d3f791b1. Ignoring this directory.
java.io.IOException: Failed to create a temp directory (under /var/lib/mesos/slave/slaves/5a1203fc-e150-417d-a56b-0377440ab9c8-S8/frameworks/5a1203fc-e150-417d-a56b-0377440ab9c8-0001/executors/beakerx.e8b68ab1-6974-11e8-a996-fa0f57afcde7.1/runs/6ee20820-45a8-4522-a739-68c8d3f791b1) after 10 attempts!
	at org.apache.spark.util.Utils$.createDirectory(Utils.scala:290)
	at org.apache.spark.storage.DiskBlockManager$$anonfun$createLocalDirs$1.apply(DiskBlockManager.scala:141)
	at org.apache.spark.storage.DiskBlockManager$$anonfun$createLocalDirs$1.apply(DiskBlockManager.scala:139)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
	at org.apache.spark.storage.DiskBlockManager.createLocalDirs(DiskBlockManager.scala:139)
	at org.apache.spark.storage.DiskBlockManager.<init>(DiskBlockManager.scala:42)
	at org.apache.spark.storage.BlockManager.<init>(BlockManager.scala:131)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:351)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:175)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:257)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:432)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2516)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:918)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:910)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:910)
	at com.twosigma.beakerx.widget.SparkContextManager.getSparkSession(SparkContextManager.java:178)
	at com.twosigma.beakerx.widget.SparkContextManager.initSparkContext(SparkContextManager.java:163)
	at com.twosigma.beakerx.widget.SparkContextManager.lambda$createConnectButton$0(SparkContextManager.java:154)
	at com.twosigma.beakerx.widget.Button.executeAction(Button.java:94)
	at com.twosigma.beakerx.widget.CompiledCodeRunner.runCommEvent(CompiledCodeRunner.java:54)
	at com.twosigma.beakerx.widget.Widget.lambda$handleCommEventSync$0(Widget.java:163)
	at com.twosigma.beakerx.handler.KernelHandlerWrapper.wrapBusyIdle(KernelHandlerWrapper.java:25)
	at com.twosigma.beakerx.widget.Widget.handleCommEventSync(Widget.java:163)
	at com.twosigma.beakerx.widget.Button.handleOnClick(Button.java:88)
	at com.twosigma.beakerx.kernel.comm.Comm.handleMsg(Comm.java:273)
	at com.twosigma.beakerx.kernel.handler.CommMsgHandler.handleMsg(CommMsgHandler.java:50)
	at com.twosigma.beakerx.kernel.handler.CommMsgHandler.lambda$handle$0(CommMsgHandler.java:41)
	at com.twosigma.beakerx.handler.KernelHandlerWrapper.wrapBusyIdle(KernelHandlerWrapper.java:25)
	at com.twosigma.beakerx.kernel.handler.CommMsgHandler.handle(CommMsgHandler.java:40)
	at com.twosigma.beakerx.kernel.handler.CommMsgHandler.handle(CommMsgHandler.java:31)
	at com.twosigma.beakerx.socket.KernelSocketsZMQ.handleShell(KernelSocketsZMQ.java:190)
	at com.twosigma.beakerx.socket.KernelSocketsZMQ.run(KernelSocketsZMQ.java:165)
2018-06-06 17:18:16:133 +0000 [Thread-0] ERROR DiskBlockManager - Failed to create any local dir.
```

**Comment by scottdraves** [comment]
Thanks for the report I will look into that, let me get 0.19 released and then i will see if I can reproduce it.  What version are you running and how did you install mesos?  how did you install beakerx?

**Comment by vishnu2kmohan** [comment]
This is because the Spark framework ([MesosCoarseGrainedScheduler](https://github.com/apache/spark/blob/v2.3.0/resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackendSuite.scala)) is thrown off by `${MESOS_DIRECTORY}` which is set to the host path which is bind mounted into the container as `${MESOS_SANDBOX}` (`/mnt/mesos/sandbox`).

If running in a container, `${MESOS_DIRECTORY}` must be [remapped ](https://github.com/vishnu2kmohan/beakerx-dcos-docker/blob/master/jupyter_notebook_config.py#L59) directly to `/mnt/mesos/sandbox` (or some other directly accessible and writeable location within the container - e.g., [`/tmp`](https://github.com/mesosphere/spark-build/blob/master/conf/spark-env.sh#L34-L36))

Note: If you're running the Jupyter Notebook as a container on Apache Mesos or Mesosphere DC/OS you must further [unset](https://github.com/vishnu2kmohan/beakerx-dcos-docker/blob/master/jupyter_notebook_config.py#L61-L66) some environment variables that will interfere with the Spark Driver:
```
MESOS_EXECUTOR_ID
MESOS_FRAMEWORK_ID
MESOS_SLAVE_ID
MESOS_SLAVE_PID
MESOS_TASK_ID
```

**Comment by scottdraves** [comment]
Thank you Vishnu for the explanation.

**Comment by djannot** [comment]
Thanks @vishnu2kmohan
