### ISSUE TITLE
add requests to dependencies

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7609]
https://github.com/twosigma/beakerx-feedstock/blob/master/recipe/meta.yaml#L40

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx-feedstock/commit/808e2e0324cdce41ead8009f067ddc1aee629a23

**Comment by jest** [comment]
Looks like it is missing from 1.0.0, reopen?

```
$ beakerx 
Traceback (most recent call last):
  File "/home/vagrant/jupyterlab/bin/beakerx", line 7, in <module>
    from beakerx import run
  File "/home/vagrant/jupyterlab/lib/python3.6/site-packages/beakerx/__init__.py", line 15, in <module>
    from .runtime import BeakerX
  File "/home/vagrant/jupyterlab/lib/python3.6/site-packages/beakerx/runtime.py", line 17, in <module>
    import os, json, numpy, pandas, requests, base64
ModuleNotFoundError: No module named 'requests'
```
