### ISSUE TITLE
spark demos crash

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7628]
when you start the spark session it crashes with:
```
2018-07-02 17:52:34:620 -0400 [SparkUI-61] WARN  Errors - The following warnings have been detected: WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 2
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JsonMappingException.<init>(Ljava/io/Closeable;Ljava/lang/String;)V
        at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:56)
        at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
        at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:718)
        at org.apache.spark.status.api.v1.JacksonMessageWriter.<init>(JacksonMessageWriter.scala:50)
...
```

**Comment by scottdraves** [comment]
aha https://github.com/twosigma/flint/commit/9baab2b9653c685dd03c6fa10eea23cc0cdb9f87

**Comment by scottdraves** [comment]
tried changing loading of flint to:
```
%%classpath add mvn
com.github.twosigma flint master-b560b000bc-1
org.apache.spark spark-sql_2.11 2.2.1
org.apache.spark spark-mllib_2.11 2.2.1
```
but broken in a different way:
```
2018-07-02 23:01:05:747 -0400 [Thread-0] ERROR KernelSocketsZMQ - java.lang.AbstractMethodError: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/Executor;[Ljava/lang/Object;)Lio/netty/util/concurrent/EventExecutor;
```

**Comment by scottdraves** [comment]
@lmitusinski figured out this works:
```
%%classpath add mvn
io.netty netty-all 4.1.25.Final
io.netty netty-buffer 4.1.25.Final
io.netty netty-common 4.1.25.Final
com.github.twosigma flint master-b560b000bc-1
org.apache.spark spark-sql_2.11 2.2.1
org.apache.spark spark-mllib_2.11 2.2.1
```
and this is related: https://github.com/netty/netty/issues/7605

but now our main SparkUI.ipynb is failing like this:
```
018-07-03 13:46:49:555 -0400 [SparkUI-139] WARN  Errors - The following warnings have been detected: WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 2
com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.7.2
        at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:64)
        at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
        at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:722)
        at org.apache.spark.status.api.v1.JacksonMessageWriter.<init>(JacksonMessageWriter.scala:50)
```

**Comment by scottdraves** [comment]
http://spark.apache.org/releases/spark-release-2-1-3.html maybe related somehow???

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/commit/6db4f638ed9f75a990a2359c220f5aa4a8294192
https://github.com/twosigma/beakerx/commit/243e1d1ae7362e7067a9c4d8c46accba19bffaa0
