### ISSUE TITLE
Yarn install error when building docker image

### ISSUE THREAD

**Issue by erip** [twosigma/beakerx#7709]
I build the base image:

    $ docker build -t beakerx-base:latest -f docker/base/Dockerfile .

then attempt to build the beakerx image:

    $ docker build -t beakerx:latest -f docker/Dockerfile .

and I get the following stacktrace:

```sh
Installing collected packages: beakerx
  Running setup.py develop for beakerx
    Running command /opt/conda/envs/beakerx/bin/python -c "import setuptools, tokenize;__file__='/home/beakerx/beakerx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    running develop
    running js
    Installing build dependencies with yarn.  This may take a while...
    > yarn install
    yarn install v1.7.0
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    error An unexpected error occurred: "https://registry.yarnpkg.com/comment-json/-/comment-json-1.1.3.tgz: unable to get local issuer certificate".
    info If you think this is a bug, please open a bug report with the information provided in "/home/beakerx/js/notebook/yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/beakerx/beakerx/setup.py", line 107, in <module>
        setup(**setup_args)
      File "/opt/conda/envs/beakerx/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/envs/beakerx/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/envs/beakerx/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/conda/envs/beakerx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/beakerx/beakerx/setupbase.py", line 404, in run
        [self.run_command(cmd) for cmd in cmds]
      File "/home/beakerx/beakerx/setupbase.py", line 404, in <listcomp>
        [self.run_command(cmd) for cmd in cmds]
      File "/opt/conda/envs/beakerx/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/envs/beakerx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/beakerx/beakerx/setupbase.py", line 284, in run
        run(['yarn', 'install'], cwd=node_package)
      File "/home/beakerx/beakerx/setupbase.py", line 152, in run
        return check_call(cmd, *args, **kwargs)
      File "/opt/conda/envs/beakerx/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['yarn', 'install']' returned non-zero exit status 1.
Cleaning up...
```

There was no such file as `/home/beakerx/js/notebook/yarn-error.log`, so I wasn't able to inspect it per the error message, but there was a `yarn.lock` file.

**Comment by erip** [comment]
Oh, I'm a total idiot. I suspended my VPN and all was well.
