### ISSUE TITLE
It just doesn't work!

### ISSUE THREAD

**Issue by DVious** [twosigma/beakerx#7711]
For me, at least, I cannot get beakers extensions applied.  I have tried over ten installations, each time clearing out my repo and conda.  

Issues to note:

1.  With every installation attempt, condo fails to solve an environment containing either OpenJDK or maven, which has a dependency on OpenJDK.  I remove the two references, to proceed.
2.  I pin OpenJDK, and Conda reports that, 'OpenJDK 8.121 is already loaded, and will be moved to the top.'  
2a.  Although I've seen no ill-effects, point 2 reminds me that I never attempt to pin maven, after solving the environment.  I will try that before anybody responds.
3.  As I am unsure which of the four installation methods to try, I've tried them all!  I always assume to implement both, 'install for Jupiter', and, 'install for labx', consecutively.  Is this the cause of my troubles?

4.  I almost always have to 'fudge' the installation, when it comes to the line, '(cd beakerx install verbose... )', as no such directory is found.  I work around it, by manually cd'ing into the git cloned file.

5.  Oftentimes, the above-workaround does not work, when installing for labx.  I don't have a labx folder to cd into.  Any relevant folder that I fudge my way into, doesn't seem to have the setup.py file that conda install requires.

Ultimately, and after all of the above,  I find that I have managed to installed jupyter-notebook (at least, it looks like the old notebook).  Certainly, it has no lab-like extensions, or any hint of beakerx.   

But it does launch with 'source activate beakerx/beakerx'.

6.  I would've thought that, if I'd done things correctly, and I'm almost certain I haven't,  I could launch this without having to activate the environment.

**Comment by DVious** [comment]
I may be ready to close this issue!

I think my problem was in interpreting the requirements for all of the packages leading up to beakerx.

Today, I installed jupyter lab, _first_.  
_Then_, I cloned beakerx to /usr/local and followed the second set of instructions -for jupyterlab.  This is currently going through the lengthy tests - a stage which I have reached only once before.

Something to note - I _always_ find that, for the line, '(cd beakerx; pip install -e . --verbose)', the setup.py file is never found.  It seems to be fixed by '(cd beakerx/beakerx; pip install -e . --verbose)'
Similarly, I had to back up to /usr/local/beakerx/, in order to, '(cd js/lab; jupyter labextension install .)'.  
I am presently struggling to get this final line to run to success - any comments on the npm debug-log would really help:

4 verbose run-script [ 'prebuild:src', 'build:src', 'postbuild:src' ]
5 info lifecycle beakerx-jupyterlab@1.0.0~prebuild:src: beakerx-jupyterlab@1.0.0
6 info lifecycle beakerx-jupyterlab@1.0.0~build:src: beakerx-jupyterlab@1.0.0
7 verbose lifecycle beakerx-jupyterlab@1.0.0~build:src: unsafe-perm in lifecycle true
8 verbose lifecycle beakerx-jupyterlab@1.0.0~build:src: PATH: /Users/bg/miniconda/envs/labx/lib/node_modules/npm/node_$
9 verbose lifecycle beakerx-jupyterlab@1.0.0~build:src: CWD: /usr/local/beakerx/js/lab
10 silly lifecycle beakerx-jupyterlab@1.0.0~build:src: Args: [ '-c', 'rimraf dist && tsc --project src' ]
11 silly lifecycle beakerx-jupyterlab@1.0.0~build:src: Returned: code: 2  signal: null
12 info lifecycle beakerx-jupyterlab@1.0.0~build:src: Failed to exec build:src script
13 verbose stack Error: beakerx-jupyterlab@1.0.0 build:src: `rimraf dist && tsc --project src`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/bg/miniconda/envs/labx/lib/node_modules/npm/node_modules/npm-$
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/bg/miniconda/envs/labx/lib/node_modules/npm/node_modules/npm-$
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid beakerx-jupyterlab@1.0.0
15 verbose cwd /usr/local/beakerx/js/lab
16 verbose Darwin 17.5.0
17 verbose argv "/Users/bg/miniconda/envs/labx/bin/node" "/Users/bg/miniconda/envs/labx/bin/npm" "run" "bui$
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error beakerx-jupyterlab@1.0.0 build:src: `rimraf dist && tsc --project src`
22 error Exit status 2

**Comment by DVious** [comment]
npm errno 2 - nothing to process!  So, again, I'm in the wrong directory!

I manually fixed that, and did the same to find the kernel folder (gradlew build).

Everything reports success, and I have a 'Beaker x' tab on-screen.  I just have to figure out how to do anything with it!
