### ISSUE TITLE
Error while run %%python magic command

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7802]
We can see this on http://localhost:8888/notebooks/doc/groovy/GeneralAutotranslation.ipynb
![image](https://user-images.githubusercontent.com/17744188/45825669-71fcb480-bcfb-11e8-8ab7-4e8b981096b9.png)

console log:
```
[W 17:27:00.996 NotebookApp] Notebook doc/groovy/GeneralAutotranslation.ipynb is
 not trusted
[I 17:27:01.591 NotebookApp] Kernel started: 3df49be0-11b6-4192-babf-f21b838b78b
e
2018-09-20 17:27:04:345 +0300 [Thread-1] INFO  log - Logging initialized @2724ms
 to org.eclipse.jetty.util.log.Slf4jLog
2018-09-20 17:27:04:391 +0300 [Thread-1] INFO  Javalin - Starting Javalin ...
2018-09-20 17:27:04:463 +0300 [Thread-1] INFO  Server - jetty-9.4.9.v20180320; b
uilt: 2018-03-20T15:21:10+03:00; git: 1f8159b1e4a42d3f79997021ea1609f2fbac6de5;
jvm 1.8.0_152-release-1056-b12
2018-09-20 17:27:04:503 +0300 [Thread-1] INFO  session - DefaultSessionIdManager
 workerName=node0
2018-09-20 17:27:04:503 +0300 [Thread-1] INFO  session - No SessionScavenger set
, using defaults
2018-09-20 17:27:04:503 +0300 [Thread-1] INFO  session - Scavenging every 600000
ms
2018-09-20 17:27:04:513 +0300 [Thread-1] INFO  ContextHandler - Started i.j.e.j.
start$httpHandler$1@32b455c1{/,null,AVAILABLE}
2018-09-20 17:27:04:543 +0300 [Thread-1] INFO  ContextHandler - Started o.e.j.s.
ServletContextHandler@59e92b96{/,null,AVAILABLE}
2018-09-20 17:27:04:553 +0300 [Thread-1] INFO  AbstractConnector - Started Serve
rConnector@1c5890c6{HTTP/1.1,[http/1.1]}{0.0.0.0:59139}
2018-09-20 17:27:04:553 +0300 [Thread-1] INFO  Server - Started @2919ms
2018-09-20 17:27:04:553 +0300 [Thread-1] INFO  EmbeddedServer - Jetty is listeni
ng on: [http://localhost:59139]
2018-09-20 17:27:04:553 +0300 [Thread-1] INFO  Javalin - Javalin has started \o/

[I 17:27:04.603 NotebookApp] Adapting to protocol v5.1 for kernel 3df49be0-11b6-
4192-babf-f21b838b78be
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Aconda3\envs\beakerx\lib\site-packages\zmq\eventloop\zmqstream.py", l
ine 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\tornado\stack_context.py", lin
e 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\ipykernel\kernelbase.py", line
 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\ipykernel\kernelbase.py", line
 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\ipykernel\kernelbase.py", line
 505, in kernel_info_request
    content, parent, ident)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\jupyter_client\session.py", li
ne 748, in send
    stream.send_multipart(to_send, copy=copy)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\zmq\eventloop\zmqstream.py", l
ine 272, in send_multipart
    self._add_io_state(zmq.POLLOUT)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\zmq\eventloop\zmqstream.py", l
ine 521, in _add_io_state
    self._update_handler(self._state)
  File "C:\Aconda3\envs\beakerx\lib\site-packages\zmq\eventloop\zmqstream.py", l
ine 536, in _update_handler
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "C:\Aconda3\envs\beakerx\lib\site-packages\tornado\platform\asyncio.py",
line 154, in add_callback
    functools.partial(stack_context.wrap(callback), *args, **kwargs))
  File "C:\Aconda3\envs\beakerx\lib\asyncio\base_events.py", line 723, in call_s
oon_threadsafe
    self._write_to_self()
  File "C:\Aconda3\envs\beakerx\lib\asyncio\selector_events.py", line 143, in _w
rite_to_self
    csock.send(b'\0')
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Aconda3\envs\beakerx\Scripts\beakerx-script.py", line 11, in <module>

    load_entry_point('beakerx', 'console_scripts', 'beakerx')()
  File "d:\pr\twosigma\beakerx\beakerx\beakerx\__init__.py", line 46, in run
    parse()
  File "d:\pr\twosigma\beakerx\beakerx\beakerx\commands.py", line 91, in parse
    args.func(args)
  File "d:\pr\twosigma\beakerx\beakerx\beakerx\commands.py", line 65, in start_p
y4j_server
    Py4JServer(args.port, args.pyport, args.kernel, args.context)
  File "d:\pr\twosigma\beakerx\beakerx\beakerx_magics\jvm_kernel_magic.py", line
 101, in __init__
    pep = PythonEntryPoint(kernel_name, context)
  File "d:\pr\twosigma\beakerx\beakerx\beakerx_magics\jvm_kernel_magic.py", line
 71, in __init__
    self.pm = JVMKernelMagic(kernel_name, context)
  File "d:\pr\twosigma\beakerx\beakerx\beakerx_magics\jvm_kernel_magic.py", line
 30, in __init__
    self.start()
  File "d:\pr\twosigma\beakerx\beakerx\beakerx_magics\jvm_kernel_magic.py", line
 38, in start
    self.kc.wait_for_ready()
  File "c:\aconda3\envs\beakerx\lib\site-packages\jupyter_client\blocking\client
.py", line 120, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info
 ```

**Comment by EfimovVladimir** [comment]
after rebuild app the error don't reproduce
