### ISSUE TITLE
Nothing displayed pandas dataframe conda install

### ISSUE THREAD

**Issue by NumesSanguis** [twosigma/beakerx#7819]
After I installed beakerx with `conda install -c conda-forge beakerx ipywidgets` dataframes don't show any output anymore in Jupyter Notebook

Fresh conda setup:

    conda create --name stats python=3.6
    conda activate stats
    conda install pandas
    conda install ipykernel # allows the use of env kernels in jupyter notebook
    conda install ipywidgets  # GUI elements in jupyter notebook
    python -m ipykernel install --user --name stats --display-name "py36 stats"  # enable env as kernel in jupyter notebook
    
    * test everything works*
    jupyter notebook
    import pandas as pd
    df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
    df
    * Standard Jupyter Notebook table shows *
    * --> everything works; shutdown jupyter notebook *
    
    conda install -c conda-forge beakerx ipywidgets
    jupyter notebook
    import pandas as pd
    df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
    df
    * No output (even without importing beakerx) *
    
    conda install -c conda-forge beakerx ipywidgets
    jupyter notebook
    import pandas as pd
    df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
    df
    * No output (even without importing beakerx) *
    
    import pandas as pd
    from beakerx import *
    df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
    df
    * Still no output (even without importing beakerx) *

No output is given anymore when running any commands such as `df` or `display(df)`.
Also, I have the same issue as https://github.com/twosigma/beakerx/issues/7766 in which beakerx is used without importing it.

`conda uninstall beakerx` solves all issues, but I would like fancy tables :')

<details>
  <summary>Jupyter notebook file after install beakerx</summary>

    {
     "cells": [
      {
       "cell_type": "code",
       "execution_count": 2,
       "metadata": {},
       "outputs": [
        {
         "data": {
          "application/vnd.jupyter.widget-view+json": {
           "model_id": "20649fd6d3394c92a6db1f97941f72d8",
           "version_major": 2,
           "version_minor": 0
          }
         },
         "metadata": {},
         "output_type": "display_data"
        }
       ],
       "source": [
        "import pandas as pd\n",
        "df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})\n",
        "df"
       ]
      },
      {
       "cell_type": "code",
       "execution_count": null,
       "metadata": {},
       "outputs": [],
       "source": []
      }
     ],
     "metadata": {
      "kernelspec": {
       "display_name": "py36 stats",
       "language": "python",
       "name": "stats"
      },
      "language_info": {
       "codemirror_mode": {
        "name": "ipython",
        "version": 3
       },
       "file_extension": ".py",
       "mimetype": "text/x-python",
       "name": "python",
       "nbconvert_exporter": "python",
       "pygments_lexer": "ipython3",
       "version": "3.6.6"
      }
     },
     "nbformat": 4,
     "nbformat_minor": 2
    }

</details>

<details>
  <summary>Pandas environment</summary>
  
    conda list

    # packages in environment at /home/*user*/anaconda3/envs/stats:
    #
    # Name                    Version                   Build  Channel
    appdirs                   1.4.3            py36h28b3542_0  
    asn1crypto                0.24.0                   py36_0  
    atomicwrites              1.2.1                      py_0    conda-forge
    attrs                     18.2.0           py36h28b3542_0  
    automat                   0.7.0                    py36_0  
    backcall                  0.1.0                    py36_0  
    beakerx                   1.1.0                    py36_0    conda-forge
    blas                      1.0                         mkl  
    bleach                    2.1.4                    py36_0  
    ca-certificates           2018.8.24            ha4d7672_0    conda-forge
    certifi                   2018.8.24             py36_1001    conda-forge
    cffi                      1.11.5           py36he75722e_1  
    chardet                   3.0.4                 py36_1003    conda-forge
    constantly                15.1.0           py36h28b3542_0  
    cryptography              2.3.1            py36hc365091_0  
    decorator                 4.3.0                    py36_0  
    entrypoints               0.2.3                    py36_2  
    gmp                       6.1.2                h6c8ec71_1  
    html5lib                  1.0.1                    py36_0  
    hyperlink                 18.0.0                   py36_0  
    idna                      2.7                      py36_0  
    incremental               17.5.0                   py36_0  
    intel-openmp              2019.0                      118  
    ipykernel                 5.0.0            py36h39e3cac_0  
    ipython                   7.0.1            py36h39e3cac_0  
    ipython_genutils          0.2.0                    py36_0  
    ipywidgets                7.4.2                      py_0    conda-forge
    jedi                      0.12.1                   py36_0  
    jinja2                    2.10                     py36_0  
    jsonschema                2.6.0                    py36_0  
    jupyter_client            5.2.3                    py36_0  
    jupyter_core              4.4.0                    py36_0  
    libedit                   3.1.20170329         h6b74fdf_2  
    libffi                    3.2.1                hd88cf55_4  
    libgcc-ng                 8.2.0                hdf63c60_1  
    libgfortran-ng            7.3.0                hdf63c60_0  
    libsodium                 1.0.16               h1bed415_0  
    libstdcxx-ng              8.2.0                hdf63c60_1  
    markupsafe                1.0              py36h14c3975_1  
    maven                     3.5.0                         0    conda-forge
    mistune                   0.8.3            py36h14c3975_1  
    mkl                       2019.0                      118  
    mkl_fft                   1.0.6            py36h7dd41cf_0  
    mkl_random                1.0.1            py36h4414c95_1  
    more-itertools            4.3.0                 py36_1000    conda-forge
    nbconvert                 5.3.1                    py36_0  
    nbformat                  4.4.0                    py36_0  
    ncurses                   6.1                  hf484d3e_0  
    notebook                  5.7.0                    py36_0  
    numpy                     1.15.2           py36h1d66e8a_1  
    numpy-base                1.15.2           py36h81de0dd_1  
    openjdk                   8.0.152              h46b5887_1  
    openssl                   1.0.2p               h470a237_0    conda-forge
    pandas                    0.23.4           py36h04863e7_0  
    pandoc                    2.2.3.2                       0  
    pandocfilters             1.4.2                    py36_1  
    parso                     0.3.1                    py36_0  
    pexpect                   4.6.0                    py36_0  
    pickleshare               0.7.5                    py36_0  
    pip                       10.0.1                   py36_0  
    pluggy                    0.7.1                      py_0    conda-forge
    prometheus_client         0.3.1            py36h28b3542_0  
    prompt_toolkit            2.0.5                    py36_0  
    ptyprocess                0.6.0                    py36_0  
    py                        1.6.0                      py_0    conda-forge
    py4j                      0.10.7                     py_1    conda-forge
    pyasn1                    0.4.4            py36h28b3542_0  
    pyasn1-modules            0.2.2                    py36_0  
    pycparser                 2.19                     py36_0  
    pygments                  2.2.0                    py36_0  
    pyopenssl                 18.0.0                   py36_0  
    pysocks                   1.6.8                 py36_1002    conda-forge
    pytest                    3.8.2                 py36_1000    conda-forge
    python                    3.6.6                hc3d631a_0  
    python-dateutil           2.7.3                    py36_0  
    pytz                      2018.5                   py36_0  
    pyzmq                     17.1.2           py36h14c3975_0  
    readline                  7.0                  h7b6447c_5  
    requests                  2.19.1                   py36_1    conda-forge
    send2trash                1.5.0                    py36_0  
    service_identity          17.0.0           py36h28b3542_0  
    setuptools                40.4.3                   py36_0  
    simplegeneric             0.8.1                    py36_2  
    six                       1.11.0                   py36_1  
    sqlite                    3.25.2               h7b6447c_0  
    terminado                 0.8.1                    py36_1  
    testpath                  0.4.2                    py36_0  
    tk                        8.6.8                hbc83047_0  
    tornado                   5.1.1            py36h7b6447c_0  
    traitlets                 4.3.2                    py36_0  
    twisted                   18.7.0           py36h14c3975_1  
    urllib3                   1.23                     py36_1    conda-forge
    wcwidth                   0.1.7                    py36_0  
    webencodings              0.5.1                    py36_1  
    wheel                     0.32.0                   py36_0  
    widgetsnbextension        3.4.2                    py36_0  
    xz                        5.2.4                h14c3975_4  
    zeromq                    4.2.5                hf484d3e_1  
    zlib                      1.2.11               ha838bed_2  
    zope                      1.0                      py36_1  
    zope.interface            4.5.0            py36h14c3975_0

</details>

**Comment by NumesSanguis** [comment]
Even after `conda uninstall beakerx` it still tries to load some modules when starting Jupter Notebook.

<details>
  <summary>Error output</summary>

    [IPKernelApp] WARNING | Error in loading extension: beakerx.autotranslation
    Check your config files in /home/*user*/.ipython/profile_default
    Traceback (most recent call last):
      File "/home/*user*/anaconda3/envs/dl/lib/python3.6/site-packages/IPython/core/shellapp.py", line 244, in init_extensions
        self.shell.extension_manager.load_extension(ext)
      File "/home/*user*/anaconda3/envs/dl/lib/python3.6/site-packages/IPython/core/extensions.py", line 85, in load_extension
        mod = import_module(module_str)
      File "/home/*user*/anaconda3/envs/dl/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'beakerx'
    [IPKernelApp] WARNING | Error in loading extension: beakerx_magics.kernel_magic
    Check your config files in /home/*user*/.ipython/profile_default
    Traceback (most recent call last):
      File "/home/*user*/anaconda3/envs/dl/lib/python3.6/site-packages/IPython/core/shellapp.py", line 244, in init_extensions
        self.shell.extension_manager.load_extension(ext)
      File "/home/*user*/anaconda3/envs/dl/lib/python3.6/site-packages/IPython/core/extensions.py", line 85, in load_extension
        mod = import_module(module_str)
      File "/home/*user*/anaconda3/envs/dl/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'beakerx_magics'
    [IPKernelApp] WARNING | Error in loading extension: beakerx_magics.groovy_magic
    Check your config files in /home/*user*/.ipython/profile_default
    Traceback (most recent call last):
      File "/home/*user*/anaconda3/envs/dl/lib/python3.6/site-packages/IPython/core/shellapp.py", line 244, in init_extensions
        self.shell.extension_manager.load_extension(ext)
      File "/home/*user*/anaconda3/envs/dl/lib/python3.6/site-packages/IPython/core/extensions.py", line 85, in load_extension
        mod = import_module(module_str)
      File "/home/*user*/anaconda3/envs/dl/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'beakerx_magics'
    ...

</details>

**Comment by LeeTZ** [comment]
Hello, @NumesSanguis I cannot easily reproduce the bug, could you double check the installation guide to see if you could reproduce that with a fresh conda env? 
Also, if the dataframes are not showing up for you, could you share if there are any error messages either in browser's console or in your console? That would help us identify the issue. Thanks!

**Comment by NumesSanguis** [comment]
@LeeTZ when I first encountered the new bug I made a new environment exactly following the steps given in my first post and I still got the same error.
Have you tried a new environment with exactly my steps? It might be related to `conda install ipykernel`, `ipywidgets` or `python -m ipykernel install --user --name stats --display-name "py36 stats"`.

I didn't see any clear error messages given in the browser itself. I don't have time for the moment to play around with this, but if I have time later on, I'll put the error output here.

**Comment by dhaitz** [comment]
Hi @NumesSanguis ,

I encountered the same errors when starting Jupyter Notebooks and got rid of them by removing `miniconda3/etc/ipython/ipython_config.py`, which in my case only contained  

    c = get_config()
    c.InteractiveShellApp.extensions = ['beakerx.autotranslation',
    'beakerx_magics.kernel_magic',
    'beakerx_magics.groovy_magic',
    'beakerx_magics.clojure_magic',
    'beakerx_magics.kotlin_magic',
    'beakerx_magics.scala_magic',
    'beakerx_magics.sql_magic',
    'beakerx_magics.java_magic'
    ]
