### ISSUE TITLE
KeyError: 'value' in beakerx/autotranslation.py", line 23, in on_msg_handler (val = content['value']) with JupyterLab 0.35.x

### ISSUE THREAD

**Issue by vishnu2kmohan** [twosigma/beakerx#7849]
We may have an incompatibility issue with BeakerX 1.2.0 and JupyterLab 0.35.4 (and possibly 0.34.x):
```
docker run --rm -it -e ENABLE_SPARK_MONITOR=True -e START_SPARK_HISTORY=True -e START_TENSORBOARD=True -e START_DASK_DISTRIBUTED=True -e START_RAY_HEAD_NODE=True -p 8080:8080 mesosphere/mesosphere-jupyter-service:1.3.0-0.35.4 start.sh jupyter lab --NotebookApp.token='' --NotebookApp.password=''
```
Point your browser to http://localhost:8080 and open a bunch of Notebooks (e.g., one for each of the available kernels) from the JupyterLab UI and then shutdown all the Notebooks and delete their respective `.ipynb` files and try launching another batch of Notebooks. We'll end up with Launcher errors yielding this trace in the `stdout` of the terminal from where the Notebook was launched:
```
[IPKernelApp] ERROR | Exception in comm_msg for 0ea3d263-bca3-44e3-9828-f7261c3ccefb
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/beakerx_magics/kernel_magic.py", line 116, in comm_msg
    comm.handle_msg(msg)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/comm/comm.py", line 159, in handle_msg
    self._msg_callback(msg)
  File "/opt/conda/lib/python3.6/site-packages/beakerx/autotranslation.py", line 23, in on_msg_handler
    val = content['value']
KeyError: 'value'
```

**Comment by vishnu2kmohan** [comment]
Update: This issue with BeakerX 1.2.0 is also reproducible on:
* JupyterLab 0.34.12 (`mesosphere/mesosphere-jupyter-service:1.3.0-0.34.12`)
* JupyterLab 0.33.12 with [Apache Toree v0.3.0-incubating-rc1](https://github.com/apache/incubator-toree/releases/tag/v0.3.0-incubating-rc1) (`mesosphere/mesosphere-jupyter-service:1.3.0-0.33.12-toree-3`)
* JupyterLab 0.33.12 with [Apache Toree v0.2.0-incubating](https://github.com/apache/incubator-toree/releases/tag/v0.2.0-incubating) (`mesosphere/mesosphere-jupyter-service:1.3.0-0.33.12-toree-2`)

Will see if downgrading to BeakerX 1.1.0 helps... :man_shrugging:

**Comment by vishnu2kmohan** [comment]
No dice with JupyterLab 0.35.4 and BeakerX 1.1.0 (`mesosphere/mesosphere-jupyter-service:1.3.0-0.35.4-beakerx-1.1.0`) either :cry:
