### ISSUE TITLE
Start 1.3.0: socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by Hubbitus** [twosigma/beakerx#7959]
```
$ sudo docker run -p 8888:8888 beakerx/beakerx:1.3.0
Execute the command
[I 04:52:15.827 NotebookApp] Writing notebook server cookie secret to /home/beakerx/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/opt/conda/envs/beakerx/lib/python3.7/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/beakerx/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/notebook/notebookapp.py", line 1379, in init_webapp
    self.jinja_environment_options,
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/notebook/notebookapp.py", line 251, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/envs/beakerx/lib/python3.7/site-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/opt/conda/envs/beakerx/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by Hubbitus** [comment]
And what also interesting your [`latest` tag](https://hub.docker.com/r/beakerx/beakerx/tags) does not point on version `1.3.0` released 2 months ago, but `latest` has 7 months age. Is it intentional?

**Comment by Hubbitus** [comment]
If someone interested, I use workaround for now (`docker-compose.yml`):
```yml
version: '3.7'

services:
  beakerx:
    image: beakerx/beakerx:1.3.0
    ports:
      - "7777:8888"
    command: bash -c "start-notebook.sh --ip=$$HOSTNAME"
```

**Comment by vitaly-zverev** [comment]
workaround #2
docker run -dp 8888:8888 --entrypoint='/usr/local/bin/start-notebook.sh'  --name  jupyterlab  beakerx/beakerx:1.3.0 "--ip=127.0.0.1"

docker exec  -u beakerx jupyterlab bash -c "/opt/conda/envs/beakerx/bin/jupyter-notebook  --ip=\$HOSTNAME"

docker exec  -u beakerx jupyterlab bash -c "/opt/conda/envs/beakerx/bin/jupyter-notebook  list"
