### ISSUE TITLE
Cannot start Python kernel after install beakerx

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#8014]
I have a base image of JupyterHub which works well but after adding another layer with beakerx I cannot start kernels any more. Below is the detailed log. There still seems to be some tornado related issues.
```
$ docker run -it     --name jupyterhub-beakerx     --log-opt max-size=50m     --memory=$(($(head -n 1 /proc/meminfo | awk '{print $2}') * 4 / 5))k     --cpus=$((`nproc` - 1))     -p 9000:8000     -e DOCKER_USER=`id -un`     -e DOCKER_USER_ID=`id -u`     -e DOCKER_PASSWORD=`id -un`     -e DOCKER_GROUP_ID=`id -g`     -e DOCKER_ADMIN_USER=`id -un`     -v `pwd`:/workdir     -v `dirname $HOME`:/home_host     dclong/jupyterhub-beakerx
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
id: ‘chdu’: no such user
Adding user chdu to group sudo
[I 2019-03-22 13:26:23.424 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2019-03-22 13:26:23.424 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2019-03-22 13:26:23.426 JupyterHub app:1055] Writing cookie_secret to /root/jupyterhub_cookie_secret
[I 2019-03-22 13:26:23.452 alembic.runtime.migration migration:130] Context impl SQLiteImpl.
[I 2019-03-22 13:26:23.452 alembic.runtime.migration migration:137] Will assume non-transactional DDL.
[I 2019-03-22 13:26:23.661 alembic.runtime.migration migration:356] Running stamp_revision  -> 896818069c98
[I 2019-03-22 13:26:25.829 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2019-03-22 13:26:25.860 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
[I 2019-03-22 13:26:26.019 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
[W 2019-03-22 13:26:26.021 JupyterHub proxy:565] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2019-03-22 13:26:26.021 JupyterHub proxy:567] Starting proxy @ http://0.0.0.0:8000/
13:26:26.256 [ConfigProxy] info: Proxying http://0.0.0.0:8000 to (no default)
13:26:26.260 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
13:26:26.301 [ConfigProxy] info: 200 GET /api/routes
[I 2019-03-22 13:26:26.302 JupyterHub proxy:301] Checking routes
[I 2019-03-22 13:26:26.302 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
13:26:26.306 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
13:26:26.306 [ConfigProxy] info: 201 POST /api/routes/
[I 2019-03-22 13:26:26.307 JupyterHub app:1912] JupyterHub is now running at http://0.0.0.0:8000/
[I 2019-03-22 13:26:45.173 JupyterHub log:158] 302 GET / -> /hub (@10.236.66.120) 1.10ms
[W 2019-03-22 13:26:45.301 JupyterHub base:242] Invalid or expired cookie token
[I 2019-03-22 13:26:45.301 JupyterHub log:158] 302 GET /hub -> /hub/ (@10.236.66.120) 0.87ms
[W 2019-03-22 13:26:45.417 JupyterHub base:242] Invalid or expired cookie token
[I 2019-03-22 13:26:45.418 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@10.236.66.120) 1.58ms
[I 2019-03-22 13:26:45.576 JupyterHub log:158] 200 GET /hub/login (@10.236.66.120) 28.59ms
[I 2019-03-22 13:26:51.972 JupyterHub base:499] User logged in: chdu
[I 2019-03-22 13:26:51.973 JupyterHub log:158] 302 POST /hub/login?next= -> /user/chdu/ (chdu@10.236.66.120) 23.47ms
[I 2019-03-22 13:26:52.159 JupyterHub log:158] 302 GET /user/chdu/ -> /hub/user/chdu/ (@10.236.66.120) 0.99ms
Welcome to Ubuntu 18.10 (GNU/Linux 4.4.0-141-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

[W 2019-03-22 13:26:53.264 JupyterHub auth:642] Failed to open PAM session for chdu: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2019-03-22 13:26:53.264 JupyterHub auth:643] Disabling PAM sessions from now on.
[I 2019-03-22 13:26:53.309 JupyterHub spawner:1100] Spawning jupyterhub-singleuser --port=34107 '--notebook-dir="/workdir"' '--NotebookApp.default_url="/lab"'
[I 2019-03-22 13:26:54.916 SingleUserNotebookApp handlers:179] [beakerx] enabled
[I 2019-03-22 13:26:55.088 SingleUserNotebookApp extension:168] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 2019-03-22 13:26:55.088 SingleUserNotebookApp extension:169] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2019-03-22 13:26:55.228 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.4
[I 2019-03-22 13:26:55.233 JupyterHub log:158] 200 GET /hub/api (@127.0.0.1) 1.05ms
[I 2019-03-22 13:26:55.234 SingleUserNotebookApp notebookapp:1772] Serving notebooks from local directory: /workdir
[I 2019-03-22 13:26:55.234 SingleUserNotebookApp notebookapp:1772] The Jupyter Notebook is running at:
[I 2019-03-22 13:26:55.234 SingleUserNotebookApp notebookapp:1772] http://127.0.0.1:34107/user/chdu/
[I 2019-03-22 13:26:55.234 SingleUserNotebookApp notebookapp:1773] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2019-03-22 13:26:55.617 JupyterHub base:628] User chdu took 2.996 seconds to start
[I 2019-03-22 13:26:55.618 JupyterHub proxy:242] Adding user chdu to proxy /user/chdu/ => http://127.0.0.1:34107
13:26:55.621 [ConfigProxy] info: Adding route /user/chdu -> http://127.0.0.1:34107
13:26:55.621 [ConfigProxy] info: 201 POST /api/routes/user/chdu
[I 2019-03-22 13:26:55.623 JupyterHub log:158] 302 GET /hub/user/chdu/ -> /user/chdu/?redirects=1 (chdu@10.236.66.120) 3312.77ms
[I 2019-03-22 13:26:56.238 JupyterHub log:158] 302 GET /hub/api/oauth2/authorize?client_id=jupyterhub-user-chdu&redirect_uri=%2Fuser%2Fchdu%2Foauth_callback&response_type=code&state=[secret] -> /user/chdu/oauth_callback?code=[secret]&state=[secret] (chdu@10.236.66.120) 204.73ms
[I 2019-03-22 13:26:56.739 JupyterHub log:158] 200 POST /hub/api/oauth2/token (chdu@127.0.0.1) 252.73ms
[I 2019-03-22 13:26:56.991 SingleUserNotebookApp auth:875] Logged-in user {'kind': 'user', 'name': 'chdu', 'admin': True, 'groups': [], 'server': '/user/chdu/', 'pending': None, 'created': '2019-03-22T20:26:25.862808Z', 'last_activity': '2019-03-22T20:26:56.910901Z', 'servers': None}
[I 2019-03-22 13:26:57.065 JupyterHub log:158] 200 GET /hub/api/authorizations/token/[secret] (chdu@127.0.0.1) 249.55ms
[I 2019-03-22 13:27:04.410 SingleUserNotebookApp commands:1484] Node v10.15.0

[I 2019-03-22 13:27:04.950 SingleUserNotebookApp build_handler:43] Build is up to date
[W 2019-03-22 13:27:05.156 SingleUserNotebookApp web:1782] 404 GET /user/chdu/lab/api/workspaces/user/chdu/lab?1553286424889 (10.236.66.120): Workspace 'user/chdu/lab' ('userchdulab-9f7e') not found
[W 2019-03-22 13:27:05.157 SingleUserNotebookApp handlers:563] Workspace 'user/chdu/lab' ('userchdulab-9f7e') not found
[I 2019-03-22 13:27:10.848 SingleUserNotebookApp handlers:153] Creating new notebook in /
[I 2019-03-22 13:27:11.144 SingleUserNotebookApp sign:396] Writing notebook-signing key to /home/chdu/.local/share/jupyter/notebook_secret
[I 2019-03-22 13:27:12.414 SingleUserNotebookApp kernelmanager:164] Kernel started: 5490134f-96ca-4a1a-b313-1e7e30c12d59
[I 2019-03-22 13:27:14.795 SingleUserNotebookApp handlers:190] Adapting to protocol v5.1 for kernel 5490134f-96ca-4a1a-b313-1e7e30c12d59
/usr/local/lib/python3.6/dist-packages/notebook/base/zmqhandlers.py:284: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited
  super(AuthenticatedZMQStreamHandler, self).get(*args, **kwargs)
[I 2019-03-22 13:27:15.270 SingleUserNotebookApp handlers:190] Adapting to protocol v5.1 for kernel 5490134f-96ca-4a1a-b313-1e7e30c12d59
[I 2019-03-22 13:27:15.919 SingleUserNotebookApp handlers:190] Adapting to protocol v5.1 for kernel 5490134f-96ca-4a1a-b313-1e7e30c12d59
[W 2019-03-22 13:27:16.836 SingleUserNotebookApp handlers:254] Replacing stale connection: 5490134f-96ca-4a1a-b313-1e7e30c12d59:a4d296cf-3210-4441-9d7e-965030bb23ee
[I 2019-03-22 13:27:28.925 SingleUserNotebookApp management:320] New terminal with automatic name: 1
[W 2019-03-22 13:27:38.071 SingleUserNotebookApp handlers:254] Replacing stale connection: 5490134f-96ca-4a1a-b313-1e7e30c12d59:f5d880f2-7aa0-48a1-ad19-f67e012a7716
[W 2019-03-22 13:27:59.886 SingleUserNotebookApp handlers:254] Replacing stale connection: 5490134f-96ca-4a1a-b313-1e7e30c12d59:2daadde2-7ce8-4128-b457-22bc9e50580c
[I 2019-03-22 13:28:22.627 SingleUserNotebookApp handlers:190] Adapting to protocol v5.1 for kernel 5490134f-96ca-4a1a-b313-1e7e30c12d59
TermSocket.open: 1
TermSocket.open: Opened 1
[W 2019-03-22 13:28:26.955 SingleUserNotebookApp handlers:254] Replacing stale connection: 5490134f-96ca-4a1a-b313-1e7e30c12d59:a4d296cf-3210-4441-9d7e-965030bb23ee
[W 2019-03-22 13:28:47.193 SingleUserNotebookApp handlers:254] Replacing stale connection: 5490134f-96ca-4a1a-b313-1e7e30c12d59:f5d880f2-7aa0-48a1-ad19-f67e012a7716
[E 2019-03-22 13:28:56.847 SingleUserNotebookApp ioloop:909] Exception in callback <bound method WebSocketMixin.send_ping of <jupyterhub.singleuser.TermSocket object at 0x7fe16ed2b400>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/usr/local/lib/python3.6/dist-packages/notebook/base/zmqhandlers.py", line 175, in send_ping
        if self.stream.closed() and self.ping_callback is not None:
    AttributeError: 'NoneType' object has no attribute 'closed'
[W 2019-03-22 13:29:07.555 SingleUserNotebookApp handlers:254] Replacing stale connection: 5490134f-96ca-4a1a-b313-1e7e30c12d59:2daadde2-7ce8-4128-b457-22bc9e50580c
[E 2019-03-22 13:29:26.848 SingleUserNotebookApp ioloop:909] Exception in callback <bound method WebSocketMixin.send_ping of <jupyterhub.singleuser.TermSocket object at 0x7fe16ed2b400>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/usr/local/lib/python3.6/dist-packages/notebook/base/zmqhandlers.py", line 175, in send_ping
        if self.stream.closed() and self.ping_callback is not None:
    AttributeError: 'NoneType' object has no attribute 'closed'
[E 2019-03-22 13:29:56.847 SingleUserNotebookApp ioloop:909] Exception in callback <bound method WebSocketMixin.send_ping of <jupyterhub.singleuser.TermSocket object at 0x7fe16ed2b400>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/usr/local/lib/python3.6/dist-packages/notebook/base/zmqhandlers.py", line 175, in send_ping
        if self.stream.closed() and self.ping_callback is not None:
    AttributeError: 'NoneType' object has no attribute 'closed'
[E 2019-03-22 13:30:26.848 SingleUserNotebookApp ioloop:909] Exception in callback <bound method WebSocketMixin.send_ping of <jupyterhub.singleuser.TermSocket object at 0x7fe16ed2b400>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/usr/local/lib/python3.6/dist-packages/notebook/base/zmqhandlers.py", line 175, in send_ping
        if self.stream.closed() and self.ping_callback is not None:
    AttributeError: 'NoneType' object has no attribute 'closed'
[E 2019-03-22 13:30:56.848 SingleUserNotebookApp ioloop:909] Exception in callback <bound method WebSocketMixin.send_ping of <jupyterhub.singleuser.TermSocket object at 0x7fe16ed2b400>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/usr/local/lib/python3.6/dist-packages/notebook/base/zmqhandlers.py", line 175, in send_ping
        if self.stream.closed() and self.ping_callback is not None:
    AttributeError: 'NoneType' object has no attribute 'closed'
^C
Interrupted
[I 2019-03-22 13:31:03.276 JupyterHub app:1706] Cleaning up single-user servers...
[I 2019-03-22 13:31:03.276 JupyterHub proxy:627] Cleaning up proxy[42]...
[I 2019-03-22 13:31:03.279 SingleUserNotebookApp notebookapp:1643] Shutting down 1 kernel
[I 2019-03-22 13:31:03.881 SingleUserNotebookApp multikernelmanager:138] Kernel shutdown: 5490134f-96ca-4a1a-b313-1e7e30c12d59
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1404, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
chdu@tiger-2398763:~/archives/docker/docker-jupyterhub-beakerx
$
```

**Comment by LeeTZ** [comment]
Hey are you installing from the dev repo or the latest release?  Haven't looked closely but It could be a tornado issue that we recently addressed but haven't released yet. Can you try tornado<6.0.0 with beakerx?

**Comment by dclong** [comment]
@LeeTZ I confirm that downgrading to Tornado 5.1.1 fix the issue.

**Comment by jaroslawmalekcodete** [comment]
@LeeTZ Is it still valid ?
I think we solved the Tornado problem in the following PR https://github.com/twosigma/beakerx/pull/8012
