### ISSUE TITLE
Windows install fails on 1.4.1

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#8031]
Rerproduced on two different computers with Windows 10:
```
Traceback (most recent call last):
  File "D:\Anaconda\Scripts\beakerx-script.py", line 6, in <module>
    from beakerx import run
  File "D:\Anaconda\lib\site-packages\beakerx\__init__.py", line 20, in <module>
    from .handlers import load_jupyter_server_extension
  File "D:\Anaconda\lib\site-packages\beakerx\handlers.py", line 23, in <module>
    from tornado.simple_httpclient import HTTPStreamClosedError
ImportError: cannot import name 'HTTPStreamClosedError'
```
Probably something is wrong with tornado module.

**Comment by EfimovVladimir** [comment]
@altavir Could you show tornado version on your beakerx environment?
`conda list`

**Comment by altavir** [comment]
It was 5.0.2. I am trying to update it manually.

**Comment by altavir** [comment]
Seems to be working after manual tornado update.

**Comment by EfimovVladimir** [comment]
right, it's a problem with updating `tornado` package.
