### ISSUE TITLE
Error building jupyterlab

### ISSUE THREAD

**Issue by ssadedin** [twosigma/beakerx#8151]
I'm having trouble getting an end to end build to work with the current tree.

Everything is OK through to the last command but then this command:

```
jupyter lab build
```

fails with:

```
[LabBuildApp] > node /data/tools/anaconda3/envs/beakerx_again/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:dev:minimize
[LabBuildApp] yarn run v1.15.2
$ jlpm run build:dev
$ jlpm run build
$ webpack
ModuleNotFoundError: Module not found: Error: Can't resolve '../lib/tree.js' in '/Volumes/Space2/tools/anaconda3/envs/beakerx_again/share/jupyter/lab/staging/node_modules/beakerx-jupyterlab/dist'
    at /Volumes/Space2/tools/anaconda3/envs/beakerx_again/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:925:10
    at /Volumes/Space2/tools/anaconda3/envs/beakerx_again/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Volumes/Space2/tools/anaconda3/envs/beakerx_again/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Volumes/Space2/tools/anaconda3/envs/beakerx_again/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22
...
```

I got it to go a little further by doing this:

```
cd <anaconda env>/share/jupyter/lab/staging/node_modules/beakerx-jupyterlab/dist
mkdir ../lib
cp -R * ../lib/
```
(this just copies the files it's looking for to the place that it is looking for them).

However then that just dies with a similar error but looking for a file that is nowhere in the source tree:

```
ModuleNotFoundError: Module not found: Error: Can't resolve '../lib/td_index.js' in '/Volumes/Space2/tools/anaconda3/envs/beakerx_again/share/jupyter/lab/staging/node_modules/beakerx-jupyterlab/dist'
```

Any hints to get the build working?

**Comment by jaroslawmalekcodete** [comment]
Hi @ssadedin 
I've just built jupyterlab and I have not problems with the "jupyter lab build" command. Everything works.
Please try to clone the repo to new directory and run the installation instructions once again.
Additionally please check if we have the same version of yarn and node.
My versions:
> yarn --version
> 1.19.1

> node -v
> v12.12.0
