### ISSUE TITLE
ipywidgets, pandas, and py4j need to be explicit dependencies

### ISSUE THREAD

**Issue by SalvatoreT** [twosigma/beakerx#8192]
I installed `beakerx` via `pip3 install beakerx`, but when I went to run it, I found out it didn't include `ipywidgets`.
```
21:51 $ beakerx
Traceback (most recent call last):
  File "/usr/local/bin/beakerx", line 5, in <module>
    from beakerx import run
  File "/usr/local/lib/python3.7/site-packages/beakerx/__init__.py", line 15, in <module>
    from .plot import *
  File "/usr/local/lib/python3.7/site-packages/beakerx/plot/__init__.py", line 15, in <module>
    from .chart import *
  File "/usr/local/lib/python3.7/site-packages/beakerx/plot/chart.py", line 15, in <module>
    from beakerx.beakerx_widgets import BeakerxDOMWidget
  File "/usr/local/lib/python3.7/site-packages/beakerx/beakerx_widgets.py", line 15, in <module>
    from ipywidgets import Box, DOMWidget, CoreWidget, \
ModuleNotFoundError: No module named 'ipywidgets'
```
After running `pip3 install ipywidgets`, I ran into a similar issue where `pandas` and `py4j` was required but not installed.

Please add them as explicit dependencies for the pip package to make the install process smoother.

**Comment by SalvatoreT** [comment]
It looks like there are no dependencies listed on the `setup.py` files that `pip` uses. The Python documentation lists [two options to fix this](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires-vs-requirements-files).

**Comment by jimmybow** [comment]
ipywidgets 8 is not surport, please add version info to setup.py
ipywidgets>=7.6,<8
https://github.com/twosigma/beakerx/blob/master/beakerx-dist/setup.py#L56
