### ISSUE TITLE
Kotlin kernel doesn't work

### ISSUE THREAD

**Issue by gailmargolis76** [twosigma/beakerx#8210]
Gives the following errors/warnings:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.twosigma.beakerx.kotlin.evaluator.ReplWithClassLoaderFactory (file:/Users/ghalib.bello/miniconda3/envs/beakerx/lib/python3.5/site-packages/beakerx/kernel/kotlin/lib/kotlin.jar) to field java.lang.ClassLoader.parent
> WARNING: Please consider reporting this to the maintainers of com.twosigma.beakerx.kotlin.evaluator.ReplWithClassLoaderFactory
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 10888 out of bounds for length 10888
> 	at org.jetbrains.org.objectweb.asm.ClassReader.readUnsignedShort(ClassReader.java:2464)
> 	at org.jetbrains.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:2525)
> 	at org.jetbrains.org.objectweb.asm.ClassReader.readModule(ClassReader.java:761)
> 	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:646)
> 	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:507)
> 	at org.jetbrains.kotlin.resolve.jvm.modules.JavaModuleInfo$Companion.read(JavaModuleInfo.kt:67)
> 	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.findSystemModule(CliJavaModuleFinder.kt:44)
> 	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.access$findSystemModule(CliJavaModuleFinder.kt:25)
> 	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:37)
> 	at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:25)
> 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:149)
> 	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:109)
> 	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:133)
> 	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:254)
> 	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:241)
> 	at kotlin.sequences.SequencesKt___SequencesKt.none(_Sequences.kt:1266)
>

**Comment by altavir** [comment]
Kotlin kernel works only on Java 8. There are multiple issues about that already. There is new kernel provided by JetBrains, which fixes it. Let me write a separate issue about it.
