### ISSUE TITLE
Groovy kernel user install

### ISSUE THREAD

**Issue by pavel-kolesnikov** [twosigma/beakerx#8320]
Hi, I'm struggling to get Groovy kernel installed correctly.

I've installed the `beakerx` and `beakerx_kernel_groovy` with `pip install` but no kernel besides IPython is available.

Then I stumbled upon the `beakerx_kernel_groovy install` option and it needs `sudo` (as `beaker install` actually, too. But it has other way  of installation). I did install both packages to user space.
 
Why it wants system-wide install? 

```
$ beakerx_kernel_groovy install
[Errno 13] Permission denied: '/usr/share/jupyter'
Perhaps you want to install with `sudo` or `--user`?
Traceback (most recent call last):
  File "/home/pk/.local/bin/beakerx_kernel_groovy", line 8, in <module>
    sys.exit(run())
  File "/home/pk/.local/lib/python3.10/site-packages/beakerx_groovy/__init__.py", line 22, in run
    parse_kernel_groovy()
  File "/home/pk/.local/lib/python3.10/site-packages/beakerx_groovy/commands.py", line 65, in parse_kernel_groovy
    args.func(args)
  File "/home/pk/.local/lib/python3.10/site-packages/beakerx_groovy/install.py", line 78, in install
    _install_kernels()
  File "/home/pk/.local/lib/python3.10/site-packages/beakerx_groovy/install.py", line 64, in _install_kernels
    subprocess.check_call(install_cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['jupyter', 'kernelspec', 'install', '--sys-prefix', '--replace', '--name', 'groovy', '/tmp/tmpue7fmnqw/groovy']' returned non-zero exit status 1.
```

```
$ beakerx_kernel_groovy --user install
usage: beakerx_kernel_groovy [-h] [--version] {install,uninstall} ...
beakerx_kernel_groovy: error: unrecognized arguments: --user
```

Now, it seems the `beakerx` broke my `jupyter-lab` install.
Upon launch, it now gives message below and start process stops.
```
Plugin 'beakerx:requirejs' is already registered.
```
How unfortunate.

**Comment by jimmybow** [comment]
you just have no Permission .......
just run 
```
pip install beakerx_kernel_groovy; 
beakerx_kernel_groovy install;
```
