### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by amunra** [twosigma/beakerx#8322]
On
```
$ uname -a
Linux blizzard 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

After a successful
```
$ python3 -m pip install beakerx
```

The actual install process failed
```
$ beakerx install
Enabling notebook extension beakerx/extension...
Traceback (most recent call last):
  File "/home/adam/.local/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/home/adam/.local/lib/python3.10/site-packages/jupyter_core/application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/home/adam/.local/lib/python3.10/site-packages/traitlets/config/application.py", line 1043, in launch_instance
    app.start()
  File "/home/adam/.local/lib/python3.10/site-packages/notebook/nbextensions.py", line 972, in start
    super().start()
  File "/home/adam/.local/lib/python3.10/site-packages/jupyter_core/application.py", line 266, in start
    self.subapp.start()
  File "/home/adam/.local/lib/python3.10/site-packages/notebook/nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/home/adam/.local/lib/python3.10/site-packages/notebook/nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
  File "/home/adam/.local/lib/python3.10/site-packages/notebook/nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "/home/adam/.local/lib/python3.10/site-packages/notebook/nbextensions.py", line 369, in _set_nbextension_state_python
    return [_set_nbextension_state(section=nbext["section"],
  File "/home/adam/.local/lib/python3.10/site-packages/notebook/nbextensions.py", line 369, in <listcomp>
    return [_set_nbextension_state(section=nbext["section"],
  File "/home/adam/.local/lib/python3.10/site-packages/notebook/nbextensions.py", line 339, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/home/adam/.local/lib/python3.10/site-packages/notebook/config_manager.py", line 130, in update
    self.set(section_name, data)
  File "/home/adam/.local/lib/python3.10/site-packages/notebook/config_manager.py", line 107, in set
    self.ensure_config_dir_exists()
  File "/home/adam/.local/lib/python3.10/site-packages/notebook/config_manager.py", line 64, in ensure_config_dir_exists
    os.makedirs(self.config_dir, 0o755)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/etc'
Traceback (most recent call last):
  File "/home/adam/.local/bin/beakerx", line 8, in <module>
    sys.exit(run())
  File "/home/adam/.local/lib/python3.10/site-packages/beakerx/__init__.py", line 84, in run
    parse_widgets()
  File "/home/adam/.local/lib/python3.10/site-packages/beakerx/commands.py", line 89, in parse_widgets
    args.func(args)
  File "/home/adam/.local/lib/python3.10/site-packages/beakerx/install.py", line 129, in install
    subprocess.check_call(["jupyter", "nbextension", "enable", "beakerx", "--py", "--sys-prefix"])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['jupyter', 'nbextension', 'enable', 'beakerx', '--py', '--sys-prefix']' returned non-zero exit status 1.
```

.. and no, I'm not giving your install script root permissions :-)

**Comment by jimmybow** [comment]
you need to install jupyter_contrib-nbextensions,  see my dockerfile
https://github.com/jimmybow/docker-java-notebook/blob/master/build/Dockerfile
