### ISSUE TITLE
circular notebook crashes on save/share

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#891]
start with this notebook:
http://sharing.beakernotebook.com/gist/anonymous/b3cf530203926d3a0eaa

run all its cells.  then try to share or save.

you'll get errors like this:
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Object.toJson (http://127.0.0.1:8801/97c7f34/beaker/vendor/bower_components/angular/angular.js:1018:15)
    at publishToWeb (http://127.0.0.1:8801/97c7f34/beaker/plugin/cellmenu/sharing.js:24:69)
    at Object.action (http://127.0.0.1:8801/97c7f34/beaker/plugin/cellmenu/sharing.js:38:11)
    at Object._impl.shareAndOpenPublished (http://127.0.0.1:8801/97c7f34/beaker/app/mainapp/components/notebook/notebook-directive.js:97:32)
    at Object.bkHelper.shareNotebook (http://127.0.0.1:8801/97c7f34/beaker/app/helpers/helper.js:159:29)
    at Object.fileMenuItems.action (http://127.0.0.1:8801/97c7f34/beaker/plugin/menu/file.js:60:18)
    at Scope.$scope.runAction (http://127.0.0.1:8801/97c7f34/beaker/app/utils/basic/commonui.js:187:20)
    at http://127.0.0.1:8801/97c7f34/beaker/vendor/bower_components/angular/angular.js:10168:21
    at http://127.0.0.1:8801/97c7f34/beaker/vendor/bower_components/angular/angular.js:17823:17 angular.js:9383
2Uncaught TypeError: Converting circular structure to JSON angular.js:1018toJson angular.js:1018_notebookModel.toJson sessionmanager.js:87generateBackupData sessionmanager.js:113backup sessionmanager.js:214

after which the app is broken.  we should handle this situation more gracefully.

**Comment by ildipo** [comment]
You can no more save circular objects in the notebook namespace.
