### ISSUE TITLE
Windows batch file does not pass command line arguments

### ISSUE THREAD

**Issue by aolney** [twosigma/beakerx#980]
Like --public-server

Check by adding the following lines to core.bat

```
rem checking command line args
echo on
echo %CMD_LINE_ARGS%
rem done

@rem Execute core
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %CORE_OPTS%  -classpath "%CLASSPATH%" com.twosigma.beaker.core.Main %CMD_LINE_ARGS%
```

Only whitespace is printed, even though --public-server is passed to beaker.command

I briefly tried to add %\* to beaker.command to pass the command line through, and that works, but it causes another bug:

```
 com.twosigma.beaker.core.Main --public-server
Exception in thread "main" com.google.inject.ProvisionException: Guice provision
 errors:

1) Error injecting constructor, java.io.IOException: Cannot run program "sh": Cr
eateProcess error=2, The system cannot find the file specified
  at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.<init>(DefaultBe
akerConfig.java:85)
  at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.class(DefaultBea
kerConfig.java:85)
  while locating com.twosigma.beaker.core.module.config.DefaultBeakerConfig
  while locating com.twosigma.beaker.core.module.config.BeakerConfig
    for parameter 0 at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.<i
nit>(PluginServiceLocatorRest.java:69)
  at com.twosigma.beaker.core.module.URLConfigModule.configureServlets(URLConfig
Module.java:73)
  while locating com.twosigma.beaker.core.rest.PluginServiceLocatorRest

1 error
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java
:1013)
        at com.twosigma.beaker.core.Main.main(Main.java:162)
Caused by: java.io.IOException: Cannot run program "sh": CreateProcess error=2,
The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.<init>(Def
aultBeakerConfig.java:176)
        at com.twosigma.beaker.core.module.config.DefaultBeakerConfig$$FastClass
ByGuice$$d3b17bd0.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance
(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInsta
nce(DefaultConstructionProxyFactory.java:60)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorI
njector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(Constru
ctorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(Pr
oviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.ja
va:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(Provi
derToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(Inter
nalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParam
eterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParam
eterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorI
njector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(Constru
ctorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(Pr
oviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.ja
va:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(Provi
derToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(Inter
nalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:97
8)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.ja
va:1024)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        ... 2 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 29 more

C:\Users\Andrew Olney\Downloads\beaker-notebook-v1.1.2-2-gb1a7d5f-windows>if "1"
 == "0" goto mainEnd

C:\Users\Andrew Olney\Downloads\beaker-notebook-v1.1.2-2-gb1a7d5f-windows>rem Se
t variable CORE_EXIT_CONSOLE if you need the _script_ return code instead of

C:\Users\Andrew Olney\Downloads\beaker-notebook-v1.1.2-2-gb1a7d5f-windows>rem th
e _cmd.exe /c_ return code!

C:\Users\Andrew Olney\Downloads\beaker-notebook-v1.1.2-2-gb1a7d5f-windows>if not
 "" == "" exit 1

C:\Users\Andrew Olney\Downloads\beaker-notebook-v1.1.2-2-gb1a7d5f-windows>exit /
b 1

```

**Comment by scottdraves** [comment]
Thanks for the bug report, we'll look into it.

**Comment by scottdraves** [comment]
OK the above commit will pass through the arguments, but as you point out, --public-server still crashes.
In fact that option was never implemented on Windows, sorry about that.
It shouldn't be too hard though, since the openssl command exists on Windows, and that's what we use to generate the certificates for https.
I filed https://github.com/twosigma/beaker-notebook/issues/984 to track fixing that.
Thanks again for the report.
